export const SIMULATION_WALK_FORWARD_MIN_VOLATILITY_POLICY = Object.freeze({
  version: "walk_forward_minimum_volatility_research_v1",
  universe: "korea_KRW_069500_and_us_USD_VOO_only",
  input: "complete_joint_krw_simple_return_matrix",
  sourceReturnStepCount: 90,
  trainWindowStepCount: 60,
  testWindowStepCount: 10,
  rebalanceCadenceStepCount: 10,
  foldCount: 3,
  covarianceEstimator: "sample_covariance_with_diagonal_shrinkage",
  covarianceShrinkage: 0.1,
  varianceFloor: 1e-12,
  weightPrecisionBps: 1,
  constraints: "long_only_fully_invested",
  portfolioPath:
    "costless_rebalance_at_test_fold_boundary_buy_and_hold_within_fold",
  comparisonPath: "equal_weight_with_identical_rebalance_boundaries",
  annualization: "paired_market_observation_rows_sqrt_252",
  annualizationFactor: 252,
  transactionCost: "zero_research_assumption",
  tax: "zero_research_assumption",
  fxCost: "zero_research_assumption_krw_returns_already_include_fx",
  pointInTimeRule: "train_rows_strictly_precede_test_rows",
  accountBinding: "forbidden",
  targetBinding: "forbidden",
  recommendation: "forbidden",
  orderAuthority: "forbidden",
  persistence: "forbidden",
  interpretation: "retrospective_out_of_sample_research_not_forecast",
} as const);
