CREATE TABLE "account_balance_snapshots" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"legacy_base44_id" varchar(24),
	"date" date NOT NULL,
	"cash" numeric(24, 6),
	"brokerage" numeric(24, 6),
	"isa" numeric(24, 6),
	"irp" numeric(24, 6),
	"is_sample" boolean DEFAULT false NOT NULL,
	"base44_created_at" timestamp with time zone,
	"base44_updated_at" timestamp with time zone,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "daily_portfolio_snapshots" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"legacy_base44_id" varchar(24),
	"snapshot_date" date NOT NULL,
	"account" varchar(50) NOT NULL,
	"account_id" uuid,
	"rule_version" varchar(100),
	"description" text,
	"is_sample" boolean DEFAULT false NOT NULL,
	"cash_value" numeric(24, 6),
	"invested_amount" numeric(24, 6),
	"total_cost" numeric(24, 6),
	"total_market_value" numeric(24, 6),
	"total_pnl" numeric(24, 6),
	"total_return_pct" numeric(20, 6),
	"fx_rate" numeric(20, 6),
	"usdkrw" numeric(20, 6),
	"kr_weight" numeric(20, 6),
	"us_weight" numeric(20, 6),
	"usd_exposure_pct" numeric(20, 6),
	"thematic_weight" numeric(20, 6),
	"num_assets" integer,
	"num_groups" integer,
	"top_holding_name" varchar(255),
	"top_holding_weight" numeric(20, 6),
	"benchmark_value" numeric(24, 6),
	"benchmark_index_value" numeric(24, 6),
	"kodex200_value" numeric(24, 6),
	"kospi200_value" numeric(24, 6),
	"kospi200_index" numeric(24, 6),
	"sp500_index" numeric(24, 6),
	"voo_value" numeric(24, 6),
	"avg_correlation" numeric(20, 6),
	"enb" numeric(20, 6),
	"portfolio_volatility" numeric(20, 6),
	"regime_label" varchar(100),
	"regime_score" numeric(20, 6),
	"captured_at" timestamp with time zone,
	"cycle_start_at" timestamp with time zone,
	"cycle_end_at" timestamp with time zone,
	"base44_created_at" timestamp with time zone,
	"base44_updated_at" timestamp with time zone,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "daily_position_snapshots" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"legacy_base44_id" varchar(24),
	"snapshot_date" date NOT NULL,
	"asset_id" uuid,
	"legacy_asset_id" varchar(24) NOT NULL,
	"ticker" varchar(50),
	"asset_name" varchar(255) NOT NULL,
	"account" varchar(50) NOT NULL,
	"account_id" uuid,
	"market" varchar(20),
	"currency" varchar(10),
	"asset_status" varchar(50),
	"asset_type" varchar(50),
	"category" varchar(100),
	"sector" varchar(100),
	"source_type" varchar(50),
	"exposure_type" varchar(50),
	"legacy_group_id" varchar(24),
	"group_name" varchar(100),
	"price_source" varchar(100),
	"price_basis" varchar(100),
	"description" text,
	"below_ma" boolean DEFAULT false NOT NULL,
	"is_sample" boolean DEFAULT false NOT NULL,
	"quantity" numeric(24, 8),
	"total_quantity" numeric(24, 8),
	"estimated_fractional_quantity" numeric(24, 8),
	"avg_cost" numeric(24, 6),
	"current_price" numeric(24, 6),
	"close_price" numeric(24, 6),
	"unit_price" numeric(24, 6),
	"unit_value_krw" numeric(24, 6),
	"market_value_local" numeric(24, 6),
	"market_value_krw" numeric(24, 6),
	"cost_krw" numeric(24, 6),
	"pnl_krw" numeric(24, 6),
	"pnl_pct" numeric(20, 6),
	"current_weight" numeric(20, 6),
	"target_weight" numeric(20, 6),
	"target_weight_raw" numeric(20, 6),
	"target_weight_effective" numeric(20, 6),
	"trim_target_weight" numeric(20, 6),
	"drift_pct" numeric(20, 6),
	"fx_rate" numeric(20, 6),
	"previous_fx_rate" numeric(20, 6),
	"previous_quantity" numeric(24, 8),
	"previous_unit_price" numeric(24, 6),
	"previous_unit_value_krw" numeric(24, 6),
	"previous_market_value_krw" numeric(24, 6),
	"price_change_krw" numeric(24, 6),
	"fx_change_krw" numeric(24, 6),
	"market_value_change_krw" numeric(24, 6),
	"market_value_change_pct" numeric(20, 6),
	"unit_value_change_krw" numeric(24, 6),
	"unit_value_change_pct" numeric(20, 6),
	"ma_120" numeric(24, 6),
	"fractional_krw_value" numeric(24, 6),
	"fractional_avg_cost" numeric(24, 6),
	"price_date" date,
	"reference_date" date,
	"fx_reference_date" date,
	"previous_reference_date" date,
	"previous_snapshot_date" date,
	"captured_at" timestamp with time zone,
	"cycle_start_at" timestamp with time zone,
	"cycle_end_at" timestamp with time zone,
	"source_created_at" timestamp with time zone,
	"base44_created_at" timestamp with time zone,
	"base44_updated_at" timestamp with time zone,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "fx_rates" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"legacy_base44_id" varchar(24),
	"date" date NOT NULL,
	"usdkrw" numeric(20, 6) NOT NULL,
	"source" varchar(100),
	"status" varchar(50),
	"fetched_at" timestamp with time zone,
	"is_sample" boolean DEFAULT false NOT NULL,
	"base44_created_at" timestamp with time zone,
	"base44_updated_at" timestamp with time zone,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE UNIQUE INDEX "account_balance_snapshots_legacy_base44_id_unique" ON "account_balance_snapshots" USING btree ("legacy_base44_id");--> statement-breakpoint
CREATE INDEX "account_balance_snapshots_date_idx" ON "account_balance_snapshots" USING btree ("date");--> statement-breakpoint
CREATE UNIQUE INDEX "daily_portfolio_snapshots_legacy_base44_id_unique" ON "daily_portfolio_snapshots" USING btree ("legacy_base44_id");--> statement-breakpoint
CREATE INDEX "daily_portfolio_snapshots_date_account_idx" ON "daily_portfolio_snapshots" USING btree ("snapshot_date","account");--> statement-breakpoint
CREATE UNIQUE INDEX "daily_position_snapshots_legacy_base44_id_unique" ON "daily_position_snapshots" USING btree ("legacy_base44_id");--> statement-breakpoint
CREATE INDEX "daily_position_snapshots_date_idx" ON "daily_position_snapshots" USING btree ("snapshot_date");--> statement-breakpoint
CREATE INDEX "daily_position_snapshots_legacy_asset_id_idx" ON "daily_position_snapshots" USING btree ("legacy_asset_id");--> statement-breakpoint
CREATE UNIQUE INDEX "fx_rates_legacy_base44_id_unique" ON "fx_rates" USING btree ("legacy_base44_id");--> statement-breakpoint
CREATE INDEX "fx_rates_date_idx" ON "fx_rates" USING btree ("date");