CREATE TABLE "etf_holdings" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"legacy_base44_id" varchar(24),
	"etf_master_id" uuid,
	"legacy_etf_id" varchar(24),
	"etf_ticker" varchar(50) NOT NULL,
	"etf_name" text NOT NULL,
	"as_of_date" date NOT NULL,
	"holding_symbol" varchar(100),
	"holding_name" text NOT NULL,
	"holding_market" varchar(20),
	"holding_country" varchar(10),
	"currency" varchar(10),
	"sector" varchar(100),
	"industry" varchar(150),
	"security_type" varchar(50),
	"source" varchar(100),
	"source_url" text,
	"notes" text,
	"is_top10" boolean DEFAULT false NOT NULL,
	"is_sample" boolean DEFAULT false NOT NULL,
	"rank" integer,
	"weight_pct" numeric(20, 8),
	"shares" numeric(28, 8),
	"market_value" numeric(28, 8),
	"last_synced_at" timestamp with time zone,
	"base44_created_at" timestamp with time zone,
	"base44_updated_at" timestamp with time zone,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "etf_masters" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"legacy_base44_id" varchar(24),
	"ticker" varchar(50) NOT NULL,
	"name" text NOT NULL,
	"market" varchar(20) NOT NULL,
	"exchange" varchar(100),
	"currency" varchar(10) NOT NULL,
	"issuer" text,
	"isin" varchar(50),
	"asset_class" varchar(100),
	"category_label" text,
	"benchmark_name" text,
	"overlap_group" varchar(150),
	"risk_level" varchar(50),
	"region_focus" varchar(100),
	"currency_exposure" varchar(50),
	"distribution_frequency" varchar(50),
	"etf_strategy" varchar(100),
	"listing_country" varchar(10),
	"leverage_type" varchar(50),
	"data_source" text,
	"official_url" text,
	"notes" text,
	"is_active" boolean DEFAULT true NOT NULL,
	"is_universe_pick" boolean,
	"is_currency_hedged" boolean DEFAULT false NOT NULL,
	"is_inverse" boolean DEFAULT false NOT NULL,
	"is_leveraged" boolean DEFAULT false NOT NULL,
	"is_sample" boolean DEFAULT false NOT NULL,
	"constituent_count" integer,
	"universe_priority" integer,
	"aum" numeric(28, 6),
	"average_volume" numeric(28, 6),
	"expense_ratio" numeric(20, 8),
	"dividend_yield" numeric(20, 8),
	"cost_score" numeric(20, 6),
	"liquidity_score" numeric(20, 6),
	"leverage_factor" numeric(20, 6),
	"rate_sensitivity" numeric(20, 6),
	"account_suitability_json" jsonb,
	"currency_exposure_json" jsonb,
	"region_exposure_json" jsonb,
	"sector_exposure_json" jsonb,
	"region_tags_json" jsonb,
	"sector_tags_json" jsonb,
	"style_tags_json" jsonb,
	"theme_tags_json" jsonb,
	"substitutes_json" jsonb,
	"top10_holdings_json" jsonb,
	"inception_date" date,
	"exposure_as_of_date" date,
	"last_synced_at" timestamp with time zone,
	"base44_created_at" timestamp with time zone,
	"base44_updated_at" timestamp with time zone,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE UNIQUE INDEX "etf_holdings_legacy_base44_id_unique" ON "etf_holdings" USING btree ("legacy_base44_id");--> statement-breakpoint
CREATE INDEX "etf_holdings_ticker_date_idx" ON "etf_holdings" USING btree ("etf_ticker","as_of_date");--> statement-breakpoint
CREATE INDEX "etf_holdings_legacy_etf_date_idx" ON "etf_holdings" USING btree ("legacy_etf_id","as_of_date");--> statement-breakpoint
CREATE INDEX "etf_holdings_master_date_idx" ON "etf_holdings" USING btree ("etf_master_id","as_of_date");--> statement-breakpoint
CREATE INDEX "etf_holdings_holding_symbol_idx" ON "etf_holdings" USING btree ("holding_symbol");--> statement-breakpoint
CREATE UNIQUE INDEX "etf_masters_legacy_base44_id_unique" ON "etf_masters" USING btree ("legacy_base44_id");--> statement-breakpoint
CREATE UNIQUE INDEX "etf_masters_ticker_market_unique" ON "etf_masters" USING btree ("ticker","market");--> statement-breakpoint
CREATE INDEX "etf_masters_ticker_idx" ON "etf_masters" USING btree ("ticker");--> statement-breakpoint
CREATE INDEX "etf_masters_is_active_idx" ON "etf_masters" USING btree ("is_active");