DROP INDEX "daily_portfolio_snapshots_date_account_source_unique";--> statement-breakpoint
DROP INDEX "daily_position_snapshots_date_account_asset_source_unique";--> statement-breakpoint
ALTER TABLE "daily_position_snapshots" ALTER COLUMN "legacy_asset_id" DROP NOT NULL;--> statement-breakpoint
CREATE UNIQUE INDEX "assets_id_account_unique" ON "assets" USING btree ("id","account_id");--> statement-breakpoint
ALTER TABLE "daily_portfolio_snapshots" ADD CONSTRAINT "daily_portfolio_snapshots_owner_user_fk" FOREIGN KEY ("canonical_owner_user_id") REFERENCES "public"."app_users"("id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "daily_portfolio_snapshots" ADD CONSTRAINT "daily_portfolio_snapshots_account_owner_fk" FOREIGN KEY ("account_id","canonical_owner_user_id") REFERENCES "public"."accounts"("id","canonical_owner_user_id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "daily_position_snapshots" ADD CONSTRAINT "daily_position_snapshots_owner_user_fk" FOREIGN KEY ("canonical_owner_user_id") REFERENCES "public"."app_users"("id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "daily_position_snapshots" ADD CONSTRAINT "daily_position_snapshots_account_owner_fk" FOREIGN KEY ("account_id","canonical_owner_user_id") REFERENCES "public"."accounts"("id","canonical_owner_user_id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "daily_position_snapshots" ADD CONSTRAINT "daily_position_snapshots_asset_account_fk" FOREIGN KEY ("asset_id","account_id") REFERENCES "public"."assets"("id","account_id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
CREATE UNIQUE INDEX "accounts_canonical_owner_code_unique" ON "accounts" USING btree ("canonical_owner_user_id","code") WHERE "accounts"."canonical_owner_user_id" is not null;--> statement-breakpoint
CREATE UNIQUE INDEX "daily_portfolio_snapshots_date_account_source_unique" ON "daily_portfolio_snapshots" USING btree ("canonical_owner_user_id","snapshot_date","account","source") WHERE "daily_portfolio_snapshots"."canonical_owner_user_id" is not null;--> statement-breakpoint
CREATE UNIQUE INDEX "daily_position_snapshots_date_account_asset_source_unique" ON "daily_position_snapshots" USING btree ("canonical_owner_user_id","snapshot_date","account","asset_id","source") WHERE "daily_position_snapshots"."asset_id" is not null and "daily_position_snapshots"."canonical_owner_user_id" is not null;--> statement-breakpoint
ALTER TABLE "daily_portfolio_snapshots" ADD CONSTRAINT "daily_portfolio_snapshots_generated_owner_check" CHECK ("daily_portfolio_snapshots"."source" <> 'varda_manual_daily_snapshot' or ("daily_portfolio_snapshots"."canonical_owner_user_id" is not null and (("daily_portfolio_snapshots"."account" = 'all' and "daily_portfolio_snapshots"."account_id" is null) or ("daily_portfolio_snapshots"."account" in ('brokerage', 'isa', 'irp') and "daily_portfolio_snapshots"."account_id" is not null)))) NOT VALID;--> statement-breakpoint
ALTER TABLE "daily_position_snapshots" ADD CONSTRAINT "daily_position_snapshots_generated_owner_check" CHECK ("daily_position_snapshots"."source" <> 'varda_manual_daily_snapshot' or ("daily_position_snapshots"."canonical_owner_user_id" is not null and "daily_position_snapshots"."account_id" is not null and "daily_position_snapshots"."asset_id" is not null and "daily_position_snapshots"."account" in ('brokerage', 'isa', 'irp'))) NOT VALID;--> statement-breakpoint
ALTER TABLE "daily_position_snapshots" ADD CONSTRAINT "daily_position_snapshots_asset_identity_check" CHECK ("daily_position_snapshots"."asset_id" is not null or "daily_position_snapshots"."legacy_asset_id" is not null);
