/** System-owned portfolio copy; holding and account names remain unchanged. */
export const PORTFOLIO_COPY: Readonly<Record<string, string>> = {
  "투입금 흐름": "Funding flow",
  "신규": "New cash",
  "· 계산상 매도": "· Calculated sales",
  "배분안 비교": "Compare allocations",
  "최종 배분": "Final allocation",
  "추세 적용 전": "Before trend adjustment",
  "배분 재원": "Available funds",
  "목표": "Target",
  "최종 배분 후": "After final allocation",
  "목표 비중": "Target weight",
  "추세 적용 전보다 현금 잔액": "Cash balance versus the unadjusted plan",
  "기본 매수안보다 매수금": "Purchase amount versus the base plan",
  "증가": "Increase",
  "감소": "Decrease",
  "계산 로직 보기": "Calculation details",
  "이번 추가 투입안이 만들어진 과정": "How this contribution plan was calculated",
  "실제 주문이 아닌 읽기 전용 계산입니다. 각 단계의 재원과 종목별 판단을 그대로 표시합니다.": "This is a read-only calculation, with the funding at each step and the rationale for each holding. No orders are placed.",
  "계산 로직 닫기": "Close calculation details",
  "금액 흐름": "Funding steps",
  "신규 투입금": "New contribution",
  "계산상 매도": "Calculated sales",
  "매수 가능 재원": "Available to invest",
  "최종 매수 배분": "Final purchases",
  "남는 현금": "Remaining cash",
  "1. 초과 종목 정리": "1. Trim overweight holdings",
  "2. MA120 매수 강도": "2. MA120 purchase intensity",
  "자산 성격별로 목표 부족액 조정": "Adjust the target shortfall by asset class",
  "추세 필터가 꺼져 있어 원래 목표비중을 사용합니다.": "The trend filter is off, so original target weights are used.",
  "금·채권은 감액하지 않습니다. MA120 아래 3% 구간은 선형 보간하고, 그 아래에서는 자산군 배율을 전부 적용합니다. 근거가 없는 종목은 임의 감액하지 않습니다.": "Gold and bonds are exempt. Adjustment is interpolated over the 3% band below MA120; the full asset-class multiplier applies further below. Missing evidence does not trigger an arbitrary reduction.",
  "3. 집행 참고기준": "3. Execution reference",
  "충족": "Met",
  "미충족": "Not met",
  "배분 공식": "Allocation formula",
  "유효 목표액 = (현재 총평가액 + 신규 투입금) × 목표비중 × MA120 배율": "Effective target value = (current portfolio value + new contribution) × target weight × MA120 multiplier",
  "종목별 부족액 = 유효 목표액 − 계산상 매도 후 평가액 (0 미만이면 0)": "Holding shortfall = effective target value − value after calculated sales (floored at zero)",
  "신규 투입금 + 계산상 매도대금을 부족액 비례로 배분합니다. 매도 종목은 다시 매수하지 않습니다. 원 단위 최대잔여 방식으로 결정하며 매도는 보유 평가액, 매수는 유효 부족액을 넘지 않습니다.": "New contributions and calculated sale proceeds are allocated in proportion to shortfalls. Sold holdings are not repurchased. Whole-won amounts use the largest-remainder method; sales cannot exceed holding value and purchases cannot exceed the effective shortfall.",
  "목표 0% 종목도 손실이 아니고 원가 근거가 있을 때 정리합니다. 원 단위로 표현할 수 없는 1원 미만 평가액은 남을 수 있습니다. 수수료·세금·주문 단위는 반영하지 않은 금액 계획입니다.": "Zero-target holdings are closed only with verified cost basis and no loss. Values below one won can remain. Fees, taxes and order-lot constraints are not included.",
  "종목별 계산 근거": "Calculation evidence by holding",
  "원래 목표로 계산한 금액과 MA120 반영 후 최종 금액을 함께 비교합니다.": "Compare the original target-based purchase plan with the final MA120-adjusted amounts.",
  "개 종목": " holdings",
  "종목": "Holding",
  "현재 → 목표": "Current → target",
  "평가손익": "Unrealized return",
  "기본 매수안": "Base purchase plan",
  "MA 반영 목표": "MA-adjusted target",
  "최종 결과": "Final result",
  "판단 이유": "Rationale",
  "목표 0%": "Target 0%",
  "근거 없음": "No evidence",
  "부족액": "Shortfall",
  "현재 계산 범위": "Current calculation scope",
  "원 서비스 후반부에 있던 환율 진입시점, 위험기여, 시장 레짐, 뉴스, 성과감시 감액은 사용자별 정규화 근거가 아직 없어 이번 계산에 임의로 넣지 않았습니다. 근거가 연결되면 같은 단계에 추가할 수 있습니다.": "FX entry timing, risk contribution, market regime, news and performance-monitoring reductions are excluded because normalized evidence for each user is not yet available. They can be added when verified data is connected.",
  "유지": "Hold",
  "목표가 0%이고 원가가 확인되며 손실이 없어 원 단위로 정리합니다. 1원 미만 평가액은 남을 수 있습니다.": "The target is 0%, cost basis is verified and the holding is not at a loss. The calculation closes it in whole won; values below one won can remain.",
  "원가 근거와 0 이상 손익을 확인했습니다. 투입 후 총액 기준 목표의 105%까지 계산상 매도합니다.": "Cost basis and a nonnegative return are verified. The calculated sale reduces the holding to 105% of its target, using the portfolio value after the contribution.",
  "손실 중이므로 매도하지 않습니다.": "This holding is at a loss, so it is not sold.",
  "매입원가 근거가 없어 매도하지 않습니다.": "Cost basis is unavailable, so this holding is not sold.",
  "MA120 감액 제외 자산입니다.": "This asset is exempt from MA120 reductions.",
  "추세 필터 또는 종목별 MA 규칙이 꺼져 있습니다.": "The trend filter or this holding’s MA rule is off.",
  "MA120 근거가 없어 목표를 임의 감액하지 않습니다.": "MA120 evidence is missing, so the target is not arbitrarily reduced.",
  "계산상 매도 후 유효 목표 부족액에 비례해 매수금을 배분했습니다.": "Purchases are allocated in proportion to effective target shortfalls after calculated sales.",
  "부족액은 있으나 원 단위 상한과 재원 배분 결과 매수금이 없습니다.": "A shortfall exists, but whole-won limits and available-fund allocation result in no purchase.",
  "유효 목표 부족액이 없어 추가 매수하지 않습니다.": "There is no effective target shortfall, so no additional purchase is made.",
  "다음 투입의 균형.": "Balance your next move.",
  "실제 보유자산과 연결되지 않은 디자인 미리보기입니다.": "Design preview using sample data, unconnected to actual holdings.",
  "예시 데이터": "Sample data",
  "목표비중 설정": "Set target weights",
  "목표비중": "Target weights",
  "배분의 시작은 목표비중에서": "Start with your target weights",
  "계산 근거를": "Review the",
  "확인해 주세요.": "calculation evidence.",
  "현재 배분안을 계산할 수 없습니다.": "An allocation cannot currently be calculated.",
  "총 매수": "Total purchases",
  "종목별 전체 배분안": "Full allocation by holding",
  "목표 부족분과 MA120 근거를 반영한 계산입니다. 남는 재원은 현금으로 유지됩니다. MA120": "This calculation uses target shortfalls and MA120 evidence. Unallocated funds remain in cash. MA120",
  "미적용": "Not applied",
  "· 일부 근거 부족": "· Some evidence missing",
  "보유 종목 관리": "Manage holdings",
  "비중·자금 흐름": "Weights & funding",
  "추가투입 전후 변화": "Before and after contribution",
  "계산 결과만 제공하며 실제 주문은 실행하지 않습니다.": "Calculation only. No orders are placed.",
  "계산 근거 확인": "Review calculation evidence",
  "배분안을 계산할 수 없는 이유": "Why this allocation is unavailable",
  "주요 배분": "Featured allocations",
  "금액 순": "By amount:",
  "종목 · 전체": " holdings · Total ",
  "매도": "Sell",
  "매수": "Buy",
  "계산된 매수·매도 종목이 없습니다. 재원은 현금으로 유지합니다.": "No purchases or sales were calculated. Available funds remain in cash.",
  "지금은 배분안을 계산할 수 없습니다": "An allocation cannot be calculated yet",
  "이 범위에 저장된 목표비중이 없습니다. 목표비중 화면에서 먼저 설정해 주세요.": "No target weights are saved for this scope. Set them on the target-weights page first.",
  "현재 목표비중 승인본이 하나로 확정되지 않았습니다.": "A single approved target-weight policy has not been established.",
  "목표비중을 저장한 뒤 보유종목 구성이 바뀌었습니다. 목표비중을 다시 확인해 주세요.": "Holdings have changed since target weights were saved. Review the target weights.",
  "저장된 목표비중의 적용 시작일 전입니다.": "The saved target weights are not effective yet.",
  "저장된 목표비중의 무결성을 확인할 수 없습니다.": "The integrity of the saved target weights could not be verified.",
  "현재 범위의 보유종목 구성을 계산에 사용할 수 없습니다.": "The holdings in this scope cannot be used for this calculation.",
  "이 계정에 승인된 목표비중이 없습니다.": "This account has no approved target weights.",
  "승인된 목표비중 상태가 충돌합니다.": "The approved target-weight states conflict.",
  "목표비중의 적용 시작일 전입니다.": "The target weights are not effective yet.",
  "현재 보유 종목과 승인된 목표비중의 종목 구성이 다릅니다.": "The current holdings do not match the approved target-weight universe.",
  "승인된 목표비중 해시가 일치하지 않습니다.": "The approved target-weight hash does not match.",
  "목표비중 합계가 100%가 아닙니다.": "Target weights must add up to 100%.",
  "매수할 수 없는 목표 종목이 있습니다.": "A target holding cannot be purchased.",
  "현재 평가액의 계정 범위가 일치하지 않습니다.": "The account scope of the current valuation does not match.",
  "일부 목표 종목의 현재 평가액이 없습니다.": "A current valuation is missing for some target holdings.",
  "현재 평가액 종목 식별자가 중복되었습니다.": "Current valuation holding identifiers are duplicated.",
  "투입 금액은 1원 이상의 정수여야 합니다.": "The contribution must be a whole-won amount of at least KRW 1.",
  "계산에 사용할 보유 평가액이 없습니다.": "No holding valuations are available for this calculation.",
  "일부 종목의 평가액이 없거나 유효하지 않습니다.": "Some holding valuations are missing or invalid.",
  "일부 종목의 매입원가 값이 유효하지 않습니다.": "Some holding cost-basis values are invalid.",
  "목표비중은 0~100% 범위여야 합니다.": "Each target weight must be between 0% and 100%.",
  "선택 범위의 목표비중 합계가 100%가 아닙니다.": "Target weights for the selected scope do not add up to 100%.",
  "같은 종목의 보유 식별자가 중복되어 계산을 중단했습니다.": "Duplicate holding identifiers were found, so the calculation was stopped.",
  "매도 기준이나 집행 참고비율이 유효하지 않습니다.": "The sale threshold or execution reference ratio is invalid.",
  "금액 합계와 원 단위 배분을 검증하지 못했습니다.": "The total amounts and whole-won allocation could not be verified.",
  "부족 비중을 매수 가능한 종목에 배분할 수 없습니다.": "The target shortfall cannot be allocated to purchasable holdings.",
  "종목 / 계좌": "Holding / account",
  "현재 → 투입 후": "Current → after contribution",
  "계산 금액": "Calculated amount",
  "종목별 배분 결과": "Allocation results by holding",
  "배분 요약": "Allocation summary",
  "배분 금액": "Allocated amount",
  "현금 보류": "Cash retained",
  "유효 목표 부족분과 원 단위 배분 후 잔액": "Balance after effective shortfalls and whole-won allocation",
  "배분 종목": "Recipients",
  "목표 거리": "Distance from target",
  "현재 비중과 동일": "Unchanged from current weights",
  "비중 변화": "Weight changes",
  "현재": "Current",
  "투입 후": "After contribution",
  "계산 근거": "Calculation evidence",
  "초과 종목의 계산상 매도, 매도금 재사용, MA120 조정과 종목별 최종 금액을 단계별로 확인합니다.": "Review calculated sales of overweight holdings, reinvested proceeds, MA120 adjustments and final amounts for each holding, step by step.",
  "적용 · 기준일": "effective · As of",
  "읽기 전용 계산 · 주문, 저장, 매도 없음": "Read-only calculation · No orders or saved changes",
  "추세 필터 꺼짐 · 기본 배분 사용": "Trend filter off · Base allocation used",
  "MA120 근거 조회 실패 · 기본 배분 사용": "MA120 evidence query failed · Base allocation used",
  "사용 가능한 가격 이력 없음 · 기본 배분 사용": "No usable price history · Base allocation used",
  "추가 투입 계산": "Additional contribution calculator",
  "얼마를 더 투자할까요?": "How much will you add?",
  "원": "KRW",
  "투입 금액 빠른 선택": "Contribution presets",
  "만": " × 10,000 KRW",
  "계산 중": "Calculating",
  "배분안 계산": "Calculate allocation",
  "현재 가격과 목표를 계산하고 있어요": "Calculating current prices and targets",
  "계산 완료": "Calculation complete",
  "계산 근거 확인 필요": "Calculation evidence needs review",
  "대표 배분 결과": "Featured allocation results",
  "매수 가능 재원의 배분": "Allocation of available funds",
  "배분 가능한 종목 없음": "No eligible recipients",
  "배분 종목 선택": "Select an allocation",
  "증권": "Brokerage",
  "전체": "All",
  "직접 보유 집중도·통화 노출": "Direct-holding concentration & currency exposure",
  "의 현재 평가액을 직접 보유 종목 기준으로 계산했습니다. ETF 내부 구성, 목표비중, 추천, 주문은 포함하지 않습니다.": ": Calculated from current direct-holding values. ETF constituents, target weights, recommendations and orders are excluded.",
  "평가 완전성": "Valuation coverage",
  "평가액": "Portfolio value",
  "0에 가까울수록 분산": "Closer to zero means less concentration",
  "1 / 보유비중 제곱합": "1 / sum of squared holding weights",
  "유효 종목 수": "Effective holdings",
  "최대 보유비중": "Largest holding",
  "직접 보유 상위 3개 합계": "Combined weight of the three largest direct holdings",
  "상위 3개 집중도": "Top-three concentration",
  "통화별 노출": "Currency exposure",
  "개": " holdings",
  "식별 가능하고 평가액이 있는 직접 보유 종목이 없어 집중도와 통화 노출을 계산하지 않았습니다.": "No identifiable direct holdings with a valuation are available, so concentration and currency exposure were not calculated.",
  "표시된 값은 확인 가능한 종목만의 부분 계산입니다. 평가 제외": "Partial calculation using only verifiable holdings. Excluded:",
  "개 · 식별 불가": " · Unidentified:",
  "개 · 평가액 오류": " · Invalid valuations:",
  "평가 근거": "Valuation evidence",
  "행 · identity: account + market + currency + ticker": " rows · Identity: account + market + currency + ticker",
  "완전": "Complete",
  "부분 계산": "Partial calculation",
  "계산 불가": "Unavailable",
  "자산 배분": "Asset allocation",
  "비중 시각화": "Allocation chart type",
  "원형": "Ring",
  "비중 지도": "Weight map",
  "포트폴리오 핵심 수치": "Portfolio key figures",
  "종목 코드 없음": "No ticker",
  "목표보다 낮음": "Below target",
  "목표 근접": "Near target",
  "목표보다 높음": "Above target",
  "목표 없음": "No target",
  "선택 종목 근거": "Selected holding evidence",
  "비중 종목 선택": "Select a holding",
  "편차": "Deviation",
  "현재 표시할 수 있는 보유 종목이 없습니다.": "No holdings are currently available to display.",
  "기준일": "As of",
  "· 읽기 전용 분석": "· Read-only analysis",
  "종목·그룹 비중": "Holdings & groups",
  "선택 종목과 그룹별 비중": "Selected holding and group weights",
  "그룹 비중 · 현재 / 승인 목표": "Group weights · Current / approved target",
  "현재 비중": "Current weight",
  "현재 / 목표": "Current / target",
  "승인된 목표비중과 현재 평가액을 비교한 읽기 전용 근거입니다.": "Read-only evidence comparing approved target weights with current valuations.",
  "현재 범위에 적용된 승인 목표가 없어 보유 근거만 표시합니다.": "No approved targets apply to this scope, so only holding evidence is shown.",
  "미분류": "Ungrouped",
  "보유 종목별 평가액 비중": "Portfolio value by holding",
  "살펴보는 종목": "Exploring holding",
  "선택한 종목": "Selected holding",
  "보유 종목 없음": "No holdings",
  "조각을 선택해 비중과 목표를 비교하세요": "Select a segment to compare current and target weights",
  "직접 보유 USD 환율 충격 실험": "Direct USD exposure: FX shock experiment",
  "USD 직접 보유 종목의 현지 가격은 고정하고 USD/KRW만 바뀐다고 가정합니다. 원화 상장 ETF의 해외 구성 종목은 추정하지 않습니다.": "Local prices of direct USD holdings stay fixed; only USD/KRW changes. Overseas constituents of KRW-listed ETFs are not estimated.",
  "USD/KRW 변동률": "USD/KRW change",
  "USD 직접 노출": "Direct USD exposure",
  "계산 가능한 직접 보유 자산 기준": "Based on direct holdings with valid valuations",
  "USD 비중": "USD weight",
  "가정 환율": "Assumed exchange rate",
  "현지 가격 고정 가정": "Assuming unchanged local prices",
  "평가액 영향": "Valuation impact",
  "수익률 예측이 아닌 평가액 변화폭": "Valuation change, not a return forecast",
  "전체 영향": "Overall impact",
  "충격 후 평가액": "Value after shock",
  "현재 계산 가능한 직접 보유 자산만 사용 · 제외/식별 불가/평가 오류": "Uses only direct holdings with calculable values · Excluded / unidentified / invalid:",
  "건 · 브라우저에서만 계산하며 저장하지 않음 · 전망, VaR, 추천, 주문 아님": " · Calculated only in your browser and not saved · Not a forecast, VaR, recommendation or order",
  "현재 계산 가능한 직접 보유 자산이 없어 환율 충격을 계산하지 않았습니다.": "No direct holdings with calculable values are available, so the FX shock was not calculated.",
  "선택한 계정에 평가액이 있는 USD 직접 보유 종목이 없습니다. 0원 영향으로 간주하지 않습니다.": "The selected account has no valued direct USD holdings. This is not treated as a zero-won impact.",
  "현재 USD/KRW 근거가 유효하지 않아 계산을 중단했습니다.": "The current USD/KRW evidence is invalid, so the calculation was stopped.",
  "입력과 평가 근거로 유효한 결과를 만들 수 없어 계산을 중단했습니다.": "The inputs and valuation evidence do not yield a valid result, so the calculation was stopped.",
  "계산 가능": "Available",
  "위험 지형": "Risk landscape",
  "각 종목이 따로 움직이는지, 하락할 때 함께 무너지는지, 위험이 몇 종목에 집중되는지를 같은 KRW 투자자 수익률로 봅니다.": "Use the same KRW investor returns to see whether holdings move independently, fall together, or concentrate risk in a few positions.",
  "1년": "1 year",
  "예시": "Sample",
  "관측": "Observed",
  "시계열 종목": "Holdings with history",
  "KRW 환산 수익률": "Returns in KRW",
  "조정종가 우선 · 검증된 KIS 원종가 보완": "Adjusted close preferred · Verified KIS close fills gaps",
  "시계열 없는 특수자산": "Special assets without history",
  "개 제외": " excluded",
  "일부 관측치로 계산": "Calculated from partial observations",
  "평균 상관계수 행렬": "Average correlation matrix",
  "붉을수록 같이 움직이고, 파랄수록 서로 다른 방향으로 움직입니다. 대각선은 자기 자신입니다.": "Red means more similar movements; blue means opposing movements. Each diagonal cell compares a holding with itself.",
  "스트레스 상관계수": "Stress correlation",
  "하락일이": "Down-day observations:",
  "일이라 최소": " days; minimum:",
  "일 기준을 충족하지 못했습니다.": " days has not been met.",
  "유효 종목 수 (ENB)": "Effective number of bets (ENB)",
  "평균 상관": "Average correlation",
  "비중을 반영한 종목 쌍 평균": "Holding-pair average weighted by portfolio weights",
  "스트레스 상관": "Stress correlation",
  "무위험 수익률 0% 가정": "Assumes a 0% risk-free rate",
  "연환산 변동성": "Annualized volatility",
  "일별 변동을 252일로 환산": "Daily volatility annualized over 252 trading days",
  "최대 낙폭 (MDD)": "Maximum drawdown (MDD)",
  "선택 기간 고점 대비 최대 하락": "Largest peak-to-trough decline in the selected period",
  "KODEX 200 베타": "KODEX 200 beta",
  "VOO 베타": "VOO beta",
  "분산": "Diversification",
  "동조": "Co-movement",
  "종목별 위험 기여": "Risk contribution by holding",
  "투자금 비중이 아니라 전체 변동성에 실제로 더한 몫입니다. 값이 큰 종목부터 표시합니다.": "Each holding’s contribution to total volatility, rather than its investment weight. Shown from largest contribution to smallest.",
  "비중": "Weight",
  "지표 읽는 법": "Reading the metrics",
  "설명 보기 ＋": "Show explanation +",
  "접기 －": "Collapse −",
  "위험이 똑같이 나뉘었다고 볼 수 있는 종목 수입니다. 보유 종목은 많아도 ENB가 낮으면 실제 위험은 몇 종목에 몰려 있습니다.": "The number of equally risky positions that would produce the same risk concentration. A low ENB can indicate that only a few positions dominate risk even when many holdings are owned.",
  "1에 가까울수록 같은 방향, 0은 관계가 약함, 음수는 반대 방향입니다. 낮을수록 분산에 유리하지만 항상 수익이 높다는 뜻은 아닙니다.": "Values near 1 indicate similar movements; near 0, a weak linear relationship; negative values, opposing movements. Lower correlation can improve diversification without guaranteeing higher returns.",
  "포트폴리오가 하락한 날만 골라 계산합니다. 평소 상관보다 높다면 위기 때 종목들이 함께 하락하는 구조입니다.": "Calculated using only days when the portfolio declined. A value above normal correlation means holdings tended to fall together during downturns.",
  "감수한 변동성 한 단위당 얻은 수익입니다. 높을수록 효율적이지만, 현재는 비교 가능한 무위험 수익률 원천이 확정되지 않아 0%를 가정합니다.": "Return per unit of volatility taken. Higher values indicate greater historical efficiency. A 0% risk-free rate is assumed because a comparable canonical source has not yet been established.",
  "베타": "Beta",
  "기준지수가 1% 움직일 때 포트폴리오가 평균적으로 얼마나 민감하게 움직였는지 나타냅니다. KODEX 200과 VOO를 따로 표시해 기준 혼동을 막습니다.": "Historical sensitivity to a 1% move in a benchmark. KODEX 200 and VOO are shown separately so the reference benchmark is explicit.",
  "선택한 기간 중 고점에서 저점까지 가장 크게 줄어든 폭입니다. 실제 손실 경험의 크기를 직관적으로 보여주지만 미래 최대 손실을 보장하지는 않습니다.": "The largest peak-to-trough decline in the selected period. This describes historical drawdowns and does not bound future losses.",
  "위험 분석 근거가 아직 충분하지 않습니다.": "There is not enough evidence for risk analysis yet.",
  "일의 수익률을 사용할 수 있습니다. 가격 이력을 지우거나 임의 평균으로 채우지 않으며, 조정종가를 우선하고 검증된 KIS 원종가로 부족한 기간을 보완합니다.": " days of returns are available. History is not erased or filled with arbitrary averages. Adjusted closes are preferred, with verified KIS closes filling gaps.",
  "단일 종목 분석": "Single-holding analysis",
  "가격 이력 부족": "Insufficient price history",
  "중복 근거 검토 필요": "Duplicate evidence needs review",
  "계산 대기": "Awaiting calculation",
  "기준지수 근거 없음": "No benchmark evidence",
  "기준지수 변동 없음": "No benchmark variance",
  "정렬 가능한 가격 이력 부족": "Insufficient aligned price history",
  "보유 종목": "Holdings",
  "유효 분산 수 ENB": "Effective number of bets",
  "근거 부족": "Insufficient evidence",
  "위험 분석": "Risk analysis",
  "상관·분산·베타 분석": "Correlation, diversification & beta",
  "위험 대비 수익 · 무위험 수익률 가정 포함": "Risk-adjusted return · Includes a risk-free-rate assumption",
  "종목들이 함께 움직이는 정도": "How closely holdings move together",
  "하락 구간 상관": "Down-day correlation",
  "하락일에 관측한 동반 움직임": "Co-movement observed on declining days",
  "최대 낙폭": "Maximum drawdown",
  "분석 기간 고점 대비 최대 하락": "Largest decline from a peak in the analysis period",
  "종목별 위험과 데이터 근거": "Risk by holding and data evidence",
  "보유 근거": "Holding evidence",
  "보유 종목과 데이터 근거": "Holdings and data evidence",
  "· 기준일": "· As of",
  "평가 제외": "Excluded valuations",
  "행": " rows",
  "집중·환율": "Concentration & FX",
  "집중도와 환율 노출": "Concentration and currency exposure",
  "내 포트의 구조.": "Inside your portfolio.",
  "자산 배분 구성": "Asset allocation overview",
  "계정": "Account",
  "그룹": "Group",
  "수량": "Quantity",
  "현재가": "Current price",
  "가격 근거": "Price evidence",
  "제외 이유": "Exclusion reason",
  "가격": "Price",
  "현재 평가 제외 근거 없음": "No current valuation exclusions",
  "승인 정책 적용": "Approved policy applied",
  "일부 연결": "Partially matched",
  "검증 필요": "Review required",
  "정책 없음": "No policy",
  "목표비중 매핑 검증 필요": "Target-weight mapping needs verification",
  "현재 범위에 승인된 목표비중 없음": "No approved targets for this scope",
  "실시간 시세": "Live quote",
  "저장 가격": "Stored price",
  "가격 없음": "Missing price",
  "환율 없음": "Missing FX",
  "미지원 통화": "Unsupported currency",
  "특수 보유자산 커버리지·조정 가능성": "Special-holding coverage & adjustability",
  "저장된 상품 유형과 상장 식별 근거만 사용합니다. 이름으로 상품 유형을 추론하지 않으며, 이 표시는 추천·주문 권한이 아닙니다.": "Only recorded asset types and listing identity evidence are used. Product types are not inferred from names. This display does not grant recommendation or order authority.",
  "상태": "Status",
  "조정 가능": "Adjustable",
  "상장 종목": "Listed instruments",
  "별도 거래 단위 필요": "Separate trading units required",
  "실물 원자재": "Physical commodities",
  "명시적 asset_type만 인정": "Only explicit asset_type is accepted",
  "일임 sleeve": "Managed sleeve",
  "현재 선택 범위의 모든 보유자산이 상장 종목 identity와 평가 근거를 갖고 있습니다.": "All holdings in the selected scope have listed-instrument identities and valuation evidence.",
  "보유자산": "Holding",
  "분류": "Classification",
  "평가 상태": "Valuation status",
  "평가 비중": "Value weight",
  "조정 제외 이유": "Adjustment exclusion reason",
  "평가 완료": "Valued",
  "개 · 평가 제외": " · Excluded valuations:",
  "개 · 조정 제외": " · Not adjustable:",
  "검토 필요": "Review needed",
  "데이터 없음": "No data",
  "평가 근거 불완전": "Incomplete valuation evidence",
  "거래 단위·체결 모델 미확정": "Trading-unit and execution model unavailable",
  "내부 구성·직접 조정 권한 없음": "No constituent details or direct adjustment authority",
  "상품 유형·외부 식별 근거 부족": "Insufficient product-type or external identity evidence",
  "분석 범위": "Analysis scope",
  "기간": "Period",
  "일": " days",
  "데이터 상태": "Data health",
  "리스크 계산 대상": "Risk-analysis holdings",
  "가격 행": "Price rows",
  "환율 행": "FX rows",
  "정의되지 않은 상관 쌍": "Undefined correlation pairs",
  "가격 carry": "Price carry",
  "환율 carry": "FX carry",
  "유효하지 않은 행": "Invalid rows",
  "수익률 관측치": "Return observations",
  "차단 및 제외": "Blocked & excluded",
  "Source 집계": "Source counts",
  "변동성 0 종목:": "Zero-variance holdings:",
  "차단 항목이 없습니다.": "No blocked items.",
  "제외된 보유 종목이 없습니다.": "No holdings were excluded.",
  "계좌": "Account",
  "사유": "Reason",
  "ticker 없음": "Missing ticker",
  "보유 수량 0 이하": "Holding quantity is zero or negative",
  "지원하지 않는 통화": "Unsupported currency",
  "입력 차단": "Input blocked",
  "계산 준비 완료": "Ready to calculate",
  "부분 관측치": "Partial observations",
  "관측치 부족": "Insufficient observations",
  "종목 수 부족": "Too few holdings",
  "전체 계산 완료": "Calculation complete",
  "단일 종목만 계산": "Single holding only",
  "입력 오류": "Invalid input",
  "중복 데이터로 입력이 차단됐습니다.": "Duplicate data blocked the calculation input.",
  "요청한 기간의 관측치가 부족합니다.": "Observations are insufficient for the requested period.",
  "계산 가능한 종목이 없습니다.": "No holdings are eligible for calculation.",
  "정규화된 계산 입력이 유효하지 않습니다.": "The normalized calculation inputs are invalid.",
  "수익률 계산에 필요한 관측치가 부족합니다.": "There are not enough observations to calculate returns.",
  "공분산 행렬을 안전하게 계산할 수 없습니다.": "The covariance matrix cannot be calculated reliably.",
  "변동성 0": "Zero variance",
  "포트폴리오 변동성 0": "Zero portfolio volatility",
  "정의되지 않은 종목 쌍 포함": "Includes undefined holding pairs",
  "양수 비중 종목 쌍 없음": "No positively weighted holding pairs",
  "하락일 관측치 부족": "Insufficient down-day observations",
  "시장 / 통화": "Market / currency",
  "계산 비중": "Calculation weight",
  "관측치": "Observations",
  "상관관계 행렬": "Correlation matrix",
  "같은 기간에 관측한 종목별 수익률": "Holding returns observed over the same period",
  "하락일에도 함께 움직였을까?": "Did they move together on down days?",
  "개 하락일": " down days",
  "하락일": "Down days",
  "개로 최소": "; minimum:",
  "개 기준을 충족하지 못했습니다.": " observations has not been met.",
  "행렬을 계산할 수 없습니다.": "The matrix cannot be calculated.",
  "분석 기준": "Analysis basis",
  "분석 범위 / 기간": "Analysis scope / period",
  "계산 상태": "Calculation status",
  "분석 service date": "Analysis service dates",
  "관측치 커버리지": "Observation coverage",
  "수익률 기준": "Return basis",
  "무위험 수익률 (가정)": "Risk-free rate (assumed)",
  "연환산 기준": "Annualization basis",
  "조회 source date": "Source-date range",
  "포트폴리오 위험 요약": "Portfolio risk summary",
  "보유 비중이 있는 종목 쌍": "Pairs of holdings with portfolio weights",
  "절대 위험 기여도 기준": "Based on absolute risk contributions",
  "분산 효과": "Diversification benefit",
  "개별 변동성의 가중합 대비": "Relative to weighted individual volatilities",
  "하락 구간 평균 상관": "Average down-day correlation",
  "단일 종목 위험": "Single-holding risk",
  "correlation, RC, ENB 제외": "Excludes correlation, RC and ENB",
  "검증된 분석용 가격 이력이 없습니다. 현재가와 운영 종가는 계속 사용할 수 있지만, 수익률·상관관계·Sharpe 계산에는 사용하지 않습니다. 분석은 조정종가를 우선하고 검증된 KIS 원종가로 부족한 기간을 보완합니다.": "No verified analytical price history is available. Current quotes and operational closes remain usable, but are not used for returns, correlation or Sharpe. Analysis prefers adjusted closes and supplements gaps with verified KIS closes.",
  "일부 관측치만으로 계산했습니다. 실제 사용 관측치는": "Calculated from partial observations. Observations used:",
  "입니다.": ".",
  "계산 가능한 종목이 1개이므로 변동성과 Sharpe만 표시합니다. 상관, 위험 기여와 ENB는 계산하지 않습니다.": "Only one holding is eligible, so only volatility and Sharpe are shown. Correlation, risk contribution and ENB are not calculated.",
  "위험과 분산.": "Risk, diversified.",
  "실제 보유자산과 연결되지 않은 90일 분석 미리보기입니다.": "90-day sample analysis, unconnected to actual holdings.",
  "포트 구조": "Portfolio structure",
  "분석 종목": "Holdings analyzed",
  "보유 종목 상관관계": "Holding correlations",
  "· KRW 환산": "· In KRW",
  "일 기준": " days of observations",
  "한 종목의 위험을 확인합니다.": "Reviewing a single holding’s risk.",
  "상관관계를 계산할 근거가 부족합니다.": "There is not enough evidence to calculate correlations.",
  "일 · 분석 가능한 종목": " days · Eligible holdings:",
  "KRW 환산 ·": "In KRW ·",
  "전체 상관계수": "All correlations",
  "전체 종목과 하락일 상관관계": "All holdings and down-day correlations",
  "위험 수치·기여": "Risk metrics & contribution",
  "위험 요약과 종목별 기여": "Risk summary and holding contributions",
  "계산·데이터 근거": "Calculation & evidence",
  "분석 기준과 데이터 근거": "Analysis basis and data evidence",
  "선택한 종목 쌍": "Selected holding pair",
  "같은 종목": "Same holding",
  "같은 방향의 움직임": "Moving in the same direction",
  "반대 방향의 움직임": "Moving in opposite directions",
  "선형 상관 없음": "No linear correlation",
  "계산 근거 없음": "No calculation evidence",
  "종목 근거 없음": "No holding evidence",
  "좌우로 스크롤할 수 있는 상관관계 행렬": "Horizontally scrollable correlation matrix",
  "반대 방향": "Opposite direction",
  "같은 방향": "Same direction",
  "셀을 선택해 종목 쌍을 확인하세요": "Select a cell to inspect a holding pair",
  "관리 | VARDA LABS": "Manage | VARDA LABS",
  "자산과 계좌": "Assets & accounts",
  "증권·연금 계좌를 추가하고 관리합니다.": "Add and manage brokerage and retirement accounts.",
  "보유 수량, 매입원가와 자산 정보를 확인합니다.": "Review holding quantities, cost basis and asset details.",
  "여러 계좌와 종목을 목적에 맞게 묶습니다.": "Group accounts and holdings to suit your analysis.",
  "목표와 기준": "Targets & rules",
  "추가 투입과 포트폴리오 관리의 기준을 정합니다.": "Set the baseline for contributions and portfolio management.",
  "보유 종목 추가": "Add holding",
  "주식, ETF, 금현물과 금융자산을 등록합니다.": "Register stocks, ETFs, physical gold and financial assets.",
  "ETF 정보": "ETF information",
  "ETF의 분류와 참고 정보를 확인합니다.": "Review ETF classifications and reference information.",
  "기록": "Records",
  "거래와 이벤트": "Trades & events",
  "매매·입출금 등 자산의 변화를 확인합니다.": "Review asset changes from trades, deposits and withdrawals.",
  "포트폴리오 스냅샷": "Portfolio snapshots",
  "날짜별로 저장된 평가액과 수익률입니다.": "Portfolio values and returns saved by date.",
  "종목별 스냅샷": "Position snapshots",
  "보유 종목의 날짜별 평가 근거입니다.": "Date-specific valuation evidence for each holding.",
  "시장 데이터": "Market data",
  "시장 데이터 동기화": "Sync market data",
  "가격·환율 데이터의 갱신 상태를 확인합니다.": "Check the update status of price and FX data.",
  "시장 현황": "Market overview",
  "연결된 시장 지표와 기준일을 확인합니다.": "Review connected market indicators and their reference dates.",
  "나의 자산,": "Your assets,",
  "나의 기준.": "your rules.",
  "포트폴리오를 이루는 데이터와": "Manage your portfolio data",
  "분석의 기준을 관리하세요.": "and the basis of your analysis.",
  "관리할 데이터 선택": "Choose data to manage",
  "정리된 데이터에서 시작하는 분석": "Analysis starts with organized data",
  "처음 시작하기": "Getting started",
  "포트폴리오를 만드는 순서": "Build your portfolio step by step",
  "01 · 계좌 등록": "01 · Add accounts",
  "증권·연금 계좌를 만들고 분석할 자산을 정리하세요.": "Create brokerage and retirement accounts and organize the assets you want to analyze.",
  "계좌 관리": "Manage accounts",
  "02 · 보유 종목 등록": "02 · Add holdings",
  "수량과 매입원가를 입력하면 자산 평가와 손익의 근거가 됩니다.": "Enter quantities and cost basis to establish valuation and profit-and-loss evidence.",
  "종목 추가": "Add holding",
  "03 · 목표비중 설정": "03 · Set target weights",
  "금현물을 포함해 관리하려는 종목의 목표비중을 정하세요.": "Set target weights for the holdings you manage, including physical gold.",
  "목표비중 관리": "Manage target weights"
};

type CopyRule = readonly [RegExp, (...parts: string[]) => string];
// Anchored templates translate only application-owned sentences, preserving data parameters.
const COPY_RULES: readonly CopyRule[] = [
  [/^전체 (\d+)종목 배분$/, n => `All ${n} allocations`],
  [/^현재 평가액 (.+) · (.+) · 가격 기준일 (.+)$/, (amount, policy, date) => `Current value ${amount} · ${policy} · Prices as of ${date}`],
  [/^(\d+)\/(\d+)종목 근거 확보( · 일부 근거 부족)?$/, (usable, total, partial) => `${usable}/${total} holdings with evidence${partial ? " · Some evidence missing" : ""}`],
  [/^데이터 검증 실패: (.+)$/, code => `Data validation failed: ${code}`],
  [/^목표 대비 \+(.+)% 이상$/, n => `At least ${n}% above target`],
  [/^투입 전 비중으로 초과 폭을 판단합니다\. 원가 근거가 있고 평가손익이 0 이상인 종목만, 투입 후 총액 기준 목표비중의 (.+)% 지점까지 계산상 매도합니다\.$/, n => `Overweight status uses pre-contribution weights. Only holdings with verified cost basis and a nonnegative unrealized return are trimmed, to ${n}% of target using the total value after contribution.`],
  [/^매수 가능 재원의 (.+)%를 참고기준으로 확인합니다\. 유효 목표 부족액이 작으면 미달할 수 있으며, 기준을 맞추기 위한 추가 매수는 하지 않습니다\.$/, n => `${n}% of available funds is shown as an execution reference. Allocation may fall below this level when effective shortfalls are small; no extra purchases are made to reach it.`],
  [/^드리프트 (.+)$/, n => `Drift ${n}`],
  [/^매도 (.+)$/, n => `Sell ${n}`],
  [/^매수 (.+)$/, n => `Buy ${n}`],
  [/^MA120 배율 (.+)을 반영했습니다\.$/, n => `The MA120 multiplier of ${n} was applied.`],
  [/^배분 재원의 (.+)$/, n => `${n} of available funds`],
  [/^(\d+)종목$/, n => `${n} holdings`],
  [/^전체 목표 종목 (\d+)개$/, n => `${n} target holdings in total`],
  [/^(.+)p 가까워짐$/, n => `${n}p closer`],
  [/^(.+)p 멀어짐$/, n => `${n}p further away`],
  [/^(.+) 현재 (.+), 목표 (.+), 투입 후 (.+)$/, (name, current, target, after) => `${name}: current ${current}, target ${target}, after contribution ${after}`],
  [/^현재 (.+)$/, n => `Current ${n}`],
  [/^목표 (.+)$/, n => `Target ${n}`],
  [/^투입 후 (.+)$/, n => `After contribution ${n}`],
  [/^MA120 일부 근거 확보 · 감액 종목 감소 합계 (.+)$/, n => `Partial MA120 evidence · Sum of holding-level reductions ${n}`],
  [/^MA120 (\d+)종목 근거 확보 · 감액 종목 감소 합계 (.+)$/, (count, n) => `MA120 evidence for ${count} holdings · Sum of holding-level reductions ${n}`],
  [/^그 외 (\d+)종목$/, n => `${n} other holdings`],
  [/^(.+), (.+), 재원의 (.+)%$/, (name, amount, weight) => `${name}, ${amount}, ${weight}% of available funds`],
  [/^(.+) 재원 배분 흐름$/, n => `Allocation flow for ${n}`],
  [/^([\d,.]+)억$/, n => `₩${(Number(n.replaceAll(",", "")) * 100).toLocaleString("en-US")}m`],
  [/^([\d,.]+)만$/, n => `₩${(Number(n.replaceAll(",", "")) * 10).toLocaleString("en-US")}k`],
  [/^식별 가능한 직접 보유 (\d+)개$/, n => `${n} identifiable direct holdings`],
  [/^(.+), 현재 비중 (.+)$/, (name, n) => `${name}, current weight ${n}`],
  [/^(\d+)개 직접 보유 종목$/, n => `${n} direct holdings`],
  [/^평가 대상 (\d+)개$/, n => `${n} valued holdings`],
  [/^(.+)% 이상 (.+)% 이하의 변동률을 입력하세요\.$/, (min, max) => `Enter a change between ${min}% and ${max}%.`],
  [/^포트폴리오가 하락한 (\d+)일만 다시 계산했습니다\. 평소보다 붉어지면 위기 때 분산 효과가 약해진다는 뜻입니다\.$/, n => `Recalculated using only ${n} portfolio down days. Redder cells indicate weaker diversification during downturns.`],
  [/^(\d+)개 중 위험 분산 효과$/, n => `Risk diversification across ${n} holdings`],
  [/^하락일 (\d+)일$/, n => `${n} down days`],
  [/^(\d+)일 정렬 관측$/, n => `${n} aligned daily observations`],
  [/^(\d+)개$/, n => `${n} holdings`],
  [/^가격 없음 (\d+)$/, n => `Missing prices ${n}`],
  [/^환율 없음 (\d+)$/, n => `Missing FX ${n}`],
  [/^미지원 통화 (\d+)$/, n => `Unsupported currency ${n}`],
  [/^(.+) · (\d+)\/(\d+) 종목 연결$/, (date, matched, total) => `${date} · ${matched}/${total} holdings matched`],
  [/^(\d+)\/(\d+) 종목만 연결$/, (matched, total) => `Only ${matched}/${total} holdings matched`],
  [/^평가액 비중 (.+)$/, n => `Portfolio value weight ${n}`],
  [/^조정 제외 비중 (.+)$/, n => `Non-adjustable weight ${n}`],
  [/^(\d+)개 제외 · 아래 목록 참조$/, n => `${n} excluded · See the list below`],
  [/^환율 기준일 중복: (.+)$/, dates => `Duplicate FX dates: ${dates}`],
  [/^(.+) 가격 기준일 중복: (.+)$/, (key, dates) => `${key}: duplicate price dates ${dates}`],
  [/^(\d+)개 하락일$/, n => `${n} down days`],
  [/^(.+) \/ (\d+)일$/, (scope, days) => `${scope} / ${days} days`],
  [/^([\d/]+) 관측치$/, n => `${n} observations`],
  [/^비중 기준일 (.+)$/, date => `Weights as of ${date}`],
  [/^canonical source 미확정 · daily (.+)$/, rate => `Canonical source unconfirmed · Daily ${rate}`],
  [/^([\d/]+)일$/, n => `${n} days`],
  [/^(\d+) 수익률 관측치$/, n => `${n} return observations`],
  [/^(\d+) 하락일$/, n => `${n} down days`],
  [/^([\d/]+) 관측치이며 더 짧은 기간으로 자동 대체하지 않습니다\.$/, n => `${n} observations. The requested period is not automatically replaced with a shorter one.`],
  [/^비중 상위 (\d+) \/ 전체 (\d+)종목$/, (top, total) => `Top ${top} by weight / ${total} holdings`],
  [/^전체 (\d+)종목$/, n => `All ${n} holdings`],
  [/^(.+): 계산 근거 없음$/, key => `${key}: no calculation evidence`],
];

export function portfolioEnglish(text: string): string {
  const normalized = text.replace(/\s+/g, " ").trim();
  if (!/[가-힣]/.test(normalized)) return text;
  const exact = Object.hasOwn(PORTFOLIO_COPY, normalized) ? PORTFOLIO_COPY[normalized] : undefined;
  if (exact !== undefined) return exact;
  for (const [pattern, render] of COPY_RULES) {
    const match = normalized.match(pattern);
    if (match) return render(...match.slice(1));
  }
  // Rationale helpers join independently defined sentences or metric labels.
  const pieces = normalized.split(/(?<=\.)\s+| · /);
  if (pieces.length > 1) {
    let translated = normalized;
    for (const piece of pieces) {
      const english = (Object.hasOwn(PORTFOLIO_COPY, piece) ? PORTFOLIO_COPY[piece] : undefined) ?? COPY_RULES.reduce<string | undefined>((result, [pattern, render]) => {
        if (result !== undefined) return result;
        const match = piece.match(pattern);
        return match ? render(...match.slice(1)) : undefined;
      }, undefined);
      if (english !== undefined) translated = translated.replace(piece, english);
    }
    return translated;
  }
  return text;
}
