// UI translations for messages emitted by the unchanged research data model.
export const labCopyExtra: Readonly<Record<string, string>> = {
  "이 범위에 승인된 목표 비중이 없습니다.": "No approved target allocation exists for this scope.",
  "목표비중 화면에서 현재 보유 종목 전체의 비중을 저장하고 승인하면 다음 조회부터 계산됩니다.": "Save and approve weights for all current holdings on the Target weights screen. Calculations will be available on the next data request.",
  "동시에 유효한 승인 목표 비중이 둘 이상입니다.": "More than one approved target allocation is effective at the same time.",
  "중복 revision을 철회하거나 supersede하여 현재 승인본을 하나로 확정해야 합니다.": "Withdraw or supersede duplicate revisions so that one approved version remains effective.",
  "분석 시작일에 목표 비중 정책이 아직 효력을 갖지 않았습니다.": "The target allocation policy was not yet effective at the start of the analysis.",
  "정책 효력일 이후 구간을 선택하거나, 더 이른 효력일의 정책을 별도로 검토·승인해야 합니다.": "Select a period after the policy's effective date, or separately review and approve a policy with an earlier effective date.",
  "현재 보유 종목 집합과 승인 목표 비중 벡터가 일치하지 않습니다.": "Current holdings do not match the approved target-weight vector.",
  "추가·삭제된 종목과 명시적 0% 행까지 반영해 목표 벡터를 새 revision으로 다시 승인해야 합니다.": "Approve a new target-weight revision that includes added or removed holdings and explicit 0% rows.",
  "전체 범위에 포함된 일부 계정의 승인 목표 비중이 없습니다.": "Some accounts in the combined scope have no approved target allocation.",
  "누락된 각 계정의 목표 비중을 승인하거나, 계산할 계정 범위를 좁혀야 합니다.": "Approve target weights for each missing account, or narrow the account scope for the calculation.",
  "시나리오들의 시작일·종료일·평가일 축이 서로 다릅니다.": "Scenario start dates, end dates or valuation dates do not match.",
  "누락 가격·환율을 보완한 뒤 동일한 공통 비교 구간으로 경로를 다시 계산해야 합니다.": "Complete missing price and FX data, then recalculate the paths over the same shared period.",
  "티커가 없는 수동 평가 자산의 기간별 가격 근거가 부족합니다.": "Historical prices are insufficient for manually valued assets without tickers.",
  "날짜별 수동 평가 이력을 입력하거나 검증된 별도 가격 공급자를 연결해야 합니다. 저장가 이월을 시장 수익률로 간주하지는 않습니다.": "Enter dated manual valuations or connect a verified price provider. Carrying a recorded value forward is not treated as a market return.",
  "필요한 종가가 누락됐거나 같은 종목·날짜의 근거가 충돌합니다.": "Required closing prices are missing, or records conflict for the same instrument and date.",
  "표시된 종목과 기간만 provider로 보완하고, 중복 행은 출처 우선순위에 따라 하나로 확정해야 합니다.": "Retrieve provider data for the listed instruments and dates, and resolve duplicate rows using source precedence.",
  "USD 자산 평가에 필요한 날짜별 USD/KRW 근거가 없거나 충돌합니다.": "Daily USD/KRW rates required to value USD assets are missing or conflicting.",
  "해당 날짜의 환율만 보완하고, 같은 날짜의 비표본 기준 환율을 하나로 확정해야 합니다.": "Complete FX data for the affected dates and establish one non-sampled reference rate for each date.",
  "실제 포트폴리오의 공통 비교 경로가 완성되지 않았습니다.": "The actual portfolio's shared comparison path is incomplete.",
  "누락·중복 스냅샷과 거래 흐름을 먼저 감사한 뒤 실제 경로를 복구해야 합니다. 다른 시나리오 값으로 대신 채우지는 않습니다.": "Audit missing or duplicate snapshots and trade flows before restoring the actual path. Values from other scenarios are not used as substitutes.",
  "분석 시작 전 공동 일간수익률이 60개 미만입니다.": "Fewer than 60 shared daily returns are available before the analysis starts.",
  "더 이른 종가·환율을 보완하거나 사용자가 명시적으로 더 짧은 학습 구간을 선택해야 합니다.": "Retrieve earlier closing prices and FX rates, or explicitly select a shorter training period.",
  "현금흐름 조정 수익률과 위험 지표를 만들 공통 평가 구간이 없습니다.": "There is no shared valuation period for cash-flow-adjusted returns and risk metrics.",
  "실제 경로와 시나리오 경로의 공통 평가일을 2일 이상 확보하고, 해당 구간의 거래 흐름·종가·환율 누락을 보완해야 합니다.": "Provide at least two shared valuation dates for actual and scenario paths, and complete trade flows, closing prices and FX rates for that period.",
  "최대 낙폭은 계산할 수 있지만 연환산 변동성에 필요한 연속 일간수익률이 20개 미만입니다.": "Maximum drawdown can be calculated, but fewer than 20 consecutive daily returns are available for annualized volatility.",
  "조회 구간을 늘리거나 누락된 종가·환율을 보완해 20개 이상의 연속 일간수익률을 확보해야 합니다.": "Extend the period or complete missing closing prices and FX rates to obtain at least 20 consecutive daily returns.",
  "수익률 관측일 사이가 하루보다 길어 일간 변동성으로 연환산할 수 없습니다.": "Gaps between return observations exceed one day, so daily volatility cannot be annualized.",
  "빠진 날짜의 종가·환율을 보완해 연속 일간 축을 만들고 다시 계산해야 합니다.": "Complete closing prices and FX rates for missing dates to create a consecutive daily series, then recalculate.",
  "비교 시작일의 보유 구성 또는 배분 기준을 확정할 수 없습니다.": "Holdings or allocation rules cannot be established for the comparison start date.",
  "시작일 포지션 스냅샷과 종목 식별을 보완한 뒤 기준 바스켓을 다시 선택해야 합니다.": "Complete the starting position snapshot and instrument identities, then select the baseline basket again.",
  "포함 계정 또는 종목 구성의 합계가 전체 경로와 일치하지 않습니다.": "Included account or instrument totals do not reconcile with the combined path.",
  "계정 소유권·그룹 멤버십·종목 축을 같은 기준일로 다시 감사해야 합니다.": "Audit account ownership, group membership and instrument identities using the same reference date.",
  "매수·매도·입출금 흐름의 계정 또는 금액 근거가 완전하지 않습니다.": "Account or amount data is incomplete for trades, deposits or withdrawals.",
  "이벤트의 계정·종목 연결과 원화 금액을 보완한 뒤 동일 흐름 일정을 다시 생성해야 합니다.": "Complete event links to accounts and holdings, and their KRW amounts, then rebuild the shared cash-flow schedule.",
  "필요한 계산 근거 중 하나 이상이 아직 완전하지 않습니다.": "One or more required calculation inputs are incomplete.",
  "상세 근거 코드와 데이터 준비 상태에서 막힌 가격·환율·스냅샷·정책 항목을 먼저 보완해야 합니다.": "Review the detailed reason codes and data readiness, then complete the missing price, FX, snapshot or policy data.",
  "코로나 급락": "COVID-19 selloff",
  "글로벌 주식시장의 코로나19 급락 구간": "The COVID-19 selloff in global equity markets",
  "2022 금리 충격": "2022 rate shock",
  "빠른 금리 인상과 성장주 조정이 겹친 구간": "A period of rapid rate increases and a growth-stock correction",
  "2023 AI 상승": "2023 AI rally",
  "미국 대형 기술주 중심의 AI 랠리 구간": "The AI rally led by US large-cap technology stocks",
  "전액 KODEX 200": "All KODEX 200",
  "전액 VOO": "All VOO",
  "현재 구성": "Current allocation",
  "동일 비중": "Equal weight",
  "현금": "Cash",
};
