export const labCopyB: Readonly<Record<string, string>> = {
  "가격 충격은 -100%부터 +100% 사이의 숫자로 입력해야 합니다.": "Enter a price shock between −100% and +100%.",
  "직접 보유와 ETF 경유 노출 합계가 유효 범위를 벗어났습니다.": "Combined direct and ETF exposure is outside the valid range.",
  "구성종목 또는 평가 근거를 확인해야 합니다.": "Constituent or valuation data needs checking.",
  "전체 포트폴리오": "Entire portfolio",
  "평가 가능한 하위집합": "Valued subset",
  "포트폴리오 ETF X-ray": "Portfolio ETF X-ray",
  "보유 ETF를 구성종목까지 펼쳐 직접 보유와 ETF 간 중복을 확인합니다. ETF별 최신 기준일을 각각 유지하며, 관측된 노출을 100%로 재정규화하지 않습니다.": "Look through your ETFs to identify overlapping constituents and direct holdings. Each ETF retains its own latest reference date; observed exposures are not rescaled to 100%.",
  "기초 포트폴리오": "Underlying portfolio",
  "평가 완전": "Complete valuation",
  "평가 부분": "Partial valuation",
  "평가된 보유 ETF": "Valued ETF holdings",
  "구성종목 근거": "Constituent data",
  "관측된 ETF 경유 노출": "Observed ETF exposure",
  "미커버 ETF 노출": "Uncovered ETF exposure",
  "가격·환율 근거가 없어 평가에서 제외된 자산이": "Assets excluded for missing price or FX data:",
  "개이며, 그중 ETF 후보는": "; potential ETFs among them:",
  "개입니다. 따라서 아래 비중은 전체 포트폴리오가 아니라 평가 가능한 하위집합 기준입니다. 제외 사유: 가격": ". The weights below therefore refer to the valued subset, rather than the entire portfolio. Exclusions: price",
  "· 환율": "· FX rate",
  "· 미지원 통화": "· Unsupported currency",
  "ETF별 구성종목 기준일이": "Distinct constituent reference dates across ETFs:",
  "개로 섞여 있습니다. 아래 수치는 각 ETF의 최신 저장 근거를 합친 참고값이며, 하나의 공통 시점 포트폴리오로 해석하지 않습니다.": ". Figures combine each ETF's latest recorded data for reference. They do not represent a portfolio at one common point in time.",
  "보유 ETF 커버리지": "ETF holding coverage",
  "reference 매핑, ETF별 기준일, 구성종목 비중 누락을 함께 표시합니다.": "Reference mappings, ETF dates and missing constituent weights are shown together.",
  "계정": "Account",
  "구성 기준일": "Constituent date",
  "평가 하위집합 비중": "Weight in valued subset",
  "관측 비중": "Observed weight",
  "미커버": "Uncovered",
  "상위 구성종목 노출": "Largest constituent exposures",
  "유효한 market · currency · ticker와 비중이 모두 있는 구성종목만 합산합니다.": "Only constituents with valid market, currency, ticker and weight data are combined.",
  "표시할 수 있는 구성종목 근거가 없습니다.": "No constituent data is available to display.",
  "숨은 중복 노출": "Overlapping exposures",
  "두 개 이상의 보유 ETF가 공유하거나, 같은 종목을 포트폴리오에서 직접 보유한 경우입니다.": "Constituents shared by at least two held ETFs, or also held directly in the portfolio.",
  "현재 exact identity 기준의 중복 노출이 없습니다.": "No overlapping exposures have an exact identity match.",
  "ETF reference 근거를 읽지 못해 이 섹션만 표시할 수 없습니다.": "This section is unavailable because ETF reference data could not be read.",
  "이름 없음": "No name",
  "티커 없음": "No ticker",
  "직접 보유": "Direct holdings",
  "경유 ETF": "Source ETFs",
  "근거 기준일": "Reference dates",
  "개 중복": " overlaps",
  "reference 없음": "No reference",
  "reference 중복": "Duplicate references",
  "구성종목 없음": "No constituents",
  "비중 합계 오류": "Invalid weight total",
  "부분 관측": "Partially observed",
  "완전 관측": "Fully observed",
  "공통 기준일 · 완전 관측": "Common date · Fully observed",
  "기준일 혼합 · 완전 관측": "Mixed dates · Fully observed",
  "사용 가능한 근거 없음": "No usable data",
  "실제 포트폴리오와 세 가지 고정비중 경로 비교": "Actual portfolio versus three fixed-allocation paths",
  "같은 관측 날짜와 외부 현금흐름을 사용한 KODEX 200 및 VOO 고정비중 연구 경로입니다.": "KODEX 200 and VOO research paths use the same observation dates and external cash flows with fixed allocation ratios.",
  "배분 입력을 확인해야 합니다.": "Allocation inputs need checking.",
  "두 종목의 완전한 경로가 모두 필요합니다.": "Complete paths are required for both instruments.",
  "두 종목의 비교 날짜축이 일치하지 않습니다.": "The comparison dates do not match between the two instruments.",
  "구성 종목 평가액 근거를 확인해야 합니다.": "Constituent valuations need checking.",
  "두 종목의 현금흐름 원본이 일치하지 않습니다.": "The original cash flows do not match between the two instruments.",
  "수익률 근거가 완전하지 않습니다.": "Return data is incomplete.",
  "실제 수익률 기준이 서로 일치하지 않습니다.": "The actual-return baselines do not match.",
  "시나리오 수익률을 계산할 수 없습니다.": "The scenario return cannot be calculated.",
  "계좌별 시나리오 근거가 모두 필요합니다.": "Scenario data is required for every account.",
  "계좌별 합계와 전체 결과가 일치하지 않습니다.": "Account totals do not reconcile with the combined result.",
  "세 가지 표준 고정비중 경로를 준비할 수 없습니다.": "The three standard fixed-allocation paths are unavailable.",
  "표준 비중 3안 비교": "Three allocation examples",
  "세 안은 같은 실제 평가액 날짜, 가격·환율 근거와 매수·매도 금액을 사용합니다. KODEX 비중 순서로만 배치하며 성과 순위나 추천을 만들지 않습니다.": "All three use the same actual valuation dates, price and FX data, and trade amounts. They are ordered by KODEX weight, with no performance ranking or recommendation.",
  "현재 입력": "Current input",
  "현금흐름 조정 추정수익률": "Estimated cash-flow-adjusted return",
  "준비된 시나리오만 표시했습니다. 누락된 안은 해당 카드의 차단 사유를 확인하세요.": "Only available scenarios are shown. Review each unavailable scenario's reason in its card.",
  "KODEX 200·VOO 고정 배분 실험": "KODEX 200 / VOO allocation experiment",
  "초기 평가액과 실제 매수·매도 금액을 선택 비율로 나눠 두 종목에 적용합니다. 이후 가격 변동에 따른 비중 변화는 그대로 두며 중간 재리밸런싱은 하지 않습니다.": "The initial value and actual trade amounts are split between the two instruments using the selected ratio. Weights then drift with prices; there is no rebalancing during the period.",
  "먼저 사용할 수 있는 과거 비교 구간을 선택해야 합니다.": "First select an available historical comparison period.",
  "KODEX 200 배분은 1~99 사이의 정수 퍼센트로 입력해야 합니다.": "Enter a whole-number KODEX 200 allocation between 1% and 99%.",
  "기존 KODEX 200·VOO 경로 증거를 준비할 수 없습니다.": "The existing KODEX 200 and VOO path data is unavailable.",
  "직접 입력한 비중 상세": "Custom allocation details",
  "두 leg 중 하나라도 가격·환율·체결·매도 가능성 검증에 실패하면 부분 결과를 표시하지 않습니다. 소수점 수량을 사용해 자동 잔여 현금을 만들지 않으며, 이 결과는 목표비중·추천·주문 근거가 아닌 과거 연구 비교입니다.": "No partial result is shown if either leg fails price, FX, execution or sellability checks. Fractional quantities avoid automatic residual cash. This is a historical research comparison, not a target allocation, recommendation or order basis.",
  "KODEX 200과 VOO는 화면에 표시된 저장 가격 근거를 사용하며, KIS 원종가 구간은 배당·기업행사를 조정하지 않습니다. 서로 다른 가격 기준을 결합한 현금흐름 조정 추정치이므로 정확한 일별 TWR 또는 총수익률을 의미하지 않습니다.": "KODEX 200 and VOO use the recorded price sources shown here. KIS raw-close segments are not adjusted for dividends or corporate actions. The cash-flow-adjusted estimate combines different price bases and is not an exact daily TWR or total return.",
  "KODEX 200 배분": "KODEX 200 allocation",
  "고정 배분 예시": "Fixed allocation example",
  "시나리오 종료 평가액": "Scenario ending value",
  "실제 대비 수익률 차이": "Return difference versus actual",
  "실제 포트폴리오와 고정 배분 시나리오 비교": "Actual portfolio versus fixed allocation scenario",
  "개 · 원본 현금흐름": " · Original cash flows:",
  "건 · 분할 체결": " · Split executions:",
  "건 · 두 시장 체결일이 달랐던 현금흐름": " · Cash flows executed on different dates across the two markets:",
  "현금": "Cash",
  "고정 혼합": "Fixed mix",
  "기간 전 최소변동성": "Pre-period minimum volatility",
  "기준 바스켓": "Baseline basket",
  "기준일 비중": "Baseline-date weights",
  "현재 비중 월간 유지": "Monthly reset to current weights",
  "계정별 자금 경계": "Account funding boundaries",
  "각 계정의 시작 평가액과 매수·매도 흐름만 사용한 연구 경로인지 확인합니다.": "Check that each research path uses only its account's starting value and trade flows.",
  "전체 합산": "Combined total",
  "전체는 통과한 증권·ISA·IRP 결과의 합이며 계정 간 자금을 합쳐 계산하지 않습니다. 상품 매수 가능 여부, 비용, 세금, 환전 스프레드와 주문 체결은 아직 검증하지 않은 연구 결과입니다. 따라서 ISA·IRP의 VOO 경로도 실제 매수 가능성을 뜻하지 않습니다.": "The combined total sums the valid brokerage, ISA and IRP results; funds are not pooled across accounts. Product eligibility, costs, taxes, FX spreads and order execution have not been verified. VOO paths for ISA or IRP therefore do not establish that VOO can actually be bought in those accounts.",
  "통과": "Passed",
  "제외": "Excluded",
  "미선택": "Not selected",
  "전체 통과": "All passed",
  "일부 경로 제외": "Some paths excluded",
  "기준 경로 사용 불가": "Baseline path unavailable",
  "선택 구간 관측 경로": "Observed path for the selected period",
  "부분 표시": "Partial display",
  "저장 방식이 바뀐 지점은 연결하지 않았습니다. 아래 선은 실제로 저장된 평가액만 표시하며, 비어 있는 날짜의 평균값 생성이나 외부 API 보충은 하지 않습니다.": "Paths are disconnected where the recording method changed. Lines show only actual recorded values, with no averages or external API data used to fill missing dates.",
  "최신 계산 가능 구간 열기": "Open the latest calculable period",
  "일": " days",
  "구간 사이에는 수익률·시나리오 계산을 적용하지 않습니다.": "Returns and scenarios are not calculated across separate segments.",
  "이전 서비스 관측": "Legacy service observations",
  "현재 저장기 관측": "Current recorder observations",
  "점 하나가 실제 저장 관측일입니다.": "Each point represents an actual recorded observation date.",
  "저장 출처별 실제 평가액 관측 경로": "Recorded portfolio value paths by source",
  "레거시 관측과 현재 저장기 관측을 서로 연결하지 않고 표시한 그래프": "Chart with legacy and current recorder observations shown as separate paths",
  "개 관측": " observations",
  "가정": "Assumptions",
  "기간과 계산 가정": "Period and calculation assumptions",
  "근거": "Sources",
  "현금흐름과 수익률 상세": "Cash flow and return details",
  "관측 경로 근거가 부족합니다.": "Observed path data is insufficient.",
  "비교 데이터": "Comparison data",
  "평가액과 해당 시점에 사용된 KODEX 200 가격 기준일을 함께 확인합니다.": "Review portfolio values alongside the KODEX 200 price date used for each observation.",
  "기간 내 반영 거래": "Trades reflected in the period",
  "건 · 지연 체결": " · Delayed executions:",
  "평가일": "Valuation date",
  "실제 평가액": "Actual value",
  "차이": "Difference",
  "가격 기준": "Price basis",
  "· 지연 체결": "· Delayed execution",
  "데이터 상태": "Data status",
  "완전한 비교일": "Complete comparison dates",
  "평가 스냅샷": "Valuation snapshots",
  "종료 시 대기 거래": "Trades pending at period end",
  "KIS 원종가(배당·기업행사 미조정)": "KIS raw close (unadjusted for dividends and corporate actions)",
  "가격 근거": "Price data",
  "관측 경로 근거가 부족해 기간과 계산 가정을 표시할 수 없습니다. 기간과 데이터 상태를 확인해 주세요.": "The period and assumptions are unavailable because observed path data is insufficient. Check the period and data status.",
  "최신 writer 관측 구간 연구 비교": "Research comparison for the latest recorder period",
  "개 평가일만 사용합니다. 레거시 구간과 이어 붙이지 않았고, 짧은 구간이므로 연환산·순위·스트레스 결론을 만들지 않습니다.": " valuation dates are used. The period is not joined to legacy data, and its short duration does not support annualization, rankings or stress conclusions.",
  "최신 구간 자동 적용": "Latest period applied automatically",
  "명시 구간 적용": "Selected period applied",
  "범위의 연구용 반사실 비교이며, 계정별 매수 가능 상품·환전·세금·주문 가능성을 검증한 투자 권고가 아닙니다. 금현물은 저장된 수동 평가 이력을 사용합니다.": " scope is used for a counterfactual research comparison. Product eligibility, FX conversion, taxes and order feasibility are not verified; this is not investment advice. Spot gold uses recorded manual valuations.",
  "평가액 비교는 유지하지만 가격 기준 또는 계산 입력이 불충분해 수익률 추정치는 표시하지 않습니다.": "The value comparison remains available, but return estimates are hidden because the price basis or calculation inputs are incomplete.",
  "관측 평가일 사이의 일별 가중 현금흐름을 반영한 Modified Dietz 추정치": "Modified Dietz estimate using day-weighted cash flows between observed valuation dates",
  "가격수익 기준 · 배당·수수료·세금 별도 반영 안 함": "Price-return basis · Dividends, fees and taxes not separately included",
  "수익률 차이": "Return difference",
  "KODEX 200 - 실제": "KODEX 200 − Actual",
  "현금흐름 직전 전체 평가액이 없는 구간을 날짜 가중 방식으로 추정한 값이며, 정확한 일별 TWR 또는 총수익률을 의미하지 않습니다.": "Day weighting estimates periods without a complete valuation immediately before cash flows. This is not an exact daily TWR or total return.",
  "전액 VOO 비교": "All-VOO comparison",
  "실제와 같은 원화 매수·매도 금액을 VOO에 적용한 가격수익 경로": "Price-return path applying the same KRW trade amounts to VOO",
  "VOO 종료 평가액": "VOO ending value",
  "VOO - 실제": "VOO − Actual",
  "체결 증거": "Execution data",
  "실제 추정수익률": "Estimated actual return",
  "전액 VOO 추정수익률": "Estimated all-VOO return",
  "경로는 계산됐지만 현금·이벤트 근거가 불충분해 추정수익률은 표시하지 않습니다.": "The path was calculated, but estimated returns are hidden because cash or event data is incomplete.",
  "저장된 평가일마다 실제 평가액과 동일한 원화 거래금액을 VOO raw close와 당시 저장 환율에 적용한 가상 평가액을 비교합니다.": "On each recorded valuation date, compare actual value with a hypothetical value using the same KRW trade amounts, VOO raw closes and the FX rates recorded at the time.",
  "실제 포트폴리오와 VOO 시나리오 비교": "Actual portfolio versus VOO scenario",
  "소수점 수량을 허용해 잔여 현금을 만들지 않으며, 보유 수량을 넘는 매도는 축소·차입 없이 전체 시나리오를 차단합니다. VOO raw close와 같은 서비스 날짜에 저장된 환율을 사용하고 배당 재투자는 제외합니다.": "Fractional quantities avoid residual cash. A sale exceeding the holding quantity blocks the entire scenario without reducing the sale or borrowing. The path uses VOO raw closes and FX rates recorded for the same service date, excluding dividend reinvestment.",
  "전액 VOO 비교 준비도": "All-VOO comparison readiness",
  "미국 종가·환율·체결일 증거가 모두 맞을 때만 다음 단계에서 경로를 계산합니다.": "The path is calculated only when US closes, FX rates and execution dates all reconcile.",
  "계산 입력 준비": "Calculation inputs ready",
  "증거 보완 필요": "Additional data required",
  "VOO 평가 종가": "VOO valuation close",
  "미국 거래일 raw close": "US trading-day raw close",
  "평가 환율": "Valuation FX rate",
  "체결 환율": "Execution FX rate",
  "체결 가격일 exact FX": "Exact FX rate for the execution price date",
  "실제 포트폴리오와 같은 가격수익 기준을 위해 VOO raw close를 사용하고 배당 재투자는 제외합니다. 준비 전에는 부분 경로나 추정값을 표시하지 않습니다.": "VOO raw closes and no dividend reinvestment keep the same price-return basis as the actual portfolio. No partial paths or estimates are shown until the required data is ready.",
  "실제 경로와 가상 경로의 평가일이 일치하지 않습니다.": "Valuation dates differ between the actual and hypothetical paths.",
  "비교 구간의 종가 기준을 확인할 수 없습니다.": "The closing-price basis for this period cannot be verified.",
  "종가와 조정종가 기준이 섞여 있어 동일 기준 비교가 아닙니다.": "Raw and adjusted closes are mixed, so the comparison does not share one price basis.",
  "실제 포트폴리오 수익률 입력을 확인해야 합니다.": "Actual portfolio return inputs need checking.",
  "KODEX 200 수익률 입력을 확인해야 합니다.": "KODEX 200 return inputs need checking.",
  "평가일별 현금 제외 근거를 확인할 수 없습니다.": "Cash-exclusion data cannot be verified for each valuation date.",
  "현금이 있는 구간의 수익률 정책이 아직 확정되지 않았습니다.": "The return policy for periods containing cash has not been defined.",
  "자산 추가·제외 이벤트에 재무 값이 섞여 있어 별도 분류가 필요합니다.": "Asset addition and removal events contain financial values that require separate classification.",
  "수익률에 영향을 줄 수 있는 미분류 이벤트가 있습니다.": "Unclassified events may affect returns.",
  "수익률 계산 입력을 확인해야 합니다.": "Return calculation inputs need checking.",
  "비교 평가일 축을 확인해야 합니다.": "Comparison valuation dates need checking.",
  "일부 평가일의 미국 거래일 종가가 없습니다.": "US trading-day closing prices are missing for some valuation dates.",
  "같은 날짜의 VOO 종가가 중복되어 있습니다.": "Duplicate VOO closes exist for the same date.",
  "사용할 수 없는 VOO 종가가 있습니다.": "Some VOO closing prices are unusable.",
  "일부 평가일의 저장 환율이 없습니다.": "Recorded FX rates are missing for some valuation dates.",
  "같은 평가일의 계좌별 환율이 일치하지 않습니다.": "Account FX rates do not match on the same valuation date.",
  "거래 기준일을 확인해야 합니다.": "Trade reference dates need checking.",
  "거래 이후 체결 가능한 VOO 종가가 없습니다.": "No eligible VOO closing price is available after the trade.",
  "체결 기준일의 VOO 종가가 중복되어 있습니다.": "Duplicate VOO closes exist for the execution date.",
  "체결 기준일의 VOO 종가를 사용할 수 없습니다.": "The VOO close for the execution date is unusable.",
  "거래와 체결 가능일 간격이 허용 범위를 넘었습니다.": "The gap between the trade and eligible execution date exceeds the allowed range.",
  "비교 종료일까지 체결되지 않는 거래가 있습니다.": "Some trades remain unexecuted at the end of the comparison period.",
  "일부 체결 가격일의 USD/KRW가 없습니다.": "USD/KRW rates are missing for some execution price dates.",
  "일부 체결 가격일의 USD/KRW가 중복되어 있습니다.": "Duplicate USD/KRW rates exist for some execution price dates.",
  "일부 체결 가격일의 USD/KRW를 사용할 수 없습니다.": "USD/KRW rates are unusable for some execution price dates.",
  "VOO 비교 입력을 확인해야 합니다.": "VOO comparison inputs need checking.",
  "예시 화면의 시나리오 요약입니다.": "Scenario summary for the example screen.",
  "기간 선택": "Select period",
  "비교 기간": "Comparison period",
  "과거 비교 구간": "Historical comparison period",
  "실제 포트폴리오와 대안 세계선에 같은 기간·현금흐름을 적용합니다.": "The actual portfolio and hypothetical paths use the same period and cash flows.",
  "선택 가능": "Available",
  "시작 관측일": "First observation date",
  "종료 관측일": "Last observation date",
  "구간 적용": "Apply period",
  "최신 구간": "Latest period",
  "최신 비교 가능 구간": "Latest comparable period",
  "를 자동 적용했습니다.": " was applied automatically.",
  "선택 구간": "Selected period",
  "를 다시 계산했습니다.": " was recalculated.",
  "시작일과 종료일은 각각 하나만 지정해야 합니다.": "Specify exactly one start date and one end date.",
  "시작 관측일과 종료 관측일을 모두 선택해 주세요.": "Select both the first and last observation dates.",
  "날짜 형식이 올바르지 않습니다.": "The date format is invalid.",
  "종료 관측일은 시작 관측일보다 뒤여야 합니다.": "The last observation date must follow the first observation date.",
  "선택 가능한 전체 관측 구간을 확인할 수 없습니다.": "The full available observation period cannot be verified.",
  "시작일은 저장된 전체 계정 평가 관측일과 정확히 일치해야 합니다.": "The start date must exactly match a recorded valuation observation covering all accounts.",
  "종료일은 저장된 전체 계정 평가 관측일과 정확히 일치해야 합니다.": "The end date must exactly match a recorded valuation observation covering all accounts.",
  "선택 구간을 하나의 계산 경로로 연결할 근거가 부족합니다. 출처별 실제 관측은 아래에 분리해 표시하고, 시나리오 계산은 검증된 최신 구간에서만 제공합니다.": "The data does not support one continuous calculation path across this period. Actual observations are shown separately by source below; scenarios are available only for the latest verified period.",
  "선택 구간을 확인해 주세요.": "Check the selected period.",
  "기간 시작 전 최소변동성 비교": "Pre-period minimum-volatility comparison",
  "선택한 비교 기간보다 앞선 KODEX 200·VOO 공동 관측 60개만으로 비중을 한 번 산정하고, 이후 실제와 같은 외부 입출금을 적용한 연구 경로입니다.": "Weights are estimated once using only 60 shared KODEX 200 and VOO observations before the comparison period. The research path then applies the same external cash flows as the actual portfolio.",
  "학습 구간": "Training period",
  "KODEX 200 비중": "KODEX 200 weight",
  "VOO 비중": "VOO weight",
  "학습 구간 추정 변동성": "Estimated training-period volatility",
  "공동 관측행 252 기준 연환산": "Annualized using 252 shared observations",
  "비중은 모델의": "This weight is on the boundary imposed by the model's",
  "최소 하한 제약이 작동한 경계값입니다. 무제약 최적 비중이나 투자 권고로 해석하면 안 됩니다.": " minimum-weight constraint. It is not an unconstrained optimal weight or investment recommendation.",
  "비교 경로 계산 완료": "Comparison path calculated",
};
