/** System-owned research copy; financial inputs, identifiers and names are preserved. */
export const SIMULATION_COPY: Readonly<Record<string, string>> = {
  "Stationary bootstrap · 하락위험 과거 관측 검증": "Stationary bootstrap · Historical downside validation",
  "종료 손실확률·최대낙폭 검증": "Terminal loss & drawdown validation",
  "확률밴드와 동일한 90개 학습 구간과 500개 완전 경로를 사용합니다. 예측 종료 손실확률과 MDD P50·P90을, 바로 이어진 실제": "Uses the same 90-observation training windows and 500 complete paths as the fan-band validation. Compare predicted terminal loss probability and MDD P50/P90 with the observed outcomes over the immediately following",
  "선택": "selected",
  "개 관측값의 종료 손실 여부와 MDD에 대조합니다.": " observations.",
  "합격 판정·모델 선택 아님": "Not a pass/fail test or model selection",
  "계산 가능": "Available",
  "평균 예측 종료 손실확률": "Mean predicted terminal loss probability",
  "실제 MDD가 예측 P90 이내": "Observed MDD within predicted P90",
  "겹치는 구간의 기술 통계": "Descriptive statistics for overlapping windows",
  "평균 MDD P50 절대오차": "Mean absolute MDD P50 error",
  "실제 MDD와 예측 중앙값 차이": "Difference between observed MDD and predicted median",
  "연구 기간은": "The research horizon must be",
  "또는": "or",
  "만 선택할 수 있습니다.": " only.",
  "URL에서 검증 종료 기준일을 하나의": "Select exactly one validation end date in the URL using",
  "값으로 선택해야 계산합니다. 최근 날짜로 자동 대체하지 않습니다.": ". The latest date is not automatically substituted.",
  "실제 관측 종료일": "Observed outcome end date",
  "예측 종료 손실확률": "Predicted terminal loss probability",
  "실제 종료": "Observed ending",
  "실제 MDD": "Observed MDD",
  "P90 대조": "P90 comparison",
  "손실": "Loss",
  "비손실": "No loss",
  "P90 이내": "Within P90",
  "P90 초과": "Above P90",
  "계산 불가 ·": "Unavailable ·",
  "실제 종료 손실 횟수와 P90 대조는 겹치는 7개 관측 구간의 기술 통계입니다. 독립 시행의 적중률이나 모델 합격·불합격으로 해석하지 않으며, 날짜 선택·파라미터 조정·추천에는 사용하지 않습니다. 데이터가 부족한 행만 계산하지 않고 나머지 행은 유지합니다.": "Observed loss counts and P90 comparisons describe seven overlapping windows. They are not independent-trial hit rates, model pass/fail results, or inputs to date selection, tuning or recommendations. Only rows with insufficient data remain uncalculated; other rows are retained.",
  "Stationary bootstrap · 과거 관측 검증": "Stationary bootstrap · Historical validation",
  "종료수익률 P10~P90 확률밴드 검증": "Terminal-return P10–P90 band validation",
  "KODEX 200 50%와 VOO 50%를 처음 한 번 배분하고 리밸런싱하지 않은 연구 포트폴리오입니다. 각 행은 앞선 90개 공동 KRW 수익률로 500개 경로를 만들고, 이어진 실제": "A research portfolio initially allocated 50% to KODEX 200 and 50% to VOO, without rebalancing. Each row uses 90 prior joint KRW returns to generate 500 paths and compares them with the next",
  "개 관측값과 비교합니다.": " observed returns.",
  "예측·추천·계정 결과 아님": "Not a forecast, recommendation or account result",
  "P10~P90 포함률": "P10–P90 coverage",
  "비교 가능한 행 없음": "No comparable rows",
  "평균 P50 절대오차": "Mean absolute P50 error",
  "실제 종료수익률과 중앙값 차이": "Difference between the observed terminal return and median",
  "학습 종료일": "Training end date",
  "실제": "Observed",
  "P50 오차": "P50 error",
  "포함": "Included",
  "이탈": "Outside",
  "최근 7개 종료일의 구간은 서로 크게 겹치므로 독립된 7번의 실험이 아닙니다. 포함률은 기술 진단값이며 합격 판정, 최적 날짜 선정, 파라미터 조정에 사용하지 않습니다. 데이터가 부족한 행만 계산하지 않고 나머지 행은 유지합니다.": "The latest seven windows overlap substantially and are not seven independent experiments. Coverage is a descriptive diagnostic, not a pass/fail test or an input to optimal-date selection or tuning. Only rows with insufficient data remain uncalculated; the others are retained.",
  "고정 비중 3안 공통 경로 비교": "Three fixed mixes on common paths",
  "25:75, 50:50, 75:25가 같은 path별 날짜 행과 블록 순서를 사용합니다. 최초 비중만 다르고 입력 행렬과 무작위 표본은 같아, 비중 차이만 비교할 수 있습니다.": "The 25:75, 50:50 and 75:25 mixes use identical dates and block sequences for each path. Only initial weights differ; input matrices and random samples are shared, isolating the effect of weights.",
  "성과 순위·추천 아님": "Not a performance ranking or recommendation",
  "세 비중의 공통 경로를 계산하지 않았습니다.": "Common paths for the three mixes were not calculated.",
  "준비된 단일 종목 결과와 사용자가 선택한 비중 결과는 그대로 유지됩니다.": "Available single-instrument results and the user-selected mix remain visible.",
  "세 그래프는 같은 세로축을 사용합니다. 각 카드의 위치는 KODEX 200 비중 오름차순이며 성과 순위가 아닙니다. 경로 500개 ·": "The three charts share a vertical axis. Cards are ordered by ascending KODEX 200 weight, not performance. 500 paths ·",
  "서비스 기준일 수익률": " service-date return",
  "단계 · 리밸런싱 없음.": " steps · No rebalancing.",
  "현재 선택": "Current selection",
  "비교용 고정 비중을 검증하지 못했습니다.": "The comparison weights could not be verified.",
  "연구 기간은 서비스 기준일 수익률 63단계 또는 126단계만 선택할 수 있습니다.": "The research horizon must be 63 or 126 service-date return steps.",
  "기준일을 직접 선택한 뒤에만 비교를 시작합니다.": "Comparison starts only after explicitly selecting a reference date.",
  "두 종목 모두에 대해 같은 날짜축의 완전한 90개 수익률 쌍이 없습니다.": "The two instruments do not have 90 complete return pairs on a shared date axis.",
  "입력 기간 또는 종목 구성이 069500·VOO 공동 연구 규격과 일치하지 않습니다.": "The period or instruments do not match the joint 069500–VOO research specification.",
  "비교용 명시 비중 연구 가정을 검증하지 못했습니다.": "The explicit-weight research assumptions for comparison could not be verified.",
  "공통 재표본 추출 계획을 만들지 못했습니다.": "A common resampling plan could not be created.",
  "공통 종목 성장 경로를 만들지 못했습니다.": "Common instrument-growth paths could not be created.",
  "비중별 정규화 경로를 계산하지 못했습니다.": "Normalized paths for each weight mix could not be calculated.",
  "경로는 계산했지만 분포·위험 요약 검증을 통과하지 못했습니다.": "Paths were calculated, but distribution and risk summaries failed validation.",
  "명시 비중 공동 포트폴리오 연구": "Explicit-weight joint portfolio research",
  "KODEX 200과 VOO의 같은 기준일 수익률 쌍을 한 행으로 묶어 함께 재표본합니다. 선택한 최초 비중만 적용하고 이후에는 리밸런싱하지 않아, 두 자산의 성과에 따라 비중이 자연스럽게 달라지는 buy-and-hold 경로입니다.": "Resample same-date KODEX 200 and VOO return pairs together. Only the selected initial weights apply, with no subsequent rebalancing, producing buy-and-hold paths whose weights drift with the two assets’ returns.",
  "고정 연구 가정 · 추천 아님": "Fixed research assumptions · Not a recommendation",
  "공동 경로를 계산하지 않았습니다.": "Joint paths were not calculated.",
  "단일 종목 입력이 준비된 경우에는 위 결과를 그대로 볼 수 있습니다.": "Available single-instrument results remain visible above.",
  "방법 v2: 완전한 KRW 투자자 기준 수익률 쌍 90개 · stationary bootstrap · 평균 블록 5단계 · 서비스 기준일 수익률": "Method v2: 90 complete KRW investor return pairs · Stationary bootstrap · Mean block length 5 · Service-date return",
  "단계 · 500경로. 같은 입력 행렬, 엔진 정책, 고정 seed에서만 결과가 동일합니다. 시장 국면 조건, 미래 예측, 계좌 보유비중, Fount, 금현물은 사용하지 않습니다.": " steps · 500 paths. Results repeat only with the same matrix, engine policy and fixed seed. Market-regime conditions, forecasts, account weights, Fount and physical gold are excluded.",
  "공통 날짜쌍 공동 재표본": "Joint resampling of common-date pairs",
  "· 최초 배분 후 리밸런싱 없음": "· No rebalancing after initial allocation",
  "계산 완료": "Calculation complete",
  "종료 분포 P10": "Terminal distribution P10",
  "기준일": "As of",
  "· 공통 수익률 쌍": "· Common return pairs:",
  "개 · 시작지수 100": " · Starting index 100",
  "KODEX 200 비중은 중복 없이 1~99 사이의 정수 퍼센트로 입력해야 합니다.": "Enter KODEX 200 weight exactly once as an integer percentage between 1 and 99.",
  "공동 연구 실행은 기준일을 직접 선택한 뒤에만 시작합니다.": "Joint research starts only after explicitly selecting a reference date.",
  "선택한 명시 비중 연구 가정을 검증하지 못했습니다.": "The selected explicit-weight research assumptions could not be verified.",
  "공동 재표본 추출 계획을 만들지 못했습니다.": "A joint resampling plan could not be created.",
  "두 종목의 누적 성장 경로를 계산하지 못했습니다.": "Cumulative growth paths for the two instruments could not be calculated.",
  "선택 비중의 정규화 경로를 계산하지 못했습니다.": "Normalized paths for the selected weights could not be calculated.",
  "KODEX 200 최초 비중": "Initial KODEX 200 weight",
  "이 비중으로 계산": "Calculate this mix",
  "공동 연구 비중 예시": "Joint-research weight examples",
  "단계 연구 시뮬레이션": "-step research simulation",
  "선택한 기준일까지의 90개 수익률을 평균 5단계 블록의 stationary bootstrap으로 재표본해 서비스 기준일 수익률": "Resample 90 returns through the selected date using stationary bootstrap with blocks averaging five steps, to calculate",
  "단계 경로 500개를 계산합니다. 두 종목은 각각 100% 보유한 경우로 독립 실행합니다. 두 결과의 차이는 공동 초과확률이나 순위를 뜻하지 않습니다.": "-step paths, 500 in total. The two instruments run independently as 100% holdings. Differences do not imply joint outperformance probabilities or rankings.",
  "연구용 · 저장 안 함 · 예측 아님": "Research only · Not saved · Not a forecast",
  "현재 기준일의 완전한 입력이 없습니다. 확인된 최근 관측일을 자동 적용하지 않고, 직접 선택하면 그 날짜로 실행합니다.": "The current reference date has incomplete inputs. A recent observed date is not automatically applied; select it explicitly to run that date.",
  "로 실행": ": run",
  "방법: KRW 투자자 기준 수익률 90개 · 평균 블록 5단계 · 서비스 기준일 수익률": "Method: 90 KRW investor returns · Mean block length 5 · Service-date return",
  "단계 · 500경로. 같은 입력 행렬, 엔진 정책, 고정 seed에서만 결과가 동일합니다. 시장 국면을 조건으로 삼는 regime bootstrap 모델은 아닙니다.": " steps · 500 paths. Results repeat only with the same matrix, engine policy and fixed seed. This is not a regime-conditioned bootstrap model.",
  "단일 종목 100%": "Single instrument, 100%",
  "· 시작지수 100 · 수수료·세금 미포함": "· Starting index 100 · Excludes fees and taxes",
  "연구 실행은 기준일을 직접 선택한 뒤에만 시작합니다.": "Research starts only after explicitly selecting a reference date.",
  "이 기준일에는 완전한 90개 수익률 입력이 없어 실행하지 않았습니다.": "This date does not have 90 complete return inputs, so research was not run.",
  "입력 기간 또는 종목 구성이 고정 연구 규격과 일치하지 않습니다.": "The period or instruments do not match the fixed research specification.",
  "단일 종목 100% 연구 가정을 검증하지 못했습니다.": "The 100% single-instrument research assumptions could not be verified.",
  "재표본 추출 계획을 만들지 못했습니다.": "A resampling plan could not be created.",
  "재표본 경로의 누적 수익률을 계산하지 못했습니다.": "Cumulative returns of resampled paths could not be calculated.",
  "정규화 경로를 계산하지 못했습니다.": "Normalized paths could not be calculated.",
  "필요한 관측값 부족": "Insufficient observations",
  "관측 구간 불일치": "Observation windows do not match",
  "경로 계산 불가": "Path calculation unavailable",
  "실제 경로 계산 불가": "Observed-path calculation unavailable",
  "입력 확인 필요": "Review inputs",
  "교차시장 정렬 근거": "Cross-market alignment evidence",
  "공통 서비스 날짜에 정확한 관측값이 없으면 가격은 최대 7일, USD/KRW는 최대 3일 범위에서 직전 저장값을 사용합니다. 휴장일을 실제 거래일로 간주하거나 미래 값을 당겨 쓰지 않습니다.": "When a common service date lacks an exact observation, the latest stored price may be carried for up to seven days and USD/KRW for up to three. Market closures are not treated as trading sessions and future values are never brought forward.",
  "원본 가격·환율·관측 날짜는 표시하지 않음": "Source prices, FX values and observation dates are not displayed",
  "비교 입력이 완전히 준비되지 않아 정렬 집계를 표시하지 않습니다.": "Comparison inputs are incomplete, so alignment counts are not shown.",
  "종목": "Holding",
  "가격 정확 관측": "Exact price observations",
  "가격 직전값 적용": "Price carry count",
  "가격 최대 적용": "Maximum price carry",
  "환율 정확 관측": "Exact FX observations",
  "환율 직전값 적용": "FX carry count",
  "환율 최대 적용": "Maximum FX carry",
  "KRW 종목 · 환율 불필요": "KRW instrument · No FX conversion needed",
  "정확 관측은 해당 서비스 날짜에 대응하는 저장 근거를 뜻합니다. 직전값 적용은 휴장일 등으로 정책 범위 안의 가장 최근 저장 근거를 사용한 횟수입니다.": "An exact observation is stored evidence matching the service date. Carry counts show how often the latest prior stored evidence was used within policy, for example during market closures.",
  "90개 관측구간 누적지수 비교": "Cumulative index over 90 observations",
  "두 입력이 같은 91개 날짜축으로 모두 준비될 때만 표시합니다. 날짜 자동 대체나 부분 비교는 하지 않습니다.": "Shown only when both inputs are complete on the same 91-point date axis. Dates are not substituted and partial comparisons are not shown.",
  "두 독립 연구 입력의 과거 KRW 수익률을 각각 시작 100으로 누적했습니다. 휴장일에는 아래 정렬 근거의 허용 범위 안에서 직전 저장값이 적용될 수 있습니다. 포트폴리오 조합·예측·시뮬레이션 경로가 아닙니다.": "Accumulate each independent research input’s historical KRW returns from 100. Prior stored values may carry across market closures within the alignment policy below. These are observed indices, not a portfolio mix, forecast or simulated path.",
  "공통 날짜축": "Common date axis",
  "누적": "Cumulative",
  "KODEX 200과 VOO의 과거 KRW 누적 관측지수 공통축 비교 차트": "Shared-axis chart of historical KRW cumulative indices for KODEX 200 and VOO",
  "KODEX 200과 VOO의 과거 KRW 누적 관측지수 비교": "Historical KRW cumulative indices for KODEX 200 and VOO",
  "전체": "All",
  "개 누적지수 표 보기": " cumulative-index rows",
  "지수": "Index",
  "두 연구 입력이 모두 준비되지 않아 비교하지 않습니다.": "Both research inputs must be ready before comparison.",
  "두 연구 입력의 관측 날짜축이 일치하지 않아 비교하지 않습니다.": "The research inputs have different observation date axes.",
  "정확히 90개 수익률과 91개 관측점이 확인되지 않아 비교하지 않습니다.": "Exactly 90 returns and 91 observations could not be verified.",
  "완전하고 유효한 누적 관측지수를 만들 수 없어 비교하지 않습니다.": "Complete, valid cumulative observed indices could not be produced.",
  "비교할 독립 연구 입력 구성이 올바르지 않습니다.": "The independent research-input configuration is invalid.",
  "개 관측 수익률": " observed returns",
  "저장된 조정종가와 기준일별 환율로 계산한 과거 KRW 단순수익률입니다.": "Historical simple KRW returns calculated from stored adjusted closes and date-specific exchange rates.",
  "예측·시뮬레이션 경로 아님": "Not a forecast or simulated path",
  "두 입력 공통": "Shared between both inputs",
  "개별": "Individual",
  "세로축": "Vertical axis",
  "관측 행": "Observation rows",
  "최근 수익률": "Latest return",
  "최고": "Highest",
  "최저": "Lowest",
  "개 수익률 표 보기": " return rows",
  "이전 기준일": "Previous reference date",
  "KRW 수익률": "KRW return",
  "현재안과 같은 500개 경로": "Same 500 paths as current weights",
  "변동성 완화 후보 비교": "Compare a lower-volatility candidate",
  "최근 90개 공동 수익률에서 변동성이 낮았던 비중을 찾고, 현재 비중과 동일한 날짜 추출·무작위 경로로 나란히 계산합니다. 회전율과 외화 비중 변화를 제한한 연구 후보이며 투자 추천이 아닙니다.": "Find weights with lower volatility over the latest 90 joint returns, then compare them with current weights using identical date samples and random paths. This research candidate constrains turnover and FX-weight changes; it is not investment advice.",
  "조회 시 계산 · 저장 안 함": "Calculated on request · Not saved",
  "후보 비중 비교를 만들지 않았습니다.": "A candidate-weight comparison was not created.",
  "현재 포트폴리오 확률 경로는 그대로 유지됩니다.": "Current portfolio paths remain available.",
  "현재 비중": "Current weights",
  "변동성 완화 후보": "Lower-volatility candidate",
  "최근 90개 수익률 기준": "Based on the latest 90 returns",
  "연환산 변동성": "Annualized volatility",
  "필요한 비중 이동": "Required weight turnover",
  "외화 비중 변화": "FX-weight change",
  "후보 - 현재": "Candidate − current",
  "중앙 경로 수익률 차이": "Median-path return difference",
  "두 그래프는 동일한 세로축과 동일한 bootstrap 추출 경로를 사용합니다. 후보는 종목당 최대": "Both charts share a vertical axis and identical bootstrap samples. The candidate limits each holding to",
  ", 한 방향 회전율 최대": ", one-way turnover to",
  ", 외화 비중 변화 최대": ", and FX-weight change to",
  "로 제한했습니다.": ".",
  "현재": "Current",
  "후보": "Candidate",
  "변화": "Change",
  "이 후보는 같은 90개 과거 행으로 비중을 추정하고 미래 경로도 만들기 때문에 아직 표본 내 연구 결과입니다. 수수료·세금은 0으로 가정했으며, 별도의 시점별 검증을 통과하기 전에는 추천·주문 비중으로 사용할 수 없습니다.": "This is still in-sample research: the same 90 historical rows estimate weights and generate paths. Fees and taxes are assumed zero. It cannot serve as recommendation or order weights before separate point-in-time validation.",
  "현재 포트폴리오 경로가 먼저 준비되어야 합니다.": "Current portfolio paths must be ready first.",
  "계산 가능한 상장 종목이 하나뿐이면 비중 대안을 만들 수 없습니다.": "A weight alternative requires more than one eligible listed holding.",
  "현재 비중과 수익률 행렬의 종목 순서가 일치하지 않습니다.": "Current weights and the return matrix have different instrument orders.",
  "제약 안에서 저변동 비중을 계산하지 못했습니다.": "Lower-volatility weights could not be calculated within the constraints.",
  "제약을 적용한 후보가 현재 비중보다 변동성을 낮추지 못했습니다.": "The constrained candidate did not reduce volatility relative to current weights.",
  "회전율·외화·집중도 제약을 모두 만족하지 못했습니다.": "Turnover, FX and concentration constraints were not all satisfied.",
  "후보 비중 합계와 종목 식별을 검증하지 못했습니다.": "Candidate-weight totals and holding identities could not be verified.",
  "공통 재표본 추출 계획을 확인하지 못했습니다.": "The common resampling plan could not be verified.",
  "공통 종목 성장 경로를 확인하지 못했습니다.": "Common instrument-growth paths could not be verified.",
  "후보 비중의 정규화 경로를 계산하지 못했습니다.": "Normalized paths for the candidate weights could not be calculated.",
  "후보 경로의 분포·위험 요약을 검증하지 못했습니다.": "Distribution and risk summaries for the candidate paths could not be verified.",
  "현재 구성 고정 · 과거 약 1개월 관측 점검": "Current composition held fixed · Roughly one month of historical outcomes",
  "내 포트폴리오 예측 범위와 실제 결과": "Your portfolio’s model range & observed outcomes",
  "현재 상장종목 비중을 과거에도 그대로 보유했다고 가정합니다. 각 종료일 직전 90개 수익률로 500개 경로를 만든 뒤, 바로 이어진 21개 수익률 구간의 실제 결과와 비교합니다.": "Assume today’s listed-holding weights also applied historically. At each endpoint, use the preceding 90 returns to generate 500 paths, then compare with observed outcomes over the immediately following 21 returns.",
  "읽기 전용 · 추천 아님": "Read-only · Not a recommendation",
  "계산 가능 구간": "Calculable periods",
  "P10~P90 안에 실제 결과가 있었던 구간": "Periods with observed outcomes inside P10–P90",
  "예측 범위 포함": "Model-range coverage",
  "실제 결과와 예측 중앙값 차이": "Difference between the observed result and predicted median",
  "평균 중앙값 오차": "Mean median error",
  "평균 예측 손실확률": "Mean predicted loss probability",
  "현재 구성의 확률 경로가 먼저 계산되어야 과거 결과를 대조할 수 있습니다. 입력 점검에 표시된 종목과 이력 상태는 그대로 유지합니다.": "Current-composition paths must be calculated before historical outcomes can be compared. Holding and history diagnostics remain visible in Input checks.",
  "실제 종료일": "Observed end date",
  "예측 손실": "Predicted loss",
  "범위": "Range",
  "이 결과는 현재 구성을 과거에 고정 적용한 사후 점검입니다. 당시 실제 보유량·매매 내역을 재현한 성과가 아니며, 비중 최적화나 주문 근거로 사용하지 않습니다.": "This is a retrospective diagnostic applying today’s composition to the past. It does not reproduce historical holdings or trades, and is not used for weight optimization or orders.",
  "저장된 KIS 미조정 종가와 날짜별 환율을 사용하므로 배당·액면분할·병합을 반영한 총수익률과 다를 수 있습니다. 데이터가 부족한 행만 제외하고 계산 가능한 행은 유지합니다.": "Uses stored unadjusted KIS closes and date-specific FX, which can differ from total returns adjusted for dividends, splits and consolidations. Only data-deficient rows are excluded; calculable rows remain.",
  "로그인 사용자 보유종목 기준": "Based on the signed-in user’s holdings",
  "내 포트폴리오 입력 점검": "Portfolio input checks",
  "현재 보유 구성과 저장된 과거 가격 이력을 계좌별로 점검합니다. 이 비중은 아래의 일회성 연구 계산에만 사용하며 저장된 목표 비중, 최적화, 추천 또는 주문 근거로 사용하지 않습니다.": "Review current composition and stored price history by account. These weights are used only for one-off research calculations, not as saved targets, optimization results, recommendations or order instructions.",
  "분석 범위": "Analysis scope",
  "분석 종목": "Holdings analyzed",
  "현재 평가액 기준 진단값": "Diagnostic based on current valuations",
  "현재 평가액": "Current value",
  "과거 이력 확인": "History readiness",
  "현재 단일 사용자 연구 모드는 저장된 KIS 종가를 사용합니다. 배당과 액면분할·병합 조정은 주장하지 않으며, 이 결과는 추천이나 주문 근거로 저장되지 않습니다.": "Current single-user research uses stored KIS closes. It does not claim dividend, split or consolidation adjustments, and results are not saved as recommendations or order instructions.",
  "건은 사용자 결정에 따라 투자 랩과 시뮬레이션에서 제외했습니다. 제외 금액은": " items are excluded from the Investment Lab and simulation according to the user’s choice. Excluded value:",
  "입니다.": ".",
  "입력 후보를 확정하지 않았습니다.": "Input candidates have not been finalized.",
  "계좌": "Account",
  "과거 이력 상태": "Historical-data status",
  "금현물은 사용자가 기록한 평가 이력만 사용합니다.": "Physical gold uses only valuation history recorded by the user.",
  "평가액을 확인하지 못한 보유종목": "Holdings without a verified valuation",
  "종목 식별을 완료하지 못한 보유종목": "Holdings without a resolved identity",
  "저장 이력이 일부 부족해도 확인 가능한 종목과 비중은 숨기지 않습니다. 부족한 상장 종목은 임의의 평균값이나 현재 가격으로 과거를 만들지 않으며, 공급자 보강 경로가 준비되기 전까지 부족한 범위를 명시한 진단을 제공합니다.": "Available holdings and weights remain visible even when stored history is incomplete. Missing history is not invented using averages or current prices; diagnostics identify the missing range until provider supplementation is ready.",
  "저장 이력 점검 전 또는 입력 진단 필요": "History not checked or input diagnostics required",
  "양수 비중 중 사용 가능한 이력": "Usable history among positive-weight holdings",
  "계좌 범위가 서버 조회 결과와 일치하지 않음": "Account scope differs from server query results",
  "평가액이 양수인 보유종목이 없음": "No holdings have a positive valuation",
  "현재 평가액을 확인하지 못한 보유종목이 있음": "Some holdings lack a verified current valuation",
  "종목 식별자를 확정하지 못한 보유종목이 있음": "Some holding identifiers are unresolved",
  "분석 가능한 최대 종목 수를 초과함": "The maximum number of analyzable holdings is exceeded",
  "현재 평가액 기반 비중 계산을 완료하지 못함": "Weights based on current valuations could not be calculated",
  "과거 이력 점검 전": "History not checked",
  "저장 이력 사용 가능": "Stored history available",
  "저장 이력 부족": "Insufficient stored history",
  "출처 근거 부족": "Insufficient source evidence",
  "0bps 행 보존": "Zero-bps row retained",
  "정책상 제외": "Excluded by policy",
  "수동 평가 이력 필요": "Manual valuation history required",
  "종목 식별 필요": "Holding identity required",
  "부분 진단": "Partial diagnostic",
  "현재 가격 없음": "Missing current price",
  "환율 없음": "Missing FX",
  "지원하지 않는 통화": "Unsupported currency",
  "같은 과거 구간에서 실제 결과와 대조": "Compare against observed outcomes in the same historical periods",
  "과거 결과로 두 모형 점검": "Check both models against historical outcomes",
  "부트스트랩과 요인·잔차 모형이 예측한 범위를 이후 21거래일의 실제 결과와 같은 조건에서 비교합니다. 숫자가 낮을수록 과거 오차가 작았다는 뜻일 뿐, 우승 모형이나 투자 추천을 정하지 않습니다.": "Compare bootstrap and factor–residual model ranges with observed outcomes over the next 21 trading observations under matching conditions. Lower numbers mean smaller historical errors; no winning model or investment recommendation is chosen.",
  "읽기 전용 · 모형 선택 금지": "Read-only · No model selection",
  "비교 완료": "Comparison complete",
  "수익률 관측치가 서로 겹치지 않는 21거래일 구간 수": "Count of 21-observation outcome windows with non-overlapping returns",
  "겹치지 않는 구간": "Non-overlapping windows",
  "예상 중앙값과 실제 수익률 차이의 평균": "Mean difference between expected medians and observed returns",
  "중앙값 평균 오차": "Mean median error",
  "실제 결과가 각 모형의 P10~P90 안에 들어온 비율": "Share of observed outcomes within each model’s P10–P90 range",
  "예상 범위 적중률": "Model-range coverage",
  "손실 확률의 Brier 오차, 0에 가까울수록 작음": "Brier error for loss probability; closer to zero is smaller",
  "손실 확률 오차": "Loss-probability error",
  "예상 중앙 최대낙폭과 실제 최대낙폭 차이의 평균": "Mean difference between predicted median and observed maximum drawdown",
  "최대낙폭 평균 오차": "Mean drawdown error",
  "결과 기준일": "Outcome date",
  "실제 수익률": "Observed return",
  "부트스트랩 중앙값": "Bootstrap median",
  "부트스트랩 오차": "Bootstrap error",
  "요인 모형 중앙값": "Factor-model median",
  "요인 모형 오차": "Factor-model error",
  "상태": "Status",
  "비교할 수 없는 구간": "Uncomparable periods:",
  "개도 숨기지 않고 표에 남겼습니다.": " remain visible in the table.",
  "현재 저장 이력으로는 서로 겹치지 않는 구간을 최대": "Current stored history supports at most",
  "개 중": " windows, of which",
  "개 구성할 수 있습니다. 부족한 과거 구간은 평균값이나 현재 가격으로 만들지 않았습니다.": " can be formed. Missing historical windows are not invented using averages or current prices.",
  "현재 계좌 구성과 비중을 과거 구간에 소급 적용한 진단입니다. 21거래일 결과 구간은 저장된 서비스 날짜 축에서 수익률이 서로 겹치지 않게 구성합니다. 그래도 표본 수가 적으므로 통계적 신뢰도나 모형 순위를 주장하지 않습니다. 요인 데이터는 당시 공개일 기준으로만 사용하지만 데이터의 과거 버전 기록은 보존되지 않아, 이후 정정된 값이 포함될 수 있습니다.": "This diagnostic applies current account holdings and weights retrospectively. The 21-observation outcome windows have non-overlapping returns on the stored service-date axis. The sample remains small, so statistical confidence or model rankings are not claimed. Factors use their historical release dates, but original data vintages are not preserved and later corrections may be present.",
  "비교 자료 부족": "Insufficient comparison data",
  "부트스트랩 범위 적중": "Within bootstrap range",
  "부트스트랩 범위 밖": "Outside bootstrap range",
  "요인 범위 적중": "Within factor range",
  "요인 범위 밖": "Outside factor range",
  "기준일 불일치": "Reference dates differ",
  "원본 계산 미완료": "Source calculation incomplete",
  "학습·결과 구간 불일치": "Training or outcome windows differ",
  "실제 결과 불일치": "Observed outcomes differ",
  "확인 필요": "Review required",
  "같은 보유 비중 · 다른 확률 가정": "Same holdings · Different probability assumptions",
  "두 확률모형 비교": "Compare two probability models",
  "과거 수익률 구간을 다시 뽑는 모형과 환율·금리 관계를 추정하는 모형을 같은 계정·기준일·기간에서 나란히 봅니다. 어느 한쪽을 정답으로 고르거나 두 확률을 평균내지 않습니다.": "Compare a model that resamples historical return blocks with a model that estimates FX and interest-rate relationships, using the same account, date and horizon. Neither is selected as correct, and their probabilities are not averaged.",
  "요인모형 - 재표본모형": "Factor model − bootstrap",
  "중앙 수익률 차이": "Median return difference",
  "P5 수익률 차이": "P5 return difference",
  "손실확률 차이": "Loss-probability difference",
  "종료 P10~P90 교집합 / 합집합": "Intersection / union of terminal P10–P90 intervals",
  "예상 범위 겹침": "Range overlap",
  "요인 결합 관측": "Factor-aligned observations",
  "예상 범위 겹침은 확률의 정확도를 뜻하지 않고, 서로 다른 가정에서 나온 분포가 얼마나 비슷한 영역을 가리키는지만 보여줍니다.": "Range overlap describes how similar the regions produced by different assumptions are. It does not measure probability accuracy.",
  "재표본모형은 저장된 공동 수익률": "The bootstrap model uses",
  "개를 사용하고, 요인모형은 그중 환율·금리 자료가 맞물린": " joint stored returns; the factor model uses",
  "개만 사용했습니다. 두 결과의 차이는 오류가 아니라 표본과 가정에 대한 민감도일 수 있습니다. 정확한 경제지표 공개 시각·개정 이력이 없으므로 요인모형은 회고적 연구입니다.": " observations aligned with FX and rates. Differences can reflect sensitivity to samples and assumptions. Without precise release times and revision history, the factor model remains retrospective research.",
  "두 모형의 직접 비교만 보류했습니다.": "Direct comparison is unavailable.",
  "준비된 개별 모형 결과와 입력 진단은 위 영역에서 계속 확인할 수 있습니다.": "Available individual-model results and input diagnostics remain visible above.",
  "과거 구간 재표본": "Historical block bootstrap",
  "환율·금리 요인": "FX & rate factors",
  "준비 안 됨": "Not ready",
  "방향과 예상 범위가 대체로 겹칩니다.": "The direction and ranges broadly overlap.",
  "방향은 같지만 예상 크기가 크게 다릅니다.": "The direction agrees, but the expected sizes differ substantially.",
  "중앙 방향이 모형 가정에 따라 달라집니다.": "The median direction depends on the model assumptions.",
  "두 모형이 방향과 범위 모두 다르게 봅니다.": "The models differ in both direction and range.",
  "두 모형이 같은 수익 방향을 가리키고 P10~P90 구간도 겹칩니다.": "The models indicate the same return direction and overlapping P10–P90 ranges.",
  "두 모형의 중앙값 부호는 같지만 P10~P90 구간은 겹치지 않습니다.": "The medians have the same sign, but P10–P90 ranges do not overlap.",
  "중앙값 부호는 다르지만 P10~P90 구간에는 공통 영역이 있습니다.": "The medians have different signs, but P10–P90 ranges overlap.",
  "중앙값 부호가 다르고 P10~P90 구간에도 공통 영역이 없습니다.": "The medians have different signs and P10–P90 ranges do not overlap.",
  "과거 구간 재표본 결과가 먼저 준비되어야 합니다.": "The historical bootstrap result must be ready first.",
  "환율·금리 요인 결과가 먼저 준비되어야 합니다.": "The FX and interest-rate factor result must be ready first.",
  "두 결과의 계정 범위가 일치하지 않습니다.": "The account scopes do not match.",
  "두 결과의 종목별 보유 비중이 일치하지 않습니다.": "The holding weights do not match.",
  "두 결과의 투자기간이 일치하지 않습니다.": "The horizons do not match.",
  "두 결과의 경로 수가 일치하지 않습니다.": "The path counts do not match.",
  "두 결과의 기준일이 일치하지 않습니다.": "The reference dates do not match.",
  "두 결과의 경로 단계가 일치하지 않습니다.": "The path steps do not match.",
  "비교할 위험 요약에 유효하지 않은 숫자가 있습니다.": "The risk summaries contain invalid numbers.",
  "확률 경로를 비중으로 역산": "Explore weights from probabilistic paths",
  "목적별 비중 후보": "Weight candidates by objective",
  "500개 경로를 탐색용 250개와 확인용 250개로 분리합니다. 현재 비중보다 확인용 경로에서도 나아진 경우만 보여주며, 같은 종목·환율 자료와 같은 무작위 경로를 사용합니다.": "Split 500 paths into 250 exploration paths and 250 validation paths. Only candidates that also improve on current weights in the validation paths are shown, using the same instruments, FX data and random paths.",
  "비중 후보 목적": "Candidate objective",
  "확인 경로를 통과한 비중 후보가 없습니다.": "No weight candidate passed path validation.",
  "현재 비중의 확률 경로와 기존 변동성 완화 후보는 그대로 확인할 수 있습니다.": "Current-weight paths and the existing volatility-reduction candidate remain available.",
  "확인용 250개 경로": "250 validation paths",
  "전체 500개 경로 · 후보 - 현재": "All 500 paths · Candidate − current",
  "중앙값 수익률 차이": "Median return difference",
  "낮을수록 방어적": "Lower means more defensive",
  "손실 확률 차이": "Loss-probability difference",
  "이 후보는 종목당 최대": "This candidate limits each holding to",
  ", 한 방향 비중 이동 최대": ", one-way weight turnover to",
  "를 지킵니다. 조회 시 계산되는 연구 결과이며 수수료·세금·주문 가능 여부를 반영한 투자 추천이 아닙니다.": ". This is research calculated on request, not investment advice accounting for fees, taxes or order eligibility.",
  "중앙값 수익": "Median return",
  "하방 방어": "Downside protection",
  "수익·방어 균형": "Return–protection balance",
  "중앙값 개선": "Median improvement",
  "P10 개선": "P10 improvement",
  "균형 점수 개선": "Balance-score improvement",
  "계산 가능한 종목과 현재 비중의 순서가 맞지 않습니다.": "The eligible instruments and current weights are in different orders.",
  "탐색·확인에 필요한 경로 수가 부족합니다.": "There are too few paths for exploration and validation.",
  "확률 경로의 결과 지표를 계산하지 못했습니다.": "Outcome metrics could not be calculated for the paths.",
  "회전율·집중도·외화 제약과 확인 경로 개선을 함께 만족한 대안이 없습니다.": "No alternative satisfies turnover, concentration and FX constraints while improving validation-path results.",
  "현재 입력에서는 목적별 대안을 만들지 못했습니다.": "No objective-based alternative could be produced from the current inputs.",
  "별도 모형 · 부트스트랩과 합산하지 않음": "Separate model · Not combined with bootstrap",
  "환율·금리 요인 확률모형": "FX & rate factor model",
  "같은 날짜의 종목 수익률과 USD/KRW·미국 10년물 금리·장단기 금리차 변화를 맞춰 통계 관계를 추정한 뒤 500개 경로를 계산합니다. 기존 재표본 추출과 다른 가정의 결과이므로 두 모형의 차이 자체를 불확실성으로 봐야 합니다.": "Align same-date holding returns with changes in USD/KRW, US 10-year yields and the yield spread, estimate statistical relationships, then calculate 500 paths. Its assumptions differ from bootstrap, so disagreement between the models is itself a source of uncertainty.",
  "요인 결합 수익률": "Factor-aligned returns",
  "USD/KRW · 10년물 · 장단기차": "USD/KRW · 10-year yield · Yield spread",
  "시장 요인": "Market factors",
  "3개": "3 factors",
  "최근 데이터에 더 큰 가중치": "Greater weight on recent data",
  "공분산": "Covariance",
  "두꺼운 꼬리 충격": "Heavy-tailed shocks",
  "분포": "Distribution",
  "현재 저장 자료에는 각 지표의 정확한 공개 시각과 개정 이력이 없습니다. 같은 날 발표값은 다음 서비스 날짜부터 사용했지만 완전한 시점별 예측 검증은 아직 성립하지 않습니다. 이 결과는 회고적 연구이며 예측·추천·주문 근거가 아닙니다.": "Precise indicator release times and revision histories are unavailable. Same-day releases are used only from the next service date, but strict point-in-time validation is not yet established. This is retrospective research, not a forecast, recommendation or order basis.",
  "이 모형만 아직 계산할 수 없습니다.": "This model cannot yet be calculated.",
  "기존 보유 비중 부트스트랩과 다른 검증 결과는 그대로 유지됩니다.": "Existing holding-weight bootstrap and other validation results remain available.",
  "같은 날짜의 수익률·환율·금리": "Same-date returns, FX and rates",
  "현재 결합 관측": "Currently aligned observations",
  "최소 필요": "Minimum required",
  "일일 작업에서 별도로 재시도": "Retried separately by the daily job",
  "해결 경로": "Recovery path",
  "팩터 자동 동기화": "Automatic factor sync",
  "현재 비중 · 최초 배분 후 리밸런싱 없음": "Current weights · No rebalancing after initial allocation",
  "요인·잔차 모형 ·": "Factor–residual model ·",
  "단계": " steps",
  "미 10년물": "US 10-year yield",
  "장단기차": "Yield spread",
  "설명력 R²": "Explained variance R²",
  "결합 구간": "Aligned period",
  "· 제외된 요인 공백": "· Excluded factor gaps:",
  "개 · 요인 공분산 축소 15% · 잔차 공분산 축소 25% · 자동 대체값 없음": " · Factor covariance shrinkage 15% · Residual covariance shrinkage 25% · No automatic replacement values",
  "현재 보유종목 수익률 입력이 먼저 준비되어야 합니다.": "Holding-return inputs must be ready first.",
  "보유종목 식별자와 계산 비중의 순서가 일치하지 않습니다.": "Holding identifiers and calculation weights are in different orders.",
  "시장 요인 원자료의 날짜나 값이 유효하지 않습니다.": "Market-factor source dates or values are invalid.",
  "종목 수익률과 시장 요인이 함께 존재하는 날짜가 45개보다 적습니다.": "Fewer than 45 dates have both holding returns and market factors.",
  "요인 모형 입력의 크기나 숫자 범위가 유효하지 않습니다.": "Factor-model input dimensions or numeric ranges are invalid.",
  "요인 모형을 추정할 관측치가 부족합니다.": "There are too few observations to estimate the factor model.",
  "요인 공분산 행렬을 안정적으로 분해하지 못했습니다.": "The factor covariance matrix could not be reliably decomposed.",
  "종목별 잔차 공분산 행렬을 안정적으로 분해하지 못했습니다.": "The holding-residual covariance matrix could not be reliably decomposed.",
  "생성 경로에 유효하지 않은 숫자가 발생했습니다.": "Generated paths contain invalid numbers.",
  "생성 경로의 분포 요약을 검증하지 못했습니다.": "The generated-path distribution summary could not be verified.",
  "내 포트폴리오 확률 경로": "Your portfolio’s possible paths",
  "결과 해석·계산 근거": "Interpretation & calculation evidence",
  "확률 경로를 읽는 방법": "Reading the probabilistic paths",
  "각 시점에서 계산 경로의 아래 10%, 중앙 50%, 위 90% 경계입니다. P10~P90은 모형 안에서 약 80%의 경로가 위치하는 구간이며, 실제 미래에 대한 80% 보장 구간은 아닙니다.": "At each step, P10, P50 and P90 mark the 10th percentile, median and 90th percentile of model paths. P10–P90 contains about 80% of paths within the model; it is not an 80% guarantee for the actual future.",
  "손실 확률과 최대 낙폭": "Loss probability & maximum drawdown",
  "손실 종료 확률은 종료값이 시작값보다 작은 경로의 비율입니다. MDD는 경로 안에서 고점 대비 가장 크게 하락한 폭입니다. P90 MDD는 더 큰 손실 쪽 경계입니다.": "Terminal loss probability is the share of paths ending below their starting value. MDD is the largest peak-to-trough decline within a path. P90 MDD is the boundary toward larger losses.",
  "500개 경로 · 12개 표본": "500 paths · 12 samples",
  "최근 90개 공동 수익률을 평균 5단계 블록으로 재표본 추출합니다. 최초 배분 후 리밸런싱 없이 500개 경로를 계산하며, 차트에는 분포 또는 대표 표본 12개를 표시합니다. 표본만으로 전체 손실 확률을 판단하지 않습니다.": "Resample the latest 90 joint returns in blocks averaging five steps. Calculate 500 paths with no rebalancing after initial allocation; the chart shows the distribution or 12 representative samples. The samples alone do not determine overall loss probability.",
  "포함 범위와 가정": "Coverage & assumptions",
  "현재 평가액의": "Of current portfolio value,",
  "%가 계산 대상입니다. 제외한 비중은 이력을 꾸며내지 않고 남겨 두며, 포함 종목만 100%로 다시 환산합니다. 수수료·세금·현금수익률 미포함, 조회 시 계산 · 저장 안 함.": "% is included. Excluded weights remain visible without invented history; included holdings are renormalized to 100%. Fees, taxes and cash returns are excluded. Calculated on request and not saved.",
  "제외 · 포함 종목만 100%로 환산한 부분 포트폴리오입니다.": " excluded · A partial portfolio with included holdings renormalized to 100%.",
  "계산 비중": "Calculation weight",
  "포함 여부": "Included",
  "미확인": "Unverified",
  "수동 평가 제외": "Manual valuations excluded",
  "비중 없음": "No weight",
  "위험과 계산 근거": "Risk & calculation evidence",
  "· 입력 수익률": "· Input returns:",
  "개 · 평균 블록 5단계 · 최초 배분 후 리밸런싱 없음": " · Mean block length: 5 steps · No rebalancing after initial allocation",
  "저장된 KIS 미조정 종가·날짜별 환율 기준. 배당·액면분할 조정 총수익률이 아닙니다.": "Uses stored unadjusted KIS closes and date-specific FX. This is not dividend- or split-adjusted total return.",
  "기준일 미확인": "Reference date unverified",
  "% 포함": "% included",
  "일부 종목 제외": "Some holdings excluded",
  "계산에 필요한 근거를 확인하고 있습니다.": "Checking the evidence required for calculation.",
  "모형·데이터에서 종목별 누락과 출처를 확인할 수 있습니다. 부족한 값을 0이나 예시 경로로 대체하지 않습니다.": "Check missing data and sources by holding in Model & data. Missing values are not replaced with zeros or sample paths.",
  "단계 후 중앙 수익률": "-step median return",
  "전체 계산 경로의 중앙값 P50": "Median P50 across all calculated paths",
  "손실로 끝날 확률": "Probability of ending at a loss",
  "종료값이 시작값보다 낮은 경로 비율": "Share of paths ending below their starting value",
  "큰 하락폭 · MDD P90": "Large drawdown · MDD P90",
  "경로 내 최대 낙폭의 더 큰 손실 쪽 경계": "The larger-loss boundary of maximum drawdowns within paths",
  "하위 경계 P10": "Lower boundary P10",
  "기록 없음": "No record",
  "상위 경계 P90": "Upper boundary P90",
  "계산 경로": "Calculated paths",
  "개": "",
  "현재 구성에서 출발": "Starting from current holdings",
  "%를 포함하며, 계산 종목의 비중을 100%로 환산합니다.": "% is included, and eligible holding weights are renormalized to 100%.",
  "관측 데이터로 계산": "Calculated from observations",
  "최근 90개 공동 수익률을 재표본 추출합니다. 수수료·세금·현금수익률은 포함하지 않습니다.": "Resamples the latest 90 joint returns. Fees, taxes and cash returns are excluded.",
  "범위로 읽는 결과": "Read the range",
  "P10~P90은 모형 안의 분포입니다. 실제 미래의 보장 범위가 아니며 조회 시 계산한 연구 결과입니다.": "P10–P90 is a distribution within the model, not a guaranteed future range. This research is calculated on request.",
  "현재 평가액이나 종목 식별 입력을 먼저 확인해야 합니다.": "Review current valuations or holding identities first.",
  "기준일 형식이 올바르지 않습니다.": "The reference-date format is invalid.",
  "공통으로 사용할 수 있는 저장 기준일이 없습니다.": "No shared stored reference date is available.",
  "연구 기간은 63단계 또는 126단계만 사용할 수 있습니다.": "The research horizon must be 63 or 126 steps.",
  "과거 이력을 계산할 상장 종목이 없습니다.": "No listed holdings have usable historical data.",
  "조정주가의 출처·수집시각·종목 연결 증거가 확인된 과거 이력이 부족합니다.": "There is insufficient adjusted-price history with verified source, collection time and instrument linkage.",
  "현재 평가액 비중을 계산 비중으로 변환하지 못했습니다.": "Current valuation weights could not be converted to calculation weights.",
  "선택한 기준일에 완전한 90개 수익률 입력이 없습니다.": "The selected date does not have 90 complete return inputs.",
  "종목 구성과 저장된 수익률 행렬이 일치하지 않습니다.": "The holdings and stored return matrix do not match.",
  "연구용 현재 비중 구성을 검증하지 못했습니다.": "The current research-weight configuration could not be verified.",
  "주소에서 직접 선택": "Explicitly selected in the URL",
  "저장 이력의 최신 공통일": "Latest common date in stored history",
  "학습 구간과 확인 구간 분리": "Separate training and validation periods",
  "과거 구간 밖 검증": "Out-of-sample historical validation",
  "앞선 60개 수익률로 후보 비중을 만든 뒤, 계산에 쓰지 않은 다음 10개 수익률에서 현재 비중과 비교합니다. 시작점을 10개씩 옮겨 총 세 번 반복해 같은 90개 구간에만 맞춘 결과인지 점검합니다.": "Create candidate weights from 60 prior returns, then compare them with current weights over the next 10 unused returns. Repeat three times, moving forward by 10 observations, to check whether improvement was specific to the same 90-observation sample.",
  "과거 진단 · 추천 아님": "Historical diagnostic · Not a recommendation",
  "구간 밖 검증을 만들지 않았습니다.": "Out-of-sample validation was not calculated.",
  "비교 가능한 구간": "Comparable periods",
  "후보 변동성이 실제로 더 낮았던 구간": "Periods when the candidate’s realized volatility was lower",
  "변동성 완화 확인": "Volatility reduction observed",
  "후보 - 현재, 세 검증 구간 평균": "Candidate − current, average of three validation periods",
  "검증 변동성 차이": "Validation volatility difference",
  "누적 수익률": "Cumulative return",
  "회차": "Fold",
  "학습 구간": "Training period",
  "검증 구간": "Validation period",
  "학습 변동성": "Training volatility",
  "검증 변동성": "Validation volatility",
  "검증 수익률": "Validation return",
  "최대 낙폭": "Maximum drawdown",
  "비중 이동": "Weight turnover",
  "차": "Difference",
  "각 셀은 현재 → 후보 순서입니다. 후보는 매 회차의 학습 구간만 보고 다시 계산하며, 뒤의 검증 수익률은 비중 계산에 사용하지 않습니다.": "Each cell shows current → candidate. Candidates are recalculated using only each fold’s training data; subsequent validation returns are not used to choose weights.",
  "세 검증 구간은 서로 겹치지 않지만 학습 구간은 일부 겹칩니다. 현재 보유 비중을 과거에도 동일했다고 가정하고, 수수료·세금은 0으로 두므로 독립 실험이나 미래 성과 보장이 아닙니다.": "The three validation periods do not overlap, though training periods partly overlap. Current holdings are assumed to have existed unchanged in the past, with zero fees and taxes. These are not independent experiments or guarantees of future performance.",
  "일부 구간만 계산할 수 있습니다.": "Only some periods can be calculated.",
  "현재 포트폴리오 계산이 먼저 준비되어야 합니다.": "The current portfolio calculation must be ready first.",
  "공동 수익률 행렬이 준비되지 않았습니다.": "The joint return matrix is not ready.",
  "수익률 행렬과 현재 비중의 종목 순서가 다릅니다.": "The return matrix and current weights have different instrument orders.",
  "학습 구간과 현재 비중의 종목 순서가 다릅니다.": "The training period and current weights have different instrument orders.",
  "검증 구간의 성과를 계산하지 못했습니다.": "Validation-period performance could not be calculated.",
  "계산 가능한 검증 회차가 없습니다.": "No validation fold can be calculated.",
  "계산 가능한 종목이 하나뿐이면 비중 대안을 만들 수 없습니다.": "A weight alternative requires more than one eligible holding.",
  "제약 안에서 후보 비중을 계산하지 못했습니다.": "Candidate weights could not be calculated within the constraints.",
  "학습 구간에서 현재보다 낮은 변동성 후보를 만들지 못했습니다.": "No lower-volatility candidate was found in the training period.",
  "회전율·외화·집중도 제약을 만족하지 못했습니다.": "Turnover, FX and concentration constraints were not satisfied.",
  "시장 국면 사후 연구": "Retrospective market-regime research",
  "저장된 환율·미국 금리·장단기 금리차로 선택 기준일과 유사한 과거 구간을 찾아 교차시장 수익률 블록을 뽑습니다. 공개시각과 revision vintage가 없어 당시 예측을 재현한 결과는 아니며, 기존 stationary bootstrap의 결손을 대신하지 않습니다.": "Find historical periods resembling the selected date using stored FX, US rates and the yield spread, then sample cross-market return blocks. Without release times and revision vintages, this does not reproduce predictions available at the time or replace missing stationary-bootstrap evidence.",
  "사후 연구용 · 저장 안 함 · 추천 아님": "Retrospective research · Not saved · Not a recommendation",
  "교차시장 수익률": "Cross-market returns",
  "KODEX 200 + VOO 같은 행": "KODEX 200 + VOO in the same row",
  "국면 정렬 행": "Regime-aligned rows",
  "유사 국면 후보": "Similar-regime candidates",
  "선택 이웃 / 사용 가능 시작점": "Selected neighbors / eligible block starts",
  "실행 상태": "Execution status",
  "사용 불가": "Unavailable",
  "자동 fallback 없음": "No automatic fallback",
  "국면 조건부 경로를 계산하지 않았습니다.": "Regime-conditioned paths were not calculated.",
  "기존의 정적 부트스트랩 결과는 이 상태와 독립적으로 유지됩니다.": "Existing stationary-bootstrap results remain independent of this status.",
  "요인": "Factor",
  "최신 공개일": "Latest release date",
  "선택일 적용 공개일": "Release date applied to selection",
  "정렬 커버리지": "Alignment coverage",
  "단일 종목·직접 입력 참고 경로": "Single-instrument & custom-weight reference paths",
  "단일 종목 두 경로와 25·50·75 이외의 직접 입력 비중만 별도로 표시합니다. 고정 비중 3안과 같은 국면 상태와 추출 계획을 사용합니다.": "Show the two single-instrument paths and custom weights other than 25%, 50% and 75% separately. They use the same regime state and sampling plan as the three fixed mixes.",
  "직접 입력 비중": "Custom weights",
  "단일 종목 참고 경로": "Single-instrument reference path",
  "명시 비중 입력이 유효하지 않아 이 시나리오만 제외했습니다.": "Only this scenario was excluded because the explicit-weight input is invalid.",
  "방법: 공개일이 선택일 이전인 3개 일별 요인의 수준·20일 변동성을 robust scaling한 뒤 가까운 과거 국면을 선택합니다. 120개 완전 수익률 행, 수익률 5~20단계 연속 블록, 서비스 기준일 수익률 63단계, 500경로를 사용합니다. DB 적재시각은 과거 공개시점으로 간주하지 않습니다. 공개시각과 revision vintage가 보존되기 전에는 엄격한 시점 검증 결과로 승격하지 않습니다. 현재 보유, 계좌, Fount, 금현물, 승인 벡터, 주문 가능성은 입력에 포함하지 않습니다.": "Method: robust-scale the levels and 20-day volatility of three daily factors released before selection, then select nearby historical regimes. Uses 120 complete return rows, contiguous blocks of 5–20 return steps, a 63-step horizon and 500 paths. DB ingestion time is not historical release time. Without preserved release times and vintages, this is not strict point-in-time validation. Holdings, accounts, Fount, physical gold, approved vectors and order eligibility are excluded.",
  "기준일을 직접 선택한 뒤에만 실행합니다.": "Runs only after explicitly selecting a reference date.",
  "두 종목의 공통 수익률 입력이 완전하지 않습니다.": "The two instruments’ joint return inputs are incomplete.",
  "공통 수익률 입력이 고정 120행 규격과 다릅니다.": "The joint return input differs from the fixed 120-row specification.",
  "시장 요인 행의 날짜 또는 값 규격이 유효하지 않습니다.": "Market-factor row dates or values are invalid.",
  "선택 기준일의 시장 요인 상태가 완전하지 않습니다.": "The selected date’s market-factor state is incomplete.",
  "선택 기준일에 적용할 시장 요인이 7일보다 오래되었습니다.": "The market factors applied to the selected date are more than seven days old.",
  "수익률과 시점 기준 요인이 함께 완전한 행이 120개 미만입니다.": "Fewer than 120 rows have complete returns and point-in-time factor alignment.",
  "연속 블록을 시작할 유사 국면 후보가 20개 미만입니다.": "Fewer than 20 similar-regime candidates can start contiguous blocks.",
  "국면 거리를 계산할 유효한 변동 요인이 부족합니다.": "There are too few varying factors to calculate regime distances.",
  "수익률 행에 재표본할 수 없는 값이 있습니다.": "Return rows contain values that cannot be resampled.",
  "국면 조건부 블록 추출 계획을 만들지 못했습니다.": "A regime-conditioned block-sampling plan could not be created.",
  "경로 계산 중 수치 검증을 통과하지 못했습니다.": "Numerical validation failed during path calculation.",
  "없음": "None",
  "국면별 고정 비중 3안 공통 경로": "Three regime-conditioned mixes on common paths",
  "25:75, 50:50, 75:25를 같은 시장 상태·과거 후보·500개 추출 계획으로 계산합니다. 최초 배분 뒤에는 리밸런싱하지 않아 종목별 등락에 따른 비중 변화를 그대로 둡니다.": "Calculate 25:75, 50:50 and 75:25 using the same market state, historical candidates and 500 sampling plans. After initial allocation, weights drift with returns without rebalancing.",
  "비중 순서 · 성과 순위·추천 아님": "Ordered by weight · Not a ranking or recommendation",
  "세 고정 비중을 함께 비교하지 않았습니다.": "The three fixed mixes were not compared together.",
  "공통 국면 실행 근거를 검증하지 못했습니다. 단일 종목이나 직접 입력한 비중의 독립 결과는 준비된 경우 그대로 유지합니다.": "The common regime-execution evidence could not be verified. Available independent single-instrument and custom-weight results remain visible.",
  "세 그래프는 하나의 세로축을 사용합니다. 카드는 KODEX 200 비중이 낮은 순서이며, 수익률이나 위험의 우열 순서가 아닙니다. stationary bootstrap 결과와 합산하거나 승패를 판정하지 않습니다.": "All charts share a vertical axis. Cards are ordered by ascending KODEX 200 weight, not by return or risk. Results are not combined with stationary bootstrap or used to select a winner.",
  "국면 사후 연구 · KODEX 200 : VOO": "Retrospective regime research · KODEX 200 : VOO",
  "시장 국면 모델 과거 결과 대조": "Market-regime model versus historical outcomes",
  "과거 각 기준일에서 이전 120개 수익률과 당시까지 공개된 시장 요인만 사용해 분포를 만든 뒤, 실제 다음 63개 서비스 기준일 결과와 비교합니다.": "At each historical reference date, build a distribution using the preceding 120 returns and market factors released by that time, then compare with the next 63 observed service-date outcomes.",
  "고정 연구 시나리오: KODEX 200 50% + VOO 50%, 최초 배분 후 리밸런싱 없음": "Fixed research scenario: KODEX 200 50% + VOO 50%, with no rebalancing after initial allocation",
  "사후 연구": "Retrospective research",
  "시점 증거 미확립": "Point-in-time evidence unestablished",
  "계산 가능한 기준일": "Calculable reference dates",
  "겹치는 구간이므로 독립 표본 아님": "Overlapping windows are not independent samples",
  "P10-P90 포함": "P10–P90 coverage",
  "예측 중앙값과 실제 종료 수익률 차이": "Difference between predicted median and observed terminal return",
  "평균 절대 오차": "Mean absolute error",
  "각 기준일의 경로 중 종료 손실 비율 평균": "Average terminal-loss share across paths at each reference date",
  "예측 손실 확률": "Predicted loss probability",
  "연구 기준일": "Research date",
  "예측 P10-P90": "Predicted P10–P90",
  "예측 P50": "Predicted P50",
  "실제 MDD / 예측 P90": "Observed MDD / predicted P90",
  "예측 구간 안": "Within predicted range",
  "예측 구간 밖": "Outside predicted range",
  "계산 불가": "Unavailable",
  "검증할 명시적 기준일과 입력 행이 아직 준비되지 않았습니다.": "Explicit reference dates and validation inputs are not ready.",
  "공개 시각과 과거 데이터 revision 이력이 현재 DB에 보존되지 않아 이 결과는 엄격한 과거 시점 재현이 아닙니다. 서로 겹치는 7개 구간은 독립 표본으로 세지 않으며, 합격 판정이나 모델 순위, 현재 보유 종목 추천에 사용하지 않습니다. 한 기준일의 입력이 비어 있으면 그 행만 계산 불가로 남기고 다른 결과는 유지합니다.": "Precise release times and historical revision vintages are not preserved, so this is not a strict point-in-time reconstruction. The seven overlapping windows are not independent samples and are not used for pass/fail judgments, model rankings or recommendations for current holdings. A missing input blocks only that date; other results remain visible.",
  "가격·환율 수익률 행이 부족합니다.": "There are too few price/FX return rows.",
  "입력 행의 날짜 또는 종목 구성이 다릅니다.": "Input row dates or instruments differ.",
  "시장 요인 행 형식이 올바르지 않습니다.": "Market-factor row formats are invalid.",
  "연구 기준일의 시장 요인 상태가 불완전합니다.": "The research date’s market-factor state is incomplete.",
  "연구 기준일의 시장 요인이 허용 기간보다 오래됐습니다.": "The research date’s market factors are older than policy allows.",
  "수익률과 시장 요인이 함께 있는 과거 행이 부족합니다.": "Too few historical rows contain both returns and market factors.",
  "비슷한 과거 국면 후보가 부족합니다.": "There are too few similar historical regime candidates.",
  "시장 국면을 구분할 수 있는 요인 변화가 부족합니다.": "Factor variation is insufficient to distinguish market regimes.",
  "수익률 행에 유효하지 않은 값이 있습니다.": "Return rows contain invalid values.",
  "국면 조건부 추출 계획을 만들지 못했습니다.": "A regime-conditioned sampling plan could not be created.",
  "분포 계산을 완료하지 못했습니다.": "The distribution calculation could not be completed.",
  "이후 실제 결과 경로를 계산할 수 없습니다.": "The subsequent observed-outcome path could not be calculated.",
  "필요한 검증 근거가 부족합니다.": "Required validation evidence is missing.",
  "체제 데이터 시점 검증": "Regime-data point-in-time checks",
  "선택 기준일과 직전 6개 서비스 날짜를 독립적으로 점검합니다. 날짜를 자동으로 되돌리지 않으며, 사후 연구 가능 여부와 당시 실제 이용 가능성이 입증됐는지를 분리합니다.": "Check the selected date and six preceding service dates independently. Dates are not moved backward automatically. Retrospective research readiness is separated from proven availability at the historical time.",
  "엄격한 시점 검증 미확립": "Strict point-in-time validation unestablished",
  "검사 날짜": "Dates checked",
  "선택일 포함 최근 서비스 날짜": "Recent service dates including selection",
  "사후 연구 가능": "Retrospective research ready",
  "공개일 기반 계산 준비도": "Readiness based on release dates",
  "시점 안전 날짜": "Point-in-time-safe dates",
  "공개시각과 vintage 입증 기준": "Requires verified release times and vintages",
  "자동 날짜 대체": "Automatic date fallback",
  "사용 안 함": "Disabled",
  "선택한 날짜를 그대로 판정": "Assess the selected date exactly",
  "현재 import만으로 당시 공개 상태를 증명할 수 없습니다.": "The current import alone cannot prove historical release availability.",
  "factor별 공개 날짜는 보존됐지만 공개 시각과 revision vintage는 보존되지 않았습니다. 같은 날짜 공개값은 다음 서비스 날짜부터만 사후 연구에 사용하며, 아래 결과를 당시 알 수 있었던 예측이나 추천으로 해석하지 않습니다.": "Factor release dates are preserved, but release times and revision vintages are not. Same-date releases enter retrospective research only from the next service date. These results are not predictions or recommendations proven knowable at that time.",
  "적용 공개일": "Applied release date",
  "정렬 상태": "Alignment status",
  "후보 상태": "Candidate status",
  "엄격한 시점 검증": "Strict point-in-time check",
  "선택일": "Selected date",
  "공개시각·vintage 없음": "Release time / vintage missing",
  "기준일을 직접 선택하면 최근 날짜별 준비도를 검사합니다.": "Explicitly select a reference date to inspect readiness across recent dates.",
  "현재 보존된 provenance로 입증된 날짜가 없습니다.": "No date is proven safe by currently preserved provenance.",
  "적용값 없음": "No applicable value",
  "사용 불가 ·": "Unavailable ·",
  "기준일 필요": "Reference date required",
  "공통 수익률 부족": "Insufficient joint returns",
  "입력 규격 불일치": "Input specification mismatch",
  "factor 행 오류": "Invalid factor rows",
  "현재 factor 불완전": "Current factors incomplete",
  "현재 factor 오래됨": "Current factors stale",
  "정렬 상태 부족": "Insufficient alignment",
  "후보 상태 부족": "Insufficient candidates",
  "유효 factor 변화 부족": "Insufficient factor variation",
  "현재 입력": "Current input",
  "연구 종목 데이터 점검": "Research-instrument data checks",
  "계정과 연결하지 않은 연구 입력입니다. 저장된 가격·환율·출처만 확인하며 시뮬레이션은 실행하지 않습니다.": "Research inputs unconnected to accounts. Checks stored prices, FX and sources without running a simulation.",
  "실행 권한 미확립": "Execution authority unestablished",
  "연구 종목과 비중": "Research instruments & weights",
  "데이터 점검": "Check data",
  "Fount는 managed:KRW:FOUNT:0, 금현물은 krx-gold:KRW:GOLD_9999_1KG:0 형식으로 남길 수 있습니다. 0bps 행도 삭제하지 않습니다.": "Fount may remain as managed:KRW:FOUNT:0 and physical gold as krx-gold:KRW:GOLD_9999_1KG:0. Zero-bps rows are retained.",
  "입력 비중": "Input weights",
  "저장 커버리지 충족": "Stored coverage satisfied",
  "출처 요건 충족": "Source requirements satisfied",
  "비중": "Weight",
  "저장 이력": "Stored history",
  "환율": "FX",
  "출처 근거": "Source evidence",
  "판정": "Assessment",
  "해당 없음": "Not applicable",
  "불필요": "Not required",
  "provider 없음": "No provider",
  "완전": "Complete",
  "일부만 확인": "Partially verified",
  "연결 충돌": "Linkage conflict",
  "이력 없음": "No history",
  "불완전": "Incomplete",
  "별도 실행 검토 가능": "Eligible for separate execution review",
  "Fount 제외": "Fount excluded",
  "금현물 수동 이력 필요": "Physical gold requires manual history",
  "특수 종목 식별 불일치": "Special-instrument identity mismatch",
  "0% 행 보존": "Zero-weight row retained",
  "선택한 종목의 저장 증거가 충족됐습니다. 이는 시뮬레이션 실행, 추천 또는 provider 이용 권한 승인이 아닙니다.": "Stored evidence requirements are met for the selected instruments. This does not authorize simulation execution, recommendations or provider use.",
  "일부 종목의 증거가 부족합니다. 준비된 종목의 진단은 유지하지만 비중을 다시 나누거나 전체 포트폴리오 결과로 표시하지 않습니다.": "Some instruments lack evidence. Diagnostics for ready instruments remain, but weights are not redistributed and results are not presented as the whole portfolio.",
  "진단만 표시합니다. 이 입력으로 포트폴리오 결과를 생성하지 않습니다.": "Diagnostics only. These inputs do not generate a portfolio result.",
  "연구 종목 값은 한 번만 입력해야 합니다": "Research instruments must be entered exactly once",
  "입력 길이가 제한을 초과했습니다": "Input exceeds the length limit",
  "연구 종목을 입력해야 합니다": "Enter research instruments",
  "종목은 최대 16개까지 입력할 수 있습니다": "A maximum of 16 instruments is allowed",
  "각 행은 market:currency:ticker:weight_bps 형식이어야 합니다": "Each row must use market:currency:ticker:weight_bps",
  "market 값이 올바르지 않습니다": "The market value is invalid",
  "통화는 KRW 또는 USD여야 합니다": "Currency must be KRW or USD",
  "ticker 값이 올바르지 않습니다": "The ticker value is invalid",
  "비중은 0~10000의 정수 bps여야 합니다": "Weight must be an integer from 0 to 10000 bps",
  "같은 종목이 중복됐습니다": "An instrument is duplicated",
  "전체 비중 합계는 10000bps여야 합니다": "Total weights must equal 10000 bps",
  "고정 종목의 연구 입력을 읽지 못했습니다. 준비된 보유 구성의 분석 결과는 계속 확인할 수 있습니다.": "Fixed-instrument research inputs could not be read. Available analysis of your holdings remains visible.",
  "예측 범위와 실제 결과": "Model range & observed outcomes",
  "보유 구성의 과거 시점별 결과 대조": "Historical outcome checks for current holdings",
  "고정 종목의 과거 검증": "Fixed-instrument historical validation",
  "분포 구간·하방 위험·시점별 안정성": "Distribution bands, downside risk & stability over time",
  "시장 국면 모델 검증": "Market-regime validation",
  "시장 조건별 분포와 실제 결과": "Conditional distributions and observed outcomes",
  "블록 재표본 추출과 환율·금리 요인 모형": "Block bootstrap and FX/rate factor models",
  "모형 보정과 시장 국면": "Model calibration & market regimes",
  "과거 검증·시장 조건별 연구": "Historical validation and market-condition research",
  "고정 종목 연구와 데이터 근거": "Fixed-instrument research & data evidence",
  "KODEX 200·Vanguard S&P 500 ETF 독립 연구": "Independent KODEX 200 and Vanguard S&P 500 ETF research",
  "검사 요약": "Readiness summary",
  "검사 기준일": "Check date",
  "검사 범위": "Check scope",
  "준비된 연구 입력": "Ready research inputs",
  "실행 안 함": "Not executed",
  "연구용 · 저장 안 함": "Research only · Not saved",
  "독립 연구 입력": "Independent research inputs",
  "두 종목은 서로 독립적으로 검사합니다. 현재 보유 종목, 기본 포트폴리오, 목표 비중 또는 승인된 실행 벡터로 해석하지 않습니다. 결손이 있으면 과거 날짜로 자동 대체하거나 범위를 임의로 줄이지 않습니다. VOO는 투자 랩의 가격수익률 준비 상태를 재사용하지 않고 별도의 조정종가·환율 증거를 검사합니다.": "The two instruments are checked independently. They do not represent current holdings, a default portfolio, target weights or an approved execution vector. Missing evidence does not trigger date fallback or a shorter period. VOO independently checks adjusted-close and FX evidence rather than reusing the Investment Lab’s price-return readiness.",
  "최근 기준일 검사": "Recent reference-date checks",
  "저장된 실행 기록이 아니라, 최근 7개 기준일을 현재 저장 증거로 다시 검사한 결과입니다.": "These are fresh checks of the latest seven reference dates against currently stored evidence, not saved execution records.",
  "날짜 자동 대체 없음": "No automatic date fallback",
  "검사": "Check",
  "선택됨": "Selected",
  "현재 결과": "Current result",
  "이 날짜 검사": "Check this date",
  "준비됨": "Ready",
  "커버리지 없음": "No coverage",
  "가격 기준": "Price basis",
  "환율 기준": "FX basis",
  "요청 종료일": "Requested end date",
  "확정 종료일": "Confirmed end date",
  "관측 범위": "Observation range",
  "기간 축": "Period axis",
  "가격 커버리지": "Price coverage",
  "환율 커버리지": "FX coverage",
  "수익률 행 커버리지": "Return-row coverage",
  "자동 재시도·날짜 대체": "Automatic retry / date fallback",
  "증거 결손": "Evidence gaps",
  "확인할 항목": "Items to review",
  "확인된 결손이 없습니다.": "No verified gaps.",
  "최근 관측 기준일": "Latest observed reference date",
  "로 다시 검사": ": check again",
  "검사 전": "Not checked",
  "관측 없음": "No observations",
  "경로 표시": "Path display",
  "분포 구간": "Distribution band",
  "표본 경로": "Sample paths",
  "차트 단위": "Chart units",
  "수익률": "Return",
  "시작값 100": "Starting value 100",
  "· 선택됨": "· Selected",
  "분포의 세 지점": "Three distribution points",
  "표시할 확률 경로가 없습니다.": "No probabilistic paths are available to display.",
  "표본 경로 선택": "Select a sample path",
  "표본": "Sample",
  "중앙값 P50": "Median P50",
  "P10~P90 · 모형 내 80% 구간": "P10–P90 · 80% interval within the model",
  "개 · 연구 분포, 수익 보장 아님": " paths · Research distribution, not a return guarantee",
  "시뮬레이션": "Simulation",
  "계산 조건": "Calculation settings",
  "시뮬레이션 계산 조건": "Simulation calculation settings",
  "내 포트폴리오는 저장 이력의 최신 공통 기준일을 사용합니다. 기준일을 지정하면 그 날짜를 정확히 적용하며, 누락된 이력을 임의로 채우지 않습니다.": "Your portfolio uses the latest shared reference date in stored history. An explicit date is applied exactly; missing history is not invented.",
  "현재 구성과 최근 90개 공동 수익률로 연구 경로를 계산합니다. 현재 보유 수량의 과거 기록을 재현하는 백테스트가 아닙니다.": "Research paths use the current holdings and latest 90 joint returns. This is not a backtest reconstructing historical records of your current quantities.",
  "기간은 수익률 관측 단계입니다. 시장 국면 모델은 별도로 63단계를 사용합니다. 고정 종목 연구는 직접 지정한 기준일로만 실행합니다.": "The horizon counts return-observation steps. The market-regime model separately uses 63 steps. Fixed-instrument research runs only with an explicitly selected date.",
  "기준일은 하나의 YYYY-MM-DD 값으로 입력해야 합니다. 계산 조건에서 날짜를 확인해 주세요.": "Enter a single reference date in YYYY-MM-DD format. Review the date in Calculation settings.",
  "연구 기간은 63 또는 126단계만 가능합니다. 잘못된 값을 기본 기간으로 대체하지 않았습니다.": "The research horizon must be 63 or 126 steps. An invalid value has not been replaced with the default horizon.",
  "현재 구성 기준 연구 · 수수료·세금·현금수익률 미포함 · 결과는 수익 보장, 추천 또는 주문 근거가 아닙니다.": "Research based on current holdings · Excludes fees, taxes and cash returns · Results are not return guarantees, recommendations or order instructions.",
  "연구 기간 선택": "Select research horizon",
  "연구 기간": "Research horizon",
  "검증 시작": "Start validation",
  "개 관측 후": " observations later",
  "적용": "Apply",
  "최신 공통 기준일": "Latest common reference date",
  "읽지 못한 근거:": "Unread evidence:",
  ". 준비된 결과는 아래에 표시합니다.": ". Available results are shown below.",
  "분석 결과를 표시할 수 없습니다": "This analysis could not be displayed",
  "이 분석만 불러오지 못했습니다. 다른 분석 결과는 계속 확인할 수 있습니다.": "Only this analysis failed to load. Other analysis results remain available.",
  "다시 시도": "Try again",
  "중앙 경로 수익률": "Median path return",
  "P5 종료수익률": "P5 terminal return",
  "종료수익률 하위 5% 평균": "Mean of the lowest 5% of terminal returns",
  "손실 종료 확률": "Probability of ending at a loss",
  "MDD 중앙값": "Median MDD",
  "MDD P90 (더 큰 손실)": "MDD P90 (larger loss)",
  "상세 분석을 불러오고 있습니다.": "Loading detailed analysis.",
  "비중 실험": "Weight experiments",
  "구성을 조정했을 때 분포와 위험의 차이를 비교합니다.": "Compare changes in distributions and risk after adjusting the holdings.",
  "과거 검증": "Historical validation",
  "과거 구간 밖에서 실제 결과와 모형의 예측을 대조합니다.": "Compare observed outcomes with model projections outside the training period.",
  "모형·데이터": "Model & data",
  "포함 종목과 데이터 누락, 모형의 가정을 확인합니다.": "Review included holdings, missing data and model assumptions.",
  "현재 보유 구성 · 연구 분포": "Current holdings · Research distribution",
  "시뮬레이션 상세": "Simulation details",
  "닫기": "Close",
  "사후 검증 연구 · 계좌 및 목표비중과 무관": "Retrospective validation · Unconnected to accounts and target weights",
  "워크포워드 최소변동성 연구": "Walk-forward minimum-volatility research",
  "KODEX 200과 VOO의 공동 원화 수익률만 사용합니다. 직전 60개 관측으로 비중을 계산하고 다음 10개 관측에만 적용하는 과정을 3번 반복합니다.": "Uses only joint KRW returns for KODEX 200 and VOO. Estimate weights from 60 preceding observations and apply them only to the next 10; repeat three times.",
  "미래 예측·추천 아님": "Not a forecast or recommendation",
  "이 연구 경로만 계산할 수 없습니다.": "Only this research path is unavailable.",
  "기존 단일 종목, 고정 비중, stationary bootstrap 및 시장 국면 결과는 그대로 유지합니다.": "Existing single-instrument, fixed-weight, stationary-bootstrap and market-regime results remain available.",
  "마지막 30개 공동 관측": "Latest 30 joint observations",
  "검증구간 수익률": "Validation return",
  "검증구간 연환산 변동성": "Annualized validation volatility",
  "관측 기준 MDD": "Observed MDD",
  "음수면 50:50보다 낮음": "Negative means lower than 50:50",
  "변동성 차이": "Volatility difference",
  "워크포워드 최소변동성과 같은 주기 50대50의 검증구간 누적지수 비교": "Validation-period cumulative index: walk-forward minimum volatility versus 50:50 rebalanced on the same schedule",
  "구간": "Period",
  "학습기간": "Training period",
  "검증기간": "Validation period",
  "학습 추정 변동성": "Estimated training volatility",
  "long-only·100% 투자, 10개 관측마다 비용 없이 재조정하고 구간 안에서는 비중 변화를 그대로 둡니다. 표본 공분산은 10% 대각 축소를 적용합니다. 거래비용·세금·환전비용은 0으로 가정하며 VOO의 원화 수익률에는 저장된 일자별 환율 변동이 이미 포함됩니다.": "Long-only and fully invested. Rebalance without costs every 10 observations, allowing weights to drift within each period. Sample covariance uses 10% diagonal shrinkage. Trading costs, taxes and FX fees are assumed zero; VOO’s KRW returns already include stored daily exchange-rate changes.",
  "기준일을 직접 선택한 경우에만 계산합니다.": "Calculated only after explicitly selecting a reference date.",
  "두 종목의 같은 날짜축 90개 수익률이 모두 준비되지 않았습니다.": "The two instruments do not have all 90 returns on a shared date axis.",
  "입력 기간 또는 종목 구성이 069500·VOO 공동 연구 규격과 다릅니다.": "The input period or instruments do not match the joint 069500–VOO research specification.",
  "사용할 수 없는 공동 수익률이 포함되어 있습니다.": "The joint returns include unusable values.",
  "학습 공분산 또는 검증 경로를 안정적으로 계산하지 못했습니다.": "Training covariance or validation paths could not be calculated reliably.",
  "같은 정책 반복 점검 · 겹치는 기간": "Repeated policy checks · Overlapping periods",
  "워크포워드 기준일 안정성": "Walk-forward date stability",
  "선택 기준일과 직전 6개 날짜에 같은 60/10/3 정책을 독립적으로 적용합니다. 날짜에 따라 결과가 크게 달라지는지 확인하는 진단이며, 가장 좋은 날짜나 설정을 고르는 기능이 아닙니다.": "Independently apply the same 60/10/3 policy to the selected date and six preceding dates. This checks sensitivity to the reference date; it does not select the best date or settings.",
  "개 계산 가능": " dates calculable",
  "누락 날짜만 사용 불가로 유지": "Only missing dates remain unavailable",
  "안정성 이력을 계산하지 않았습니다.": "Stability history was not calculated.",
  "기존 단일 기준일 연구 결과는 그대로 유지합니다.": "Existing single-date research results remain available.",
  "7개 검증창은 대부분의 학습·검증 수익률을 공유하므로 서로 독립된 7번의 실험이 아닙니다. 이 표를 이용해 학습기간, 10% 대각 축소, 재조정 주기를 다시 선택하거나 성과 순위를 만들지 않습니다.": "The seven windows share most training and validation returns, so they are not seven independent experiments. Do not use this table to reselect the training period, 10% diagonal shrinkage or rebalancing interval, or to rank performance.",
  "50:50 변동성": "50:50 volatility",
  "관측 MDD": "Observed MDD",
  "KODEX 비중 3구간": "KODEX weights across 3 folds",
  "URL에서 하나의 기준일을 직접 선택해야 합니다.": "Select exactly one reference date explicitly in the URL.",
  "요청한 7개 기준일 구성이 정책과 다릅니다.": "The requested seven-date configuration does not match policy.",
  "일부 기준일의 공동 수익률이 부족합니다.": "Some reference dates have insufficient joint returns.",
  "모든 기준일의 공동 수익률이 부족합니다.": "All reference dates have insufficient joint returns.",
  "이 날짜의 공동 수익률 행렬이 완전하지 않습니다.": "This date’s joint return matrix is incomplete.",
  "이 날짜의 행렬 규격이 정책과 다릅니다.": "This date’s matrix dimensions do not match policy.",
  "이 날짜에 사용할 수 없는 수익률이 있습니다.": "This date contains unusable returns.",
  "이 날짜의 비중 또는 검증 경로를 계산하지 못했습니다.": "This date’s weights or validation path could not be calculated.",
  "확인되지 않은 결손이 있습니다.": "There is an unidentified evidence gap.",
  "확률 경로를 계산하고 있습니다.": "Calculating probabilistic paths."
};

type CopyRule = readonly [RegExp, (...parts: string[]) => string];
const COPY_RULES: readonly CopyRule[] = [
  [/^(\d+)개 행 계산 불가$/, n => `${n} rows unavailable`],
  [/^실제 종료 손실 ([\d/]+)개$/, n => `Observed terminal losses ${n}`],
  [/^([\d/]+)개 실제 결과 포함$/, n => `${n} observed outcomes included`],
  [/^(\d+)회$/, n => `${n} times`],
  [/^(\d+)일$/, n => `${n} days`],
  [/^정책 (\d+)일$/, n => `Policy: ${n} days`],
  [/^(\d+)개$/, n => n],
  [/^(.+)의 과거 (\d+)개 KRW 단순수익률 차트$/, (ticker, n) => `${ticker}: chart of ${n} historical simple KRW returns`],
  [/^(.+) 과거 KRW 단순수익률$/, ticker => `${ticker}: historical simple KRW returns`],
  [/^상한 (.+)$/, n => `Limit ${n}`],
  [/^실제 손실 종료 ([\d/]+)개$/, n => `Observed loss endings ${n}`],
  [/^(\d+)개 보유 행에서 집계$/, n => `Aggregated from ${n} holding rows`],
  [/^수동 이력 필요 (.+)$/, n => `Manual history required ${n}`],
  [/^([\d,.+-]+)원$/, n => `${n} KRW`],
  [/^저장 이력으로 구성한 (\d+)개 중 비교 가능 · 최대 (\d+)개$/, (n, max) => `Comparable among ${n} windows from stored history · Maximum ${max}`],
  [/^부트 (.+) · 요인 (.+)$/, (bootstrap, factor) => `Bootstrap ${bootstrap} · Factor ${factor}`],
  [/^(\d+)개 중 (\d+)개$/, (total, n) => `${n} of ${total}`],
  [/^전체 (\d+)개 중$/, n => `Out of ${n} total`],
  [/^부족 (\d+)개$/, n => `Shortfall ${n}`],
  [/^(\d+)개 계산 불가$/, n => `${n} unavailable`],
  [/^(\d+)개 검증 수익률 연결$/, n => `${n} validation returns joined`],
  [/^공개일 기준 · 최대 (\d+)일$/, n => `Release-date basis · Maximum ${n} days`],
  [/^([\d/]+) 계산 완료$/, n => `${n} calculated`],
  [/^(.+) · (\d+)일 적용$/, (date, n) => `${date} · Carried ${n} days`],
  [/^전체 (\d+)개 기준일$/, n => `${n} reference dates in total`],
  [/^(.+) · (\d+)일 경과$/, (date, n) => `${date} · ${n} days old`],
  [/^([\d/]+)행 · (.+)$/, (rows, provider) => `${rows} rows · ${provider}`],
  [/^(\d+)개 수익률$/, n => `${n} returns`],
  [/^(\d+)개 관측점 필요$/, n => `${n} observation points required`],
  [/^(\d+)개 확인 필요$/, n => `${n} need review`],
  [/^([\d/]+) 수익률 행$/, n => `${n} return rows`],
  [/^([\d/\-]+) 관측점$/, n => `${n} observation points`],
  [/^(\d+)단계$/, n => `Step ${n}`],
  [/^표본 (\d+)( · 선택됨)?$/, (n, selected) => `Sample ${n}${selected ? " · Selected" : ""}`],
  [/^(.+) 연구 시뮬레이션 경로와 P10 P50 P90 구간$/, name => `${name}: research paths and P10, P50, P90 bands`],
  [/^(.+) 확률 분포$/, name => `${name}: probability distribution`],
  [/^표본 경로 (\d+) 선택$/, n => `Select sample path ${n}`],
  [/^(.+) 경로 시점$/, name => `${name}: path step`],
  [/^(\d+)단계, 중앙값 (.+)$/, (n, value) => `Step ${n}, median ${value}`],
];

export function simulationEnglish(text: string): string {
  const normalized = text.replace(/\s+/g, " ").trim();
  if (!/[가-힣]/.test(normalized)) return text;
  const exact = SIMULATION_COPY[normalized] ?? SIMULATION_EXTRA_COPY[normalized];
  if (exact !== undefined) return exact;
  for (const [pattern, render] of COPY_RULES) {
    const match = normalized.match(pattern);
    if (match) return render(...match.slice(1));
  }
  if (normalized.includes(" · ")) return normalized.split(" · ").map(simulationEnglish).join(" · ");
  return text;
}
const SIMULATION_EXTRA_COPY: Readonly<Record<string, string>> = {
  "한국": "Korea", "미국": "United States", "워크포워드 최소변동성": "Walk-forward minimum volatility", "동일 주기 50:50": "50:50, matching rebalance schedule",
  "검사 기준일 형식이 올바르지 않습니다.": "The check-date format is invalid.",
  "수익률 관측 수 설정이 올바르지 않습니다.": "The return-observation count is invalid.",
  "검사할 연구 입력이 없습니다.": "No research inputs are available to check.",
  "종목 식별 정보가 올바르지 않습니다.": "The holding identity is invalid.",
  "지원하지 않는 통화입니다.": "The currency is unsupported.",
  "같은 종목 입력이 중복되었습니다.": "An instrument input is duplicated.",
  "가격 관측 날짜가 올바르지 않습니다.": "A price-observation date is invalid.",
  "조정종가가 아닌 가격 필드가 포함되었습니다.": "A non-adjusted-close price field is included.",
  "조정종가 값이 올바르지 않습니다.": "An adjusted-close value is invalid.",
  "같은 날짜의 가격 행이 중복되었습니다.": "Price rows are duplicated for a date.",
  "환율 관측 날짜가 올바르지 않습니다.": "An FX-observation date is invalid.",
  "사용할 수 없는 환율 상태입니다.": "The FX status is unusable.",
  "환율 값이 올바르지 않습니다.": "An FX rate is invalid.",
  "같은 날짜의 환율 행이 중복되었습니다.": "FX rows are duplicated for a date.",
  "요청한 기준일의 시장 관측값이 없습니다.": "The requested date has no market observations.",
  "필요한 관측 기간이 부족합니다.": "The observation period is too short.",
  "종목 가격 이력을 찾지 못했습니다.": "Instrument price history was not found.",
  "USD/KRW 환율 이력을 찾지 못했습니다.": "USD/KRW history was not found.",
  "수익률 계산에 필요한 기준일 수가 부족합니다.": "There are too few reference dates to calculate returns.",
  "기준일 값이 올바르지 않습니다.": "A reference-date value is invalid.",
  "기준일이 중복되었습니다.": "Reference dates are duplicated.",
  "기준일 순서가 올바르지 않습니다.": "Reference dates are in the wrong order.",
  "연구 입력 종목이 중복되었습니다.": "Research instruments are duplicated.",
  "종목 이력 상태가 올바르지 않습니다.": "The holding-history status is invalid.",
  "가격 행의 종목 식별 정보가 일치하지 않습니다.": "A price row has a mismatched holding identity.",
  "수익률 계산 결과가 유효하지 않습니다.": "A calculated return is invalid.",
  "일부 기준일의 가격 증거가 없습니다.": "Price evidence is missing on some reference dates.",
  "일부 가격 증거가 허용 기간보다 오래되었습니다.": "Some price evidence is older than policy allows.",
  "일부 기준일의 환율 증거가 없습니다.": "FX evidence is missing on some reference dates.",
  "일부 환율 증거가 허용 기간보다 오래되었습니다.": "Some FX evidence is older than policy allows.",
  "종목별 가격 이력을 사용할 수 없습니다.": "Holding price histories are unavailable.",
  "시장 식별 정보가 올바르지 않습니다.": "The market identity is invalid.",
  "종목 코드가 없습니다.": "The ticker is missing.",
  "검사 대상 종목의 축 증거가 없습니다.": "Date-axis evidence is missing for a research instrument.",
  "검사 대상 종목의 행렬 증거가 없습니다.": "Matrix evidence is missing for a research instrument.",
  "수익률 행렬 준비 조건을 충족하지 못했습니다.": "The return matrix does not meet readiness requirements.",
  "완전한 관측 수익률 상세를 만들 수 없습니다.": "Complete observed-return details could not be produced.",
  "확인되지 않은 데이터 결손이 있습니다.": "There is an unidentified data gap."
};
