import { commonEnglish, translationEntry } from "./locale";
import {translateManagementActionCopy} from "./management-action-copy";

export const managementEnglish: Readonly<Record<string,string>> = {
  "계좌 범위":"Account scope", "결과 둘러보기":"Explore results", "상태 확인 불가":"Status unavailable", "가격":"Price", "일":" days", "가능":"Available", "준비 중":"Preparing", "· 추세":"· Trend",
  "가격 확인 중":"Checking prices", "과거 가격 준비":"Prepare price history", "분석 준비 완료":"Ready for analysis", "과거 가격 없음":"No price history", "최신 가격 보완 필요":"Latest price needed", "일부 분석 가능":"Some analysis available", "수동 평가 기록 사용":"Using recorded manual valuations", "투자랩·시뮬레이션 제외":"Excluded from Lab and Simulation", "분석 범위 확인 필요":"Analysis scope needs review", "자동 가격 준비 미지원":"Automatic price preparation unsupported",
  "과거 가격 준비 상태를 읽지 못했습니다. 기존 계산 결과는 변경하지 않았습니다.":"Price history readiness could not be read. Existing calculation results remain unchanged.", "부족한 과거 가격 준비":"Prepare missing price history",
  "결과 전체를 숨기지 않고 준비된 범위는 그대로 보여줍니다. 아래 버튼은 선택한 종목만 KIS에서 조회하며, 임의 평균값으로 과거 가격을 만들지 않습니다.":"Available results remain visible. The button retrieves only the selected holding from KIS. Missing historical prices are never filled with assumed averages.",
  "티커 없음":"No ticker", "보유 종료":"Close holding", "종료 메모 (선택)":"Closure note (optional)", "예: 전량 매도 후 보유 종료":"e.g. Closed after selling the entire position", "현재 계산에서 제외하되 수량·매입원가·과거 기록은 보존합니다.":"Exclude from current calculations while preserving quantity, cost basis and historical records.", "종료 중":"Closing", "복원 메모 (선택)":"Restoration note (optional)", "복원 중":"Restoring", "보유 복원":"Restore holding",
  "보유 계좌":"Holding account", "계좌 선택":"Select an account", "기존 분석 범위":"Existing analysis scope", "새 분석 범위 사용":"Use a new scope", "새 분석 범위 이름":"New scope name", "기존 분석 범위를 선택했다면 비워 두세요":"Leave empty if you selected an existing scope", "기존 분석 범위 선택 또는 새 범위 이름 중 하나만 사용합니다.":"Choose an existing scope or enter a new name, not both.",
  "상장 시장":"Listed market", "종목 유형":"Instrument type", "티커":"Ticker", "종목명 (선택)":"Holding name (optional)", "비우면 등록된 종목명 또는 티커 사용":"Leave empty to use the registered name or ticker", "보유 수량":"Quantity held", "1좌당 매입 원가 (":"Cost per unit (", "손익 계산의 기준 원가입니다.":"The cost basis used to calculate profit and loss.", "현재 1좌 가격 (":"Current price per unit (", ", 선택)":", optional)", "비우면 최신 저장 가격을 사용합니다.":"Leave empty to use the latest recorded price.", "증권사 표시 수익률 (%, 선택)":"Brokerage return (%, optional)", "검산용으로만 보존하며 손익 계산에는 사용하지 않습니다.":"Saved for cross-checking only; not used to calculate profit and loss.", "저장 중":"Saving", "보유종목 저장":"Save holding",
  "수량·평균매입가 정정":"Correct quantity and average cost", "현재 보유 수량":"Current quantity", "1좌당 평균 매입가 (":"Average cost per unit (", "평균 매입가 입력":"Enter average cost", "정정 사유 (선택)":"Correction reason (optional)", "예: 최초 입력 수량 오기":"e.g. Incorrect quantity entered initially", "오입력 정정 전용입니다. 매수·매도 거래나 현금 흐름으로 기록되지 않습니다.":"For data corrections only. This is not recorded as a buy, sell or cash flow.", "정정 중":"Correcting", "현재 상태 정정":"Correct current position",
  "1g 평가액 (KRW)":"Value per gram (KRW)", "수동 평가 저장":"Save manual valuation", "저장 전까지 기존 평가액을 계속 사용합니다.":"The existing valuation is used until you save.",
  "분석 범위 만들기":"Create analysis scope", "변경 저장":"Save changes", "과거 기록을 유지한 채 이 분석 범위를 목록에서 삭제합니다.":"Remove this analysis scope from the list while preserving historical records.", "삭제 중":"Deleting", "분석 범위 삭제":"Delete analysis scope", "분석 범위 이름":"Analysis scope name", "설명 (선택)":"Description (optional)", "계좌 전체 포함":"Include entire accounts", "선택한 계좌에 나중에 추가되는 종목도 자동으로 이 분석 범위에 포함됩니다.":"Holdings added to the selected accounts in the future will also be included.", "개별 종목 포함":"Include individual holdings", "계좌 전체와 겹치는 개별 선택은 저장할 때 자동으로 정리됩니다.":"Individual selections overlapping an entire account are deduplicated when saved.", "선택할 보유종목이 없습니다.":"No holdings are available to select.",
  "종목":"Holding", "시장":"Market", "현재 평가액":"Current value", "목표 비중":"Target weight", "목표 0%만 가능":"Only a 0% target is allowed", "합계":"Total", "입력 확인":"Check inputs", "정확히 100%인 비중만 저장합니다. 이 값은 추천이나 주문이 아니라 사용자가 정한 기준입니다.":"Weights must total exactly 100% to save. These are your own targets, not a recommendation or an order.", "목표비중 저장":"Save target weights", "가격 근거 없음":"No price evidence",
  "보유종목 추가":"Add holding", "조회 범위":"Selected scope", "범위를 확인할 수 없습니다":"Scope unavailable", "분석 데이터":"Analysis data", "이 범위에 현재 보유 중인 종목이 없습니다.":"There are no current holdings in this scope.", "종료된 보유종목":"Closed holdings", "평가와 분석에서는 제외되며 수량·매입원가·과거 기록은 보존됩니다.":"Excluded from valuation and analysis. Quantity, cost basis and historical records are preserved.", "종료 시각":"Closed at", "복원":"Restore", "보유종목":"Holdings", "로그인 후 보유종목을 추가할 수 있습니다.":"Sign in to add holdings.", "계좌와 분석 범위 정보를 불러오지 못했습니다.":"Account and scope information could not be loaded.", "먼저 보유 계좌를 만들어야 합니다.":"Create a holding account first.", "계좌 관리 열기":"Open account management",
  "로그인과 사용자 소유권이 확인되기 전에는 분석 범위를 조회하거나 변경하지 않습니다.":"Analysis scopes cannot be read or changed until sign-in and ownership are verified.", "여러 계좌 또는 일부 종목을 하나의 분석 범위로 묶습니다.":"Group accounts or selected holdings into one analysis scope.", "분석 범위 관리":"Manage analysis scopes", "실제 계좌와 별개로, 함께 분석할 계좌와 종목을 묶습니다.":"Group accounts and holdings for analysis without changing the actual accounts.", "활성 범위":"Active scopes", "선택 가능":"Available selections", "분석 범위 정보를 불러오지 못했습니다. 데이터 연결 상태를 확인해 주세요.":"Analysis scopes could not be loaded. Check the data connection.", "새 분석 범위":"New analysis scope", "빈 범위도 만들 수 있으며 구성은 언제든 바꿀 수 있습니다.":"You can create an empty scope and change its contents later.", "변경일 이후의 홈, 오늘 변동, 추가 투입, 위험, 투자랩과 시뮬레이션에 같은 범위가 적용됩니다.":"After the change, the same scope applies to Home, Today, Contribute, Risk, Investment Lab and Simulation.", "아직 만든 분석 범위가 없습니다.":"No analysis scopes have been created yet.",
  "로그인과 계정 소유권이 확인되기 전에는 목표비중을 읽거나 저장하지 않습니다.":"Target weights cannot be read or saved until sign-in and account ownership are verified.", "계좌와 자산그룹별로 사용자가 직접 정한 목표비중을 관리합니다.":"Manage your own target weights for each account and asset group.", "목표비중":"Target weights", "선택한 계좌 또는 자산그룹 안에서 새 투자금을 배분할 기준을 직접 정합니다.":"Set how new contributions should be allocated within the selected account or group.", "선택 범위":"Selected scope", "저장 상태":"Saved status", "검증 필요":"Needs validation", "첫 설정":"First setup", "현재 구성과 일치":"Matches current holdings", "현재 비중을 편집 시작값으로 표시":"Current weights shown as the editing starting point", "저장하면 같은 범위의 이전 승인본은 수정되지 않고 종료 이력으로 남습니다.":"Saving preserves the previous approved version for this scope as a closed record.", "계좌·종목별 목적지 보존":"Account and holding destinations preserved", "현재 범위의 보유종목 구성을 목표비중으로 만들 수 없습니다. 보유종목과 계좌 연결을 먼저 확인해 주세요.":"Target weights cannot be created for these holdings. Check holding and account links first.",
  "소유 계정 이벤트":"Owned account events", "소유권이 확인된 계정 연결을 통해 읽은 거래 및 자산 상태 근거":"Transactions and asset-state evidence read through verified account ownership", "관련 근거 화면":"Related evidence", "계정":"Account", "포지션 스냅샷":"Position snapshots", "세션 근거":"Session evidence",
  "이 화면은 account_id로 소유 계정에 연결된 이벤트만 표시합니다. 연결되지 않은 레거시 행은 account 문자열만으로 소유권을 추론하지 않습니다.":"Only events linked to an owned account by account_id are shown. Ownership of unlinked legacy rows is not inferred from account text.", "일부 이벤트의 표시 근거가 불완전하거나 표시 한도를 넘었습니다. 유효한 행은 유지했지만 이 결과를 전체 거래 원장으로 사용하면 안 됩니다.":"Some event evidence is incomplete or exceeds the display limit. Valid rows remain visible, but this is not a complete transaction ledger.", "이 계정 범위에는 account_id로 소유 계정에 연결된 이벤트가 없습니다. 연결되지 않은 레거시 행은 소유권을 추론하지 않아 표시하지 않습니다.":"This scope has no events linked to owned accounts by account_id. Unlinked legacy rows are omitted because ownership cannot be inferred.", "세션, 소유 계정 연결, 행 무결성 검증이 모두 통과할 때까지 이벤트 데이터는 닫힌 상태로 유지됩니다.":"Event data remains unavailable until session, account ownership and row integrity checks all pass.", "이벤트 읽기를 사용할 수 없습니다.":"Event reads are unavailable.", "이벤트 읽기가 차단됐습니다.":"Event reads were blocked.", "이 계정 범위에 연결된 이벤트가 없습니다.":"No events are linked to this account scope.", "부분 근거":"Partial evidence", "검증 통과":"Validation passed",
  "로그인이 확인되었습니다. 나의 포트폴리오로 이어가세요.":"You are signed in. Continue to your portfolio.", "로그인 상태를 확인하지 못했습니다. 잠시 후 다시 시도해 주세요.":"Your sign-in could not be verified. Please try again later.", "계정 로그인 확인됨":"Account sign-in verified", "포트폴리오로 계속":"Continue to portfolio", "로그인 화면 보기":"View sign-in page", "기존 데이터 연결":"Link existing data", "이전 서비스의 자산 기록은 별도로 확인한 연결 코드로만 연결됩니다. 코드를 다른 사람에게 공유하지 마세요.":"Records from the previous service require a separately verified linking code. Do not share your code.", "현재 연결 코드 입력이 열려 있지 않습니다. 기존 기록이 있다면 신규 포트폴리오 생성 전에 운영자에게 연결을 요청해 주세요.":"Linking code entry is currently closed. If you have existing records, request a link before creating a new portfolio.", "로그인 상태 다시 확인":"Check sign-in again", "로그인 화면으로":"Go to sign in",
  "화면을 불러오는 중":"Loading page", "화면을 준비하고 있어요":"Preparing your view", "요청을 끝까지 처리하지 못했습니다":"The request could not be completed", "이 화면만 다시 불러옵니다.":"Reload this view.", "저장된 포트폴리오 데이터는 변경하지 않았습니다. 같은 문제가 반복되면 아래 확인 코드를 함께 알려 주세요.":"Your saved portfolio data has not changed. If the problem persists, include the reference code below when contacting support.", "확인 코드":"Reference code", "홈으로":"Go home", "현재 요청 범위 밖의 화면은 계속 사용할 수 있습니다.":"Other views remain available.",
};

export function translateManagementCopy(text: string): string {
  const normalized=text.replace(/\s+/g," ").trim();
  const exact=translationEntry(managementEnglish, normalized) ?? translationEntry(commonEnglish, normalized);
  if(exact !== undefined) return exact;
  if (/^[\d,.]+개$/.test(normalized)) return normalized.slice(0,-1);
  let match=/^(\d+)개 목표 설정 가능$/.exec(normalized);
  if(match) return `${match[1]} eligible for targets`;
  match=/^계좌 (\d+) · 종목 (\d+)$/.exec(normalized);
  if(match) return `${match[1]} accounts · ${match[2]} holdings`;
  match=/^승인본 (.+)$/.exec(normalized);
  if(match) return `Approved revision ${match[1]}`;
  return translateManagementActionCopy(text);
}
