import { commonEnglish, translationEntry } from "@/lib/i18n/locale";

export const authEnglish: Readonly<Record<string,string>> = {
  "내 계정": "My account",
  "포트폴리오": "Portfolio",
  "로그인이 확인되었습니다. 나의 포트폴리오로 이어가세요.": "You are signed in. Continue to your portfolio.",
  "로그인 상태를 확인하지 못했습니다. 잠시 후 다시 시도해 주세요.": "Your sign-in could not be verified. Please try again later.",
  "네이버": "Naver",
  "나의 자산, 나의 기록.": "Your assets. Your story.",
  "편한 방법으로 시작하세요.": "Choose how you would like to get started.",
  "다시, 나의 자산 흐름으로.": "Welcome back to your portfolio.",
  "가입한 방법으로 로그인하세요.": "Sign in using the method you registered with.",
  "여러 로그인 정보가 함께 남아 있습니다. 로그아웃 후 사용할 계정 하나로 다시 로그인해 주세요.": "Multiple sign-in sessions were found. Sign out, then sign in to the account you want to use.",
  "이메일 인증 후 로그인해 주세요.": "Verify your email before signing in.",
  "인증 메일 다시 받기": "Resend verification email",
  "메일의 인증 결과를 확인한 뒤 로그인해 주세요.": "Complete email verification, then sign in.",
  "로그인을 완료하지 못했습니다. 다시 시도하거나 다른 방법을 선택해 주세요.": "Sign-in could not be completed. Try again or choose another method.",
  "또는 이메일로 계속": "or continue with email",
  "지금은 로그인에 연결할 수 없습니다. 잠시 후 다시 방문해 주세요.": "Sign-in is currently unavailable. Please try again later.",
  "이미 계정이 있나요?": "Already have an account?",
  "처음 방문하셨나요?": "New here?",
  "12자 이상": "At least 12 characters",
  "비밀번호 입력": "Enter your password",
  "숨기기": "Hide", "표시": "Show", "비밀번호 숨기기": "Hide password", "비밀번호 표시": "Show password",
  "비밀번호 찾기": "Forgot password",
  "가입한 이메일로 재설정 링크를 보내드립니다.": "We will send a reset link to your registered email.",
  "이메일 인증": "Verify email",
  "인증 메일의 링크를 열어 이메일을 확인해 주세요.": "Open the link in the verification email to confirm your address.",
  "새 비밀번호": "New password",
  "앞으로 사용할 비밀번호를 입력해 주세요.": "Enter the password you would like to use.",
  "화면 미리보기 · 로그인 및 데이터 저장 없음": "Design preview · No sign-in or data storage",
  "VARDA-LABS 홈": "VARDA-LABS home",
  "나의 자산을,": "Your wealth,", "더 선명하게.": "in a clearer light.",
  "흩어진 자산의 오늘을 살펴보고,": "See how your assets are doing today.",
  "기록을 바탕으로 다음을 계획하세요.": "Plan your next steps with a clearer view of the past.",
  "한눈에 보는 자산과 변화": "Your assets and changes at a glance",
  "기록으로 확인하는 나의 흐름": "Your progress, grounded in real records",
  "다양한 가정으로 탐색하는 가능성": "Explore possibilities with different assumptions",
  "계좌 비밀번호를 수집하지 않습니다.": "We never collect your brokerage passwords.",
  "소셜 로그인": "Social sign-in", "가입하기": "Sign up", "(설정 준비 중)": "(not available yet)", "준비 중": "Coming soon",
  "화면 미리보기입니다. 실제 로그인은 운영 서비스에서 진행할 수 있습니다.": "This is a preview. Sign in on the live service.",
  "로그아웃 중": "Signing out",
  "로그아웃하지 못했습니다. 로그인 상태가 유지되고 있으니 다시 시도해 주세요.": "Sign-out failed. You are still signed in. Please try again.",
  "비밀번호가 서로 다릅니다. 다시 확인해 주세요.": "The passwords do not match. Please check them.",
  "화면 미리보기입니다. 입력한 정보는 전송하거나 저장하지 않습니다.": "This is a preview. Your input is not sent or stored.",
  "이메일 회원가입": "Sign up with email", "이메일 로그인": "Email sign-in", "이름": "Name", "사용할 이름": "Your preferred name",
  "비밀번호 확인": "Confirm password", "확인 중": "Checking", "이메일로 가입하기": "Sign up with email", "이메일로 로그인": "Sign in with email",
  "이메일 로그인은 준비 중입니다.": "Email sign-in is not available yet.",
  "인증 메일 재전송": "Resend verification email",
  "인증 메일을 다시 요청했습니다. 스팸함도 확인해 주세요.": "A new verification email was requested. Please check your spam folder too.",
  "이메일을 확인해 주세요": "Check your email",
  "으로 받은 인증 메일의 링크를 연 뒤 로그인해 주세요.": " — open the verification link sent to this address, then sign in.",
  "로그인으로 계속": "Continue to sign in", "요청 중": "Sending", "다른 이메일 사용": "Use another email",
  "비밀번호가 서로 다릅니다.": "The passwords do not match.",
  "화면 미리보기입니다. 메일을 보내거나 비밀번호를 변경하지 않습니다.": "This is a preview. No email is sent and no password is changed.",
  "비밀번호를 변경했습니다.": "Your password has been changed.",
  "유효한 재설정 링크가 필요합니다. 새 메일을 요청해 주세요.": "A valid reset link is required. Request a new email.",
  "재설정 메일 요청": "Request a reset email", "비밀번호 재설정": "Reset password", "인증 메일 요청": "Request verification email", "새 비밀번호 확인": "Confirm new password",
  "입력한 이메일에 연결된 계정이 있다면 안내 메일을 보냈습니다. 스팸함도 확인해 주세요.": "If an account is linked to this email, instructions have been sent. Check your spam folder too.",
  "비밀번호 변경": "Change password", "인증 메일 보내기": "Send verification email", "재설정 링크 보내기": "Send reset link",
  "이메일 인증은 준비 중입니다.": "Email verification is not available yet.", "로그인으로 돌아가기": "Back to sign in",
  "기존 포트폴리오 연결": "Link an existing portfolio", "안내받은 일회용 연결 코드": "Your one-time linking code", "연결 코드 확인": "Verify linking code",
  "코드가 전달되었습니다. 서버 확인 후 계정 연결 상태가 반영됩니다.": "Your code was submitted. The link will be updated after server verification.",
  "코드 전달 여부를 확인하지 못했습니다. 중복 제출하지 말고 운영자에게 확인해 주세요.": "We could not confirm the submission. Contact support before submitting again.",
  "계좌 이름을 1~100자로 입력해 주세요.": "Enter an account name between 1 and 100 characters.",
  "로그인 상태를 확인하지 못했습니다. 다시 로그인해 주세요.": "Your session could not be verified. Please sign in again.",
  "계좌 상태가 변경됐거나 같은 이름이 사용 중입니다. 새로고침 후 확인해 주세요.": "The account changed or this name is already in use. Refresh and check again.",
  "계좌를 등록하지 못했습니다. 잠시 후 다시 시도해 주세요.": "The account could not be created. Please try again later.",
  "계좌 이름": "Account name", "예: 나의 증권 계좌": "e.g. My brokerage account",
  "이 계좌의 기준 통화는 KRW입니다. 미국 종목도 종목별 거래 통화로 기록할 수 있습니다.": "This account is valued in KRW. US holdings can still be recorded in their trading currency.",
  "계좌 등록 중": "Creating account", "계좌 등록하고 계속": "Create account & continue",
  "첫 계좌": "First account", "첫 종목": "First holding", "포트폴리오 시작": "Get started", "시작 단계": "Setup progress", "완료": "Complete",
  "나만의 포트폴리오": "Your own portfolio", "새 포트폴리오는 빈 기록에서 시작합니다.": "A new portfolio starts with an empty history.",
  "이전 서비스의 기록이 있다면 기존 데이터를 연결해 주세요.": "If you have records in the previous service, link your existing data.",
  "이전 서비스에 기록이 있나요?": "Have records in the previous service?",
  "기존 자산을 자동으로 가져오지 않습니다. 안내받은 연결 코드가 있다면 새 포트폴리오를 만들기 전에 기존 데이터 연결을 진행해 주세요.": "Existing holdings are not imported automatically. If you have a linking code, link your data before creating a new portfolio.",
  "기존 데이터 연결": "Link existing data", "첫 계좌 등록": "Add your first account",
  "자산을 보관하는 곳의 이름을 정해주세요.": "Give the account holding your assets a name.",
  "계좌번호나 금융기관 비밀번호는 필요하지 않습니다.": "No account number or brokerage password is required.",
  "첫 종목을 기록해볼까요": "Add your first holding", "포트폴리오와 계좌가 준비됐습니다.": "Your portfolio and account are ready.",
  "보유한 종목을 추가하면 나의 자산 흐름이 시작됩니다.": "Add a holding to start tracking your portfolio.", "등록된 계좌 · 원화 기준 평가": "Registered accounts · Valued in KRW",
  "보유 종목 추가": "Add a holding", "지금은 홈 둘러보기": "Explore the home page",
  "종목을 등록하기 전에는 평가액과 수익률이 비어 있을 수 있습니다.": "Value and return may remain empty until you add a holding.",
  "연결해야 할 기존 기록이 없으며, 새 포트폴리오로 시작합니다.": "I have no existing records to link and will start a new portfolio.",
  "새 포트폴리오로 시작하는지 확인해 주세요.": "Please confirm that you want to start a new portfolio.",
  "계정 연결 상태가 변경됐습니다. 새로고침 후 기존 기록을 확인해 주세요.": "Your account linking status changed. Refresh to check your existing records.",
  "포트폴리오를 만들지 못했습니다. 잠시 후 다시 시도해 주세요.": "The portfolio could not be created. Please try again later.",
  "포트폴리오 만드는 중": "Creating portfolio", "새 포트폴리오 만들기": "Create a new portfolio",
  "요청이 많습니다. 잠시 기다린 후 다시 시도해 주세요.": "Too many requests. Please wait and try again.",
  "이 로그인 방식은 아직 준비 중입니다. 다른 방식으로 로그인해 주세요.": "This sign-in method is not available yet. Please choose another.",
  "이메일 인증이 필요합니다. 받은 메일을 확인해 주세요.": "Email verification is required. Please check your inbox.",
  "링크가 만료되었거나 유효하지 않습니다. 새 메일을 요청해 주세요.": "This link is invalid or has expired. Request a new email.",
  "이메일 또는 비밀번호를 확인해 주세요.": "Check your email and password.",
  "가입 정보를 확인하거나 기존 로그인 방식으로 다시 시도해 주세요.": "Check your registration details or use your existing sign-in method.",
  "요청을 완료하지 못했습니다. 잠시 후 다시 시도해 주세요.": "The request could not be completed. Please try again later.",
};

export function translateAuthCopy(text: string): string {
  const normalized = text.replace(/\s+/g, " ").trim();
  const exact = translationEntry(authEnglish, normalized) ?? translationEntry(commonEnglish, normalized);
  if (exact !== undefined) return exact;
  const social = /^(Google|GitHub|네이버)로 (가입하기|로그인)(.*)$/.exec(normalized);
  if (social) return `${social[2] === "로그인" ? "Sign in" : "Sign up"} with ${social[1] === "네이버" ? "Naver" : social[1]}${social[3].replace("(설정 준비 중)", "(not available yet)")}`;
  const provider = /^(Google|GitHub|네이버)(로 계속| 로그인 설정 준비 중|로 연결하지 못했습니다\. 잠시 후 다시 시도해 주세요\.)$/.exec(normalized);
  if (provider) {
    const name = provider[1] === "네이버" ? "Naver" : provider[1];
    return provider[2] === "로 계속" ? `Continue with ${name}` : provider[2] === " 로그인 설정 준비 중" ? `${name} sign-in is not available yet` : `Could not connect to ${name}. Please try again later.`;
  }
  return text;
}
